### ISSUE TITLE
Change REST API response format

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#100]
> - [ ] The output seems to be a JSON dump of a JOOQ record. We need to remove the `fields` field and replace `records` with just its contents
> - [ ] There is excessive quoting. For example this `"{\"access\": \"protected\", \"defined\": true}"` can be simply replaced by `"{"access": "protected",  "defined": true}`

_Originally posted by @gousiosg in https://github.com/fasten-project/fasten/pull/80#issuecomment-721006461_

**Comment by romatallinn** [comment]
@marcomicera a useful task to go forward with in relation to the web platform. To add, however, I guess it would be useful to put keys for every field. Coz right now it's just array.

So, instead:

```        
[
    17,
    16,
     "4.12",
    "OPAL",
    null,
    "{\"commitTag\": \"r4.12\", \"sourcesUrl\": \"https://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12-sources.jar\", \"packagingType\": \"jar\", \"parentCoordinate\": \"\", \"dependencyManagement\": {\"dependencies\": []}}"
 ]
```

Keyed dictionary:
```
[
    "id": 17,
    "package_id": 16,
     "version": "4.12",
    etc...
 ]
```

**Comment by marcomicera** [comment]
Related: https://github.com/fasten-project/fasten/issues/124.

**Comment by marcomicera** [comment]
Done in 3ea80350.

**Comment by tmortagne** [comment]
>  There is excessive quoting. For example this "{\"access\": \"protected\", \"defined\": true}" can be simply replaced by "{"access": "protected", "defined": true}

Note that this one does not seems to be fixed on http://lima.ewi.tudelft.nl/api but maybe the server is not up to date (but it's strange since the first point is fixed). See http://lima.ewi.tudelft.nl/api/mvn/packages/org.eclipse.jetty:jetty-webapp/9.4.17.v20190418/metadata for example.

**Comment by marcomicera** [comment]
> but maybe the server is not up to date

I think the old RESTeasy/Jetty implementation is still running on that server. Someone should deploy the new Spring/Tomcat version. @proksch

**Comment by proksch** [comment]
The server should run the new REST API since several days already... (btw. you can also access it via http://api.fasten-project.eu/api/ now, but Lima should still work. We will report on this before the next dev call). I am not sure about the state of the excessive quoting problem though. I thought we had an issue for this, but maybe I had this exact here issue in mind.... If there is none, please create a new issue for this and mention the concrete endpoint that is affected.

**Comment by MihhailSokolov** [comment]
> The server should run the new REST API since several days already... (btw. you can also access it via http://api.fasten-project.eu/api/ now, but Lima should still work. We will report on this before the next dev call). I am not sure about the state of the excessive quoting problem though. I thought we had an issue for this, but maybe I had this exact here issue in mind.... If there is none, please create a new issue for this and mention the concrete endpoint that is affected.

I just resolved the issue with escape characters. We will deploy the latest version a bit later today because we first need to fix some configuration.

**Comment by tmortagne** [comment]
> btw. you can also access it via http://api.fasten-project.eu/api now

Much better domain name indeed, but it does not seems to work (getting a "502 Bad Gateway" error).

But maybe it's related to "we first need to fix some configuration".

**Comment by tmortagne** [comment]
Actually http://lima.ewi.tudelft.nl/api/ is down too now so I guess it is indeed the configuration issue.

**Comment by wzorgdrager** [comment]
We just deployed the latest version, it should work properly now.

**Comment by tmortagne** [comment]
It's better but http://api.fasten-project.eu/api/mvn/packages/org.eclipse.jetty:jetty-webapp/9.4.17.v20190418/metadata for example produces an invalid JSON. Probably because there is still `"` around the metadata fiel value.

**Comment by MihhailSokolov** [comment]
> It's better but http://api.fasten-project.eu/api/mvn/packages/org.eclipse.jetty:jetty-webapp/9.4.17.v20190418/metadata for example produces an invalid JSON. Probably because there is still `"` around the metadata field value (seems to suggest we are doing String concatenation instead of using some JSON writer tool).

You are indeed correct. Thanks for noticing! Could you please open an issue for it and I will try to fix it tomorrow

**Comment by tmortagne** [comment]
> You are indeed correct. Thanks for noticing! Could you please open an issue for it and I will try to fix it tomorrow?

Done: https://github.com/fasten-project/fasten/issues/174
