### ISSUE TITLE
Dockerize the REST API

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#101]
It might be possible to use `openjdk:11.0.9-jre-slim` and simply run the REST API JAR file.
We might force the creation of the JAR file via a:

- Maven goal
- Docker stage
- Making the main Docker-compose service depend on a "builder" service

That's also my personal order of preference for this.

If that's not possible, I'm afraid we would need to use `maven` images, which I think are even bigger in general.

**Comment by gousiosg** [comment]
Why not reuse the existing infrastructure and link with our plug-in runner component?

**Comment by marcomicera** [comment]
> Why not reuse the existing infrastructure and link with our plug-in runner component?

@proksch mentioned in an email that there will be a k8s deployment in the future, and @wzorgdrager would assist me with that.

**Comment by gousiosg** [comment]
This answer is orthogonal to my question. Yes @wzorgdrager will help with the deployment files, but we should use the existing docker building infrastructure to deploy

**Comment by marcomicera** [comment]
> but we should use the existing docker building infrastructure to deploy

I was simply not aware of that

> Why not reuse the existing infrastructure and link with our plug-in runner component?

because Docker hasn't been mentioned here.

@gousiosg could you please tell me where can I find this infrastructure and what it is about?

**Comment by MihhailSokolov** [comment]
@marcomicera @gousiosg is there any progress on this one?

**Comment by MihhailSokolov** [comment]
@gousiosg by reusing existing Docker deployment you mean making it a plugin and deploying it with the FASTEN server the same way we deploy other plugins?
If yes, I actually think it is not quite necessary. REST API does not need to consume from Kafka (or any other place), so it doesn't really need the FASTEN server. So I think it is easier to deploy it separately. What do you think?

**Comment by proksch** [comment]
Make it as simple as possible. I would not tie it to the FASTEN Server, as it is not a plugin.

**Comment by gousiosg** [comment]
The idea was that if we use it as part of the server, we would be able to reuse the same build, deployment and K8S pipeline. When I wrote that comment, you had to run the Rest API in a `screen` session, with no supervision etc. If this is the fastest way to do that, so be it for the moment. Eventually, we need to deploy it within K8S.

**Comment by marcomicera** [comment]
> @marcomicera @gousiosg is there any progress on this one?

No, I didn't work on this.
