### ISSUE TITLE
Include metadata in base entities endpoints

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#105]
> General design question; why do we have different endpoints for `{entity}` and `{entity}/metadata`, for example `{pkg_ver}` and `{pkg_ver}/metadata`? When retrieving an entity, I would expect all related metadata to be retrieved as well.

_Originally posted by @gousiosg in https://github.com/fasten-project/fasten/pull/80#issuecomment-721085816_

Also, the [Wiki](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects) should be updated accordingly.

**Comment by marcomicera** [comment]
So endpoints that return single entities (e.g., `{entity}`) seem to be including their corresponding `metadata` fields already ([table](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects)).
@gousiosg do you want to get rid of `{entity}/metadata` endpoints?

**Comment by proksch** [comment]
I remember that @gousiosg wanted to keep them separately. I do not remember the argument though... I would say why not include it in the first step (to make it available at all) and review this decision later, when the API get's more stable.

**Comment by MihhailSokolov** [comment]
> I remember that @gousiosg wanted to keep them separately. I do not remember the argument though... I would say why not include it in the first step (to make it available at all) and review this decision later, when the API get's more stable.

Then if @gousiosg agrees, I am closing this issue and keeping `{entity}` and `{entity}/metadata` separate as they currently are.

**Comment by gousiosg** [comment]
I 'd prefer to have it in the same call, in most cases we need the metadata more than the actual entity (e.g. when querying `callables`)

**Comment by MihhailSokolov** [comment]
> I 'd prefer to have it in the same call, in most cases we need the metadata more than the actual entity (e.g. when querying `callables`)

So then just remove the `{entity}/metadata` because `{entity}` already returns all the information available for the given entity (including metadata)?
