### ISSUE TITLE
Switch to Spring for the REST API

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#111]
As far as the REST API is concerned, there are still a few issues:

- A couple of timeout #86
- CDI not working (needed for unit testing) #87
- Unsupported concurrent requests #93 

All (or part of) these problems could be solved together by switching from RESTeasy to Spring (especially for Spring DI).

This change would also affect integration tests #89 and Dockerization #101.

**Comment by gousiosg** [comment]
Could you please explain how / why the problems you describe will be solved with Spring?

**Comment by marcomicera** [comment]
> Could you please explain how / why the problems you describe will be solved with Spring?

Sure, sorry for my brevity.

1. First things first: the Spring DI. Spring has some dedicated annotations like `@Autowired` and `@Service` that already allowed me to have a fully-functional CDI system. This simplifies unit testing a lot #87.
1. I already noticed that this Spring version of the REST API doesn't suffer from most of the timeouts we had before. I think this is due to Spring's embedded Tomcat Servlet container. I didn't manage to find out why Jetty caused timeouts, so a very dumb solution would be to just get rid of it.
1. For concurrency, I think this is going to be handled by Spring & Tomcat. I didn't find any simple solution for Jetty rather than spawning threads manually https://github.com/fasten-project/fasten/issues/93#issuecomment-717196048. I think this could be achieved with a simple `server.tomcat.max-threads=400` with the Spring's embedded Tomcat. There seem to be lots of [other tweaks](https://dzone.com/articles/concurrency-control-in-rest-api-with-spring-framew) as well for Spring.

**Comment by marcomicera** [comment]
@ilyagrishkov @MihhailSokolov do I have to keep [Main.java](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/Main.java) and [RestAPIPlugin.java](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/RestAPIPlugin.java) that implements the PF4J `Plugin` interface and [`DBConnector`](https://github.com/fasten-project/fasten/blob/kbapi/core/src/main/java/eu/fasten/core/plugins/DBConnector.java)?\
It's a bit complicated to launch Spring through such classes.

I'd just use:
```java
@SpringBootApplication
public class RestApplication {

    public static void main(String[] args) {
        SpringApplication.run(RestApplication.class, args);
    }
}
```

With a Spring `@Component` that connects to the KnowledgeBase at the beginning:
```java
@Component
public class KnowledgeBaseConnector {

    @PostConstruct
    public void connectToKnowledgeBase() { /* ... */ }
}
```

So instead of launching it with `mvn exec:java` it would be: `mvn spring-boot:run`.\
So technically, not a PF4J plugin anymore: is it ok?

**Comment by marcomicera** [comment]
Done in #123.
