### ISSUE TITLE
Change callables' metadata endpoint (and query)

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#114]
### Problem

As pointed out by @zikanl is his last email, one of the reasons why the query behind the [callables' metadata endpoint](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#callables) (`/mvn/packages/{pkg}/{pkg_ver}/{fasten_uri}/metadata`) causes Jetty to timeout could be a complete scan of the `callables` table, as we're not specifying the module ID as a path parameter (see the [Knowledge Base schema](https://user-images.githubusercontent.com/8766163/93773151-06b68780-fc20-11ea-8a9e-8166ee80dfc6.png)).

Also, according to the Wiki (and to my last call with @proksch & @ilyagrishkov):

> Callable ID = module ID (package version) + FASTEN URI + other

May I ask for more info about that?

### Proposed solution

I'd change `/mvn/packages/{pkg}/{pkg_ver}/{fasten_uri}/metadata` to one of the following:
- `/mvn/packages/{pkg}/{pkg_ver}/{module}/{callable}/metadata`
- `/mvn/packages/{pkg}/{pkg_ver}/{module}/{callable}/metadata?fasten_uri=...`
- `/mvn/packages/{pkg}/{pkg_ver}/{module}/{callable}/{fasten_uri}/metadata`
- `/mvn/packages/{pkg}/{pkg_ver}/{module}/{fasten_uri}/metadata`

Consequently, the [corresponding query](https://github.com/fasten-project/fasten/blob/24b01bd3ac1250042ac0df1fcc307678e11f91e1/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java#L1102-L1112) would get a new `WHERE` clause.

**Comment by marcomicera** [comment]
Another reason to change these endpoints: Tomcat does not support "(", ")", and "$" in path parameters, even when UTF-8 encoding is enabled https://github.com/fasten-project/fasten/pull/123#issue-523340984, [source](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server.tomcat.relaxed-path-chars).

**Comment by MihhailSokolov** [comment]
@marcomicera have reached an agreement about this issue?

**Comment by marcomicera** [comment]
> @marcomicera have reached an agreement about this issue?

No. @zikanl would you be ok with one of the following?

> ### Proposed solution
> I'd change `/mvn/packages/{pkg}/{pkg_ver}/{fasten_uri}/metadata` to one of the following:
> 
> * `/mvn/packages/{pkg}/{pkg_ver}/{module}/{callable}/metadata`
> * `/mvn/packages/{pkg}/{pkg_ver}/{module}/{callable}/metadata?fasten_uri=...`
> * `/mvn/packages/{pkg}/{pkg_ver}/{module}/{callable}/{fasten_uri}/metadata`
> * `/mvn/packages/{pkg}/{pkg_ver}/{module}/{fasten_uri}/metadata`

**Comment by zikanl** [comment]
Let us discuss this in detail during the call tomorrow.

**Comment by MihhailSokolov** [comment]
We have added a hash index on `callables.fasten_uri`, so now there is no need to join with modules. It is very fast with that index. See https://github.com/fasten-project/fasten/issues/170#issuecomment-745256320
