### ISSUE TITLE
Add FastenServer tests

### ISSUE THREAD

**Issue by MihhailSokolov** [fasten-project/fasten#116]
## Is your feature request related to a problem? Please describe.
FastenServer does not have any tests which makes the code more error-prone.

## Describe the solution you'd like
Some tests must be written to at least test FastenServer basic functionality like setting database connection for plugins and etc.

**Comment by StefanosChaliasos** [comment]
https://github.com/fasten-project/fasten/pull/110#issuecomment-723649341

**Comment by proksch** [comment]
The server will be replaced with the [new loader platform](https://github.com/fasten-project/data-processing/). I am closing this issue, as the server will be replaced in the coming weeks.
