### ISSUE TITLE
GraphMavenResolver and DatabaseMerger must communicate by IDs

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#122]
Presently, GraphMavenResolver returns a set of Dependency objects. DatabaseMerger requires a list of artifacts in an undocumented format. The two classes will have to work together heavily in any scenario for impact-change analysis, so one must be able to pass data along efficiently.

The most natural way of representing revisions is by their ID in the Postgres database. A Maven resolver should return a set of such IDs, and a DatabaseMerger should accept a set of such IDs. This will also mitigate the unavoidable traps and pitfalls of using a text-based representation (see issue #120 ).

**Comment by MihhailSokolov** [comment]
GraphMavenResolver's part is implemented in 6d75ac5
@ilyagrishkov should soon implement DatabaseMerger part as well
