### ISSUE TITLE
Parse REST API metadata response fields

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#124]

**Comment by zikanl** [comment]
It would be good to have a more detailed description of (JSON) response for endpoints first.

**Comment by marcomicera** [comment]
> It would be good to have a more detailed description of (JSON) response for endpoints first.

Now that I've managed to properly format JSON responses (#100), I'm starting to include a sort of a JSON schema in the Wiki page. Check the "response body" column of the first ["packages and package versions" table](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#packages-and-package-versions). I'll finish filling the other tables tomorrow.

**Comment by MihhailSokolov** [comment]
@marcomicera is it done or still in progress? If in progress, what is left to be done?

**Comment by marcomicera** [comment]
> @marcomicera is it done or still in progress? If in progress, what is left to be done?

I was still updating the Wiki page with a more accurate version of the response bodies as @zikanl suggested, but I didn't actually start parsing the metadata field. You can take over this.

**Comment by romatallinn** [comment]
Hi @marcomicera, I am not sure if this is the issue about this problem, but I am getting `metadata` response in the format of:
`"{"final": true, "access": "packagePrivate", "superClasses": ["/java.awt.event/WindowAdapter"], "superInterfaces": []}"`

The quotes in the beginning and the end of the response screws it up because now it stringifies everything incorrectly.

**Comment by marcomicera** [comment]
> Hi @marcomicera, I am not sure if this is the issue about this problem, but I am getting `metadata` response in the format of:
> `"{"final": true, "access": "packagePrivate", "superClasses": ["/java.awt.event/WindowAdapter"], "superInterfaces": []}"`

Sorry for the late reply: @MihhailSokolov could you please check this? Thanks!

**Comment by MihhailSokolov** [comment]
I am pretty sure I fixed it a couple of days ago. Or does the problem still persist?
