### ISSUE TITLE
Synchronization issues for analyzers & plugins within FASTEN

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#126]
Plugins and analyzers work in parallel within the overall FASTEN architecture. This may give rise to synchronization issues, for example:
 - A new message arrives on an new version for a product
 - JavaCGOpal consumes the message and starts work
 - RepoCloner consumes the message and starts work
 - RepoCloner finished and produces a message to _fasten.RepoCloner.out_
 - RapidPlugin consumes from _fasten.RepoCloner.out_ and starts work
 - RapidPlugin is done and produces to _fasten.RapidPlugin.callable.out_
 - the FASTEN meta-data DB consumes from _fasten.RapidPlugin.callable.out_ and tries to put the meta-data in the callable tables, but no callables are there yet
 - JavaCGOpal finishes and produces callable to the FASTEN meta-data DB

Potential fix: create a separate topic where downstream plugins (RapidPlugin, VulnerabilityProducer, etc.) can consume messages that signal that callables are indeed available in the meta-data DB. Those messages would need the same info as now available in RepoCloner.out, or potentially more status information if it has become available (JavaCGOpal failed, RepoCloner failed, etc.)

**Comment by gousiosg** [comment]
In the scenario you describe,`RapidPlugin` is consuming from the wrong topic: it should use the output of `MetadataPlugin` instead.

Despite this, the main issue is that `RapidPlugin` has 2 dependencies: i) on `RepoCloner` (for the repo data), and ii) on `MetadataPlugin ` (for the callables). There is currently no way to ensure that `RapidPlugin` can start after _both_ dependencies produced an output message, as this requires a join between the two streams. Due to timing differences (`OPAL` can be way slower than `RepoCloner`), this join might need to consider the Cartesian product of the two streams as window-based joins will leave messages unprocessed.

The easiest workaround would be to create a Flink job that emits the appropriate message when the join condition was successful. @wzorgdrager what do you think?

**Comment by wzorgdrager** [comment]
If it is known that producing metadata is always slower, isn't it enough to indeed have the output topic of `MetadataPlugin` as a trigger for the `RapidPlugin`? Or does the `RepoCloner` output specific information which is necessary for `RapidPlugin` and not available in the output topic for `MetadataPlugin`?

Anyhow, as Magiel mentions this might be a problem for more downstream plugins. I also think a good approach would be to have a job solely joining streams and see if artifacts are completely downloaded/processed/extracted. We could go for a Flink job and deploy it on the cluster also used for CodeFeedr, but I think it's preferable to just deploy a single Docker container with a [Flink job cluster](https://ci.apache.org/projects/flink/flink-docs-stable/ops/deployment/kubernetes.html#deploy-job-cluster) (less maintenance :smile: ).  Alternatively, a simple [Kafka streams](https://kafka.apache.org/documentation/streams/) job could be written. 

Maybe a good first step would be to identify for each plugin/analyzer on which plugins they rely in the upstream?

**Comment by MagielBruntink** [comment]
We have documented what information is needed: https://github.com/fasten-project/quality-analyzer#maven

Another solution could be to forward such information along the chain of tools, so that downstream plugins can safely consume from MetadataPlugin (what topic, btw?) and still have the needed  info.

**Comment by wzorgdrager** [comment]
@MagielBruntink For now you could try to use the `fasten.MetadataDBJavaExtension.out` topic to get the output of the MetadataPlugin. I'll (soon) work on a more permanent solution involving joining those (upstream) streams. I'll keep you up-to-date on that!

**Comment by gousiosg** [comment]
One thing we could do is to define processing stages. By defining a stage, a plug-in gets assigned a Kafka topic that is populated with events (incl metadata) that signify the end of that stage. The end of a stage means that one or (most usually) more plug-ins have finished processing the artifact in that stage. Those messages are processed by special jobs (Flink?) that can join streams together and understand the outputs of each stage. Some stages that come to mind:

* Input stage: Data about the availability of an artifact is made available (we have that already)
* Raw data processing stage: The artefact's src code has been downloaded and its callgraph metadata is in the DB. The RapidPlugin should depend on this stage
* Metadata stage: Source code metrics, Github data, build data, etc are made available in the DB. The security plug-in and any plug-in that updates the in-memory dependency graphs should depend on that stage
* REST API stage: Data about the artifact can be served by the API

**Comment by wzorgdrager** [comment]
@gousiosg @MagielBruntink I created a new repository for a Flink job dealing with this issue. Can be found [here](https://github.com/fasten-project/synchronize-javacg) (if you have ideas for a better name, let me know). You can keep track of that repo to follow the progress. Let's move our discussion there. I shall create some issues with ideas/discussion points for the specific implementation, and if you want you can give input on that.

**Comment by wzorgdrager** [comment]
Discussion is moved to [this issue in the correct repository](https://github.com/fasten-project/synchronize-javacg/issues/1).
