### ISSUE TITLE
Add Package instance endpoint

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#129]
- Implement `/{pkg}` that retrieves the `Package` instance _(forge, repo, etc)_. 
- It would be useful to also include in there the latest `PackageVersion` for a better flow.

**Comment by marcomicera** [comment]
> * It would be useful to also include in there the latest `PackageVersion` for a better flow.

This is not trivial, I've been using:

```sql
SELECT		p.*, pv.version
FROM		packages p JOIN package_versions pv ON p.id = pv.package_id
WHERE		p.package_name = 'com.goldmansachs.obevo:obevo-db-postgresql'
ORDER BY	CAST(SPLIT_PART(pv.version, '.', 1) AS INTEGER) DESC,
		CAST(SPLIT_PART(pv.version, '.', 2) AS INTEGER) DESC,
		CAST(SPLIT_PART(pv.version, '.', 3) AS INTEGER) DESC
LIMIT		1;
```

Assuming that `version` follows this format: `INTEGER`.`INTEGER`.`INTEGER`, but this is not always the case, e.g.:

```sql
SELECT	version
FROM	package_versions
LIMIT	10;
```

returns:

```
       version
----------------------
 0.0.1
 7.2.0
 1.1.0.Final
 v2beta1-rev53-1.22.0
 2.1.3
 2.63.0
 3.6.4
 2.0.0
 7.4-rc-1
 8.1.10.v20130312
```

@romatallinn how would you like to programmatically determine the last version in such cases?

I have two empirical ideas that might not be super reliable...: using `MAX(package_versions.id)` or `MAX(package_versions.created_at)`. Not really elegant...

**Comment by romatallinn** [comment]
> `MAX(package_versions.created_at)`. Not really elegant...

What is exactly the problem with `package_versions.created_at`?

**Comment by marcomicera** [comment]
> What is exactly the problem with `package_versions.created_at`?

Actually, I don't know whether that represents the row insertion time into the DB or the actual package version creation time.

**Comment by romatallinn** [comment]
> the row insertion time into the DB or the actual package version creation time.

Good question. I asked @MihhailSokolov, he says it's the date when the package was published, thus what we need. Nevertheless, I still see the possible problem with patches for older versions.

Either way, for the moment, I think you can use the date.

**Comment by marcomicera** [comment]
@romatallinn done. You can find the details in the first row of the ["packages and package versions" endpoints table](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#packages-and-package-versions).
