### ISSUE TITLE
Do not return arrays for endpoints returning only one row

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#131]
E.g., `/mvn/packages/{pkg}` should return:

```json
{
    "id": 61001,
    "package_name": "com.lemoulinstudio.jnag:jnag-utils-jse-rds",
    "forge": "mvn",
    "project_name": "Jnag utils for Red Dwarf Jse clients",
    "repository": null,
    "created_at": null,
    "version": "1.2.1"
}
```

And not:

```json
[
	{
		"id": 61001,
		"package_name": "com.lemoulinstudio.jnag:jnag-utils-jse-rds",
		"forge": "mvn",
		"project_name": "Jnag utils for Red Dwarf Jse clients",
		"repository": null,
		"created_at": null,
		"version": "1.2.1"
	}
]
```

The [Wiki page](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects) should be updated accordingly.

**Comment by marcomicera** [comment]
Also `limit` and `offset` query params should be deleted.

**Comment by mayralgr** [comment]
@marcomicera I would like to work on this, can I be assigned? and can you give me as much information as you can? It is my first pr :)

**Comment by marcomicera** [comment]
> @marcomicera I would like to work on this, can I be assigned?

Sure! Thanks a lot for dedicating your time to FASTEN.

> and can you give me as much information as you can? It is my first pr :)

Of course!
#80 is the draft PR for the REST API. You can see there that the REST API code resides on the [`kbapi` branch](https://github.com/fasten-project/fasten/tree/kbapi), specifically in the [`analyzer/restapi-plugin` folder](https://github.com/fasten-project/fasten/tree/kbapi/analyzer/restapi-plugin). You can find instructions on how to launch the REST server in the [README file of that directory](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/README.md).

For the purpose of this issue, you would need a running Postgres instance (whose URL & username can be set in the [REST server configuration file](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/src/main/resources/application.properties)). The password must be set [as an ENV var](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/README.md#usage) in the command line.

As far as this "array" mini-problem is concerned, I think you wouldn't even need to replicate one of the tables of our Knowledge Base ([schema](https://github.com/fasten-project/fasten/blob/kbapi/analyzer/restapi-plugin/README.md#usage))... you could just create a dummy table and show how we can avoid returning a JSON array when the result obviously contains 1 element only.
We would then propagate such a change to all the endpoints that only return 1 item (ctrl/cmd + f "Only one element" in our [endpoints table](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects)).

Should you have any questions, feel free to ping me here. Thanks a lot again for your help!

**Comment by MihhailSokolov** [comment]
@mayralgr are you still working on this? Because I have a fix for this issue. It's just one line change :)

**Comment by mayralgr** [comment]
@MihhailSokolov I was but I had a little hard time installing everything, I was going to start today. If you have it, don't worry. I'll look for another one. Thank you! If anything, if you have a suggestion for a first pr, I am open to it :)

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov I was but I had a little hard time installing everything, I was going to start today. If you have it, don't worry. I'll look for another one. Thank you! If anything, if you have a suggestion for a first pr, I am open to it :)

Actually, I do have a suggestion for you :)
I would appreciate if you could take up the issue #155 if you don't mind.
Good luck!

**Comment by mayralgr** [comment]
@MihhailSokolov thank you, I will work on it :)

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov thank you, I will work on it :) 

Perfect, thanks! If you have any questions don't hesitate to ask.
