### ISSUE TITLE
Please rename the eu.fasten.core.data.Graph class

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#136]
The eu.fasten.core.data.Graph class has a name overlapping with JGraphT's Graph interface. Such a short and generic name should be reserved to interfaces. The class appears to be a very specific implementation.

**Comment by proksch** [comment]
I am not sure if this has been resolved in the meantime, but I disagree with the reasoning.

There is also always the option to use fully qualified type references, so this is not a blocker.

I will close this issue for now as a "wont-fix".

**Comment by gdrosos** [comment]
Actually this issue has been resolved on 3558221d0bd060b43e5350149a61bda5f4b0116c through #369 .
