### ISSUE TITLE
Please start to use type-specific containers pervasively

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#137]
Throughout the FASTEN codebase a large number of primitive-type containers and interfaces using objects (e.g., List<Long>, Set<Integer>, etc.) are used both in method specifications and as concrete containers.

For primitive types, such containers are extremely expensive, as they require an object per contained element. The memory footprint is 4-5 times that of the stored data. If we intend to scale our analysis to the size of the Maven ecosystem they will become a liability.

Please consider using fastutil's primitive containers instead. They are drop-in replacements (they satisfy the corresponding java.util interfaces). Besides reducing the constant boxing and unboxing they reduce significantly the memory footprint and the number of generated objects, improving by orders of magnitude the pressure on the garbage collector.

For example,

List<Int> -> IntList
ArrayList<Integer> -> IntArrayList
Set<Long> -> LongSet
HashSet<Long> -> LongOpenHashSet
HashMap<Long,Long> -> Long2LongOpenHashMap
HashMap<Int,T> -> Int2ObjectOpenHashMap<T>

**Comment by proksch** [comment]
I hope that this issue has been settled by now and I think @ashkboos knows these type by heart by now. I'll close this issue.
