### ISSUE TITLE
Call from an artifact to a dependency not listed in OPAL call graph output

### ISSUE THREAD

**Issue by amottier** [fasten-project/fasten#140]
## Describe the bug
I'm using a very [basic project](https://github.com/fasten-project/fasten/files/5597021/minimal-projects-for-testing-purpose.zip) (a one class application with a one class library) to test the call graph generator. In the JSON output I can find all calls except a call from `MyApp` class `run` method to `Speaker` class `sayHello` method packaged in `my-lib`.

## To Reproduce
1. Download `javacg-opal-0.0.1-20201123.120959-1-with-dependencies.jar` from https://github.com/fasten-project/fasten/packages/514198
2. Download and unzip my [example application](https://github.com/fasten-project/fasten/files/5597021/minimal-projects-for-testing-purpose.zip)
3. Run the call graph generator with addition of missing slf4j to classpath on `my-app` artifact with dependency on `my-lib`: `java -cp "javacg-opal-0.0.1-20201123.120959-1-with-dependencies.jar:/home/antoine/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/home/antoine/.m2/repository/org/slf4j/slf4j-jdk14/1.7.30/slf4j-jdk14-1.7.30.jar" eu.fasten.analyzer.javacgopal.Main -a /path/to/my-app-1.0-SNAPSHOT.jar -d /path/to/my-lib-1.0-SNAPSHOT.jar -m FILE -ma CHA -s -o output.json`

## Expected behavior
I expect to have the method `sayHello` listed under `externalTypes` -> `/eu.fasten.dummy.mylib/Speaker` and an external call from `run` method (id `2`) to `sayHello` in `externalCalls`. Instead I got this result: [output.json.txt](https://github.com/fasten-project/fasten/files/5597148/output.json.txt)

## Logs
Logs report 6 calls but include in this figure a call from method 0 to 0 (constructor of `MyApp` class calling itself) that does not really make sense.
```
15:06:26.922 [main] INFO eu.fasten.analyzer.javacgopal.Main - Resolved 2 nodes, 6 calls in 3,446 seconds
```

## Environment (please complete the following information):
 - OS: Debian Buster 10
 - Java version:
   - To run call graph generator: openjdk version "11.0.9" 2020-10-20 
   - Use to build the application and library jar: openjdk version "1.8.0_275"

**Comment by amottier** [comment]
On a side note, I'm not sure about the purpose of `output.json_my-app-1.0-SNAPSHOT_merged` compared to `output.json`. During my test I even didn't realized that such file was created as it is not mention in the [README.md](https://github.com/fasten-project/fasten/blob/opal-gh-pkg/analyzer/javacg-opal/README.md) and not specified on the command line.

**Comment by amottier** [comment]
@ashkboos did you get a chance to take a look at this issue? I just tried again with latest version currently available on `develop` branch and I'm still not able to get an accurate call graph.

**Comment by ashkboos** [comment]
@amottier Have you tried the RTA algorithm? If you set the `-ga` CLI argument to `RTA` you won't have this missing edge anymore. I.e. use this command `-a myApp.jar -i FILE -g -ga RTA -o o.json` to generate the call graph for `myApp`. ATM the merging doesn't support RTA generation, since this functionality is mostly used as a library the CLI support is not very extensive. However, if you want you can generate these call graphs using RTA and then Stitch them using the LocalMerger Library in the core package.

Also about the self-referring edge, it is not a real edge, we used to use this as a place holder edge to be considered while stitching the class initializers. However, we don't use it anymore since we decided to deal with them in a different manner.

**Comment by amottier** [comment]
@ashkboos I just give a try to RTA algorithm (I was relying on [default](https://github.com/fasten-project/fasten/blob/develop/analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/Main.java#L91) that is RCA) and it seems to provide expected result.

I did run `java -jar javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar -ga RTA -a my-app-1.0-SNAPSHOT.jar -d my-lib-1.0-SNAPSHOT.jar -i FILE -ma CHA -m -o outputRTA-CHA.json` and I can see the call from `run` method in my-app to `sayHello` in my-lib (see attached outputRTA-CHA.txt
[outputRTA-CHA.txt](https://github.com/fasten-project/fasten/files/5889051/outputRTA-CHA.txt)
). So I'm not sure to understand "ATM the merging doesn't support RTA generation".

Thanks for the clarification regarding the self-referring edge.

**Comment by ashkboos** [comment]
@amottier by "ATM the merging doesn't support RTA generation", I meant ATM we cannot generate the CG using RTA and then pass the generated files to the merger, so you already did it in the right way.

**Comment by amottier** [comment]
If I understand correctly you mean that if I generate individual call graph for my-app and my-lib (with options `-a my-xxx.jar -i FILE -g -ga RTA -o xxx.json`) I'll not be able to merge the two json files in a single one using `javacg-opal`. Did I correctly understand your point?

**Comment by ashkboos** [comment]
Yes, exactly.

**Comment by amottier** [comment]
Ok thanks for your help! One last question: does it makes sense to switch the default algorithm for call graph generation from `CHA` to `RTA`? Or something motivate to keep `CHA` as default?

**Comment by ashkboos** [comment]
Yes, I agree that we should probably make it `RTA`, for now. Note that the reason that we use `CHA` right now is that this algorithm is the default for most of the generators. However, we are suspected that there might be a bug in the `CHA` implementation of the OPAL library that causes these missing edges. We are contacting the maintainers of the library to make sure that they fix this if it's a bug or let us know if we are missing something.
