### ISSUE TITLE
Allow CORS requests

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#143]
The web platform is built on React. Thus, it uses the client to communicate with API. In the current configuration, Rest API is blocking such requests due to CORS restrictions. Therefore, we need to allow it.

For now, I am having a workaround for my needs by adding `@CrossOrigin` annotation to all API endpoints that I use. There is probably a more elegant way of applying the rule to all endpoints at once.

**Comment by Luffy-programmer** [comment]
I am a beginner and want to contribute, but I don't know how.
Help!

**Comment by MihhailSokolov** [comment]
Should be solved in c7524ef
@romatallinn could you test it to see if my solution works? If it doesn't then we'll add `@CrossOrigin` to every API class.

**Comment by MihhailSokolov** [comment]
> I am a beginner and want to contribute, but I don't know how.
> Help!

Hello @Luffy-programmer. We are happy that you want to contribute! Please read our contribution guide [here](https://github.com/fasten-project/fasten/blob/master/CONTRIBUTING.md)

**Comment by romatallinn** [comment]
LGTM.
