### ISSUE TITLE
Implement search with filters

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#144]
It would be useful for the frontend project to have a search feature with mixed output, which means that it looks over and returns different types of components (not only packages but modules and callables as well).

(although for starters, search over just packages would be enough)

**Comment by MihhailSokolov** [comment]
@romatallinn Would the substring search in package names be enough? Also what should be the output then, full package record or something else?

**Comment by romatallinn** [comment]
> Would the substring search in package names be enough?
Yes, this would be sufficient for now.

> what should be the output then, full package record or something else?
Yes, the array of Package instances.

**Comment by MihhailSokolov** [comment]
Implemented in a8af2efe708d0beccdc7e162b1ebbd099e1d1c7f
