### ISSUE TITLE
Refactor POMAnalyzer to use proper MavenResolver

### ISSUE THREAD

**Issue by MihhailSokolov** [fasten-project/fasten#145]
## Is your feature request related to a problem? Please describe.
All the analysis in POMAnalyzer is done manually by inspecting the POM file and parents' POM files which is tedious and can be error-prone.

## Describe the solution you'd like
A MavenResolver can provide an effective POM which already has all the information needed to be extracted. Therefore only one file will be analyzed and there is no need to deal with variables resolution and inheritance manually.

## Additional context
Code examples on how to use Maven Resolver:
- [https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-tools/xwiki-commons-tool-extension-plugin/src/main/java/org/xwiki/tool/extension/util/ExtensionMojoHelper.java#L308](https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-tools/xwiki-commons-tool-extension-plugin/src/main/java/org/xwiki/tool/extension/util/ExtensionMojoHelper.java#L308)
- [https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-repositories/xwiki-commons-extension-repository-maven/src/main/java/org/xwiki/extension/repository/aether/internal/AetherExtensionRepository.java#L688](https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-repositories/xwiki-commons-extension-repository-maven/src/main/java/org/xwiki/extension/repository/aether/internal/AetherExtensionRepository.java#L688)

**Comment by proksch** [comment]
The revised [pom-analyzer](https://github.com/fasten-project/data-processing/tree/main/plugins/pom-analyzer) is based on the Maven resolver from Shrinkwrap. This should fix this issue.
