### ISSUE TITLE
Remove escape characters from REST API responses

### ISSUE THREAD

**Issue by MihhailSokolov** [fasten-project/fasten#155]
## Describe the bug
The response contains the escape character `\` before some `/` and `"`.

## To Reproduce
1. Run the REST API plugin
2. Go to `http://localhost:8080/mvn/packages/junit:junit/4.12/modules`
3. In the response you will see the response character, for example `"metadata": "{\"final\": false, \"access\": \"public\", \"superClasses\": [\"\/junit.framework\/TestSuite\", \"\/java.lang\/Object\"], \"superInterfaces\": [\"\/junit.framework\/Test\"]}"`

## Expected behavior
There should not be any escape characters in the response. So `"metadata": "{\"final\": false, \"access\": \"public\", \"superClasses\": [\"\/junit.framework\/TestSuite\", \"\/java.lang\/Object\"], \"superInterfaces\": [\"\/junit.framework\/Test\"]}` should be `"metadata": "{"final": false, "access": "public", "superClasses": ["/junit.framework/TestSuite", "/java.lang/Object"], "superInterfaces": ["/junit.framework/Test"]}`.

**Comment by mayralgr** [comment]
I am working on this issue 😄

**Comment by MihhailSokolov** [comment]
@mayralgr I forgot to mention: when you start working on the issue, please branch out from `kbapi` branch and when you're done, create a PR back into `kbapi`. Thanks!

**Comment by mayralgr** [comment]
@MihhailSokolov thank you, I am already in the kbpi branch, I hope I finish today, I am goin to check the issue and if I have any further questions I get back to you. Thanks!

**Comment by romatallinn** [comment]
Hi @mayralgr, what is the status of this issue?

**Comment by mayralgr** [comment]
@romatallinn thanks for asking, I had had some troubles running the project, until I found the source I am leaving it open to contributions, I will get back to it if possible.

**Comment by MihhailSokolov** [comment]
Fixed in 02de5db

**Comment by romatallinn** [comment]
You removed the escapes, but they were there due to the quotes in the beginning and the end of the response. Now it is neither a valid string (no escapes, multiple quotes) nor a valid json (quotes stringify wrong parts).

`"{"final": true, "access": "packagePrivate", "superClasses": ["/java.awt.event/WindowAdapter"], "superInterfaces": []}"`
