### ISSUE TITLE
DatabaseMerger.mergeWithCHA() misses internal calls

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#156]
We consider here the graph with ID 1114828 (dsiutils version 2.2.2). Loading it from the graph database returns a graph with

- 2383 nodes of which 2383 internal
- 6061 arcs

Actually examining the nodes and checking manually finds 1974 internal nodes and 4190 internal calls. The stored number of internal nodes is wrong.

The graph returned by the mergeWithCHA() with the only graph as dependency has 592 nodes and 852 arcs, which is simply impossible because there are almost five times more internal calls.

[UPDATED: the previous figures where the result of a few dependencies being found. The new figures are exactly what one obtains invoking mergeWithCHA() using only ID 1114828.]

Examples of missed calls:

```
Internal call /it.unimi.dsi.parser/Element.%3Cinit%3E(%2Fjava.lang%2FCharSequence,%2Fjava.lang%2FBooleanType,%2Fjava.lang%2FBooleanType,%2Fjava.lang%2FBooleanType)%2Fjava.lang%2FVoidType -> /it.unimi.dsi.lang/MutableString.%3Cinit%3E(%2Fjava.lang%2FChar
Sequence)%2Fjava.lang%2FVoidType is missing from the stitched graph
Internal call /it.unimi.dsi.bits/TransformationStrategies$PrefixFreeTransformationStrategy$PrefixFreeBitVector.%3Cinit%3E(BitVector)%2Fjava.lang%2FVoidType -> /it.unimi.dsi.bits/TransformationStrategies$ISOTransformationStrategy$ISOCharSequenceBitVector.length()%2Fjava.lang%2FLongType is missing from the stitched graph
Internal call /it.unimi.dsi.lang/MutableString.endsWithIgnoreCase(%2Fjava.lang%2FString)%2Fjava.lang%2FBooleanType -> /it.unimi.dsi.lang/MutableString.length()%2Fjava.lang%2FIntegerType is missing from the stitched graph
Internal call /it.unimi.dsi.util/FrontCodedStringList.get(%2Fjava.lang%2FIntegerType)%2Fit.unimi.dsi.lang%2FMutableString -> /it.unimi.dsi.util/FrontCodedStringList.byte2Char(%2Fjava.lang%2FByteType%5B%5D,%2Fjava.lang%2FCharType%5B%5D)%2Fjava.lang%2FCharType%5B%5D is missing from the stitched graph
Internal call /it.unimi.dsi.big.util/StringMaps$SynchronizedStringMap.get(%2Fjava.lang%2FObject)%2Fjava.lang%2FLong -> /it.unimi.dsi.big.util/LongBigListSignedStringMap.get(%2Fjava.lang%2FObject)%2Fjava.lang%2FObject is missing from the stitched graph
Internal call /it.unimi.dsi.io/OfflineIterable.addAll(%2Fjava.lang%2FIterable)%2Fjava.lang%2FVoidType -> /it.unimi.dsi.bits/TransformationStrategies$IterableWrapper.iterator()%2Fjava.util%2FIterator is missing from the stitched graph
Internal call /it.unimi.dsi.lang/MutableString.indexOf(%2Fjava.lang%2FCharSequence,%2Fjava.lang%2FIntegerType)%2Fjava.lang%2FIntegerType -> /it.unimi.dsi.lang/MutableString$SubSequence.charAt(%2Fjava.lang%2FIntegerType)%2Fjava.lang%2FCharType is missing from the stitched graph
```

**Comment by ilyagrishkov** [comment]
Fixed in 11e6ab7. Now merged call graphs include resolved nodes and arcs, internal as well as unresolved external nodes and arcs from the original call graph.

**Comment by vigna** [comment]
The branch missing_internals contains a class that should be run on munich (as that's the only place where the graph database is available).

Please compile core and try 

java eu.fasten.core.maven.TestInternal it.unimi.dsi dsiutils 2.0.4

The class stores the arcs corresponding to internal calls, and after stitching performs a test to check that the arcs are still in place. Most of the internal calls are now there, but some are still missing.

**Comment by ashkboos** [comment]
I guess we fixed this problem in the past. The DatabaseMerger class does not exist anymore on develop. I will close this issue, please fill free to reopen it if you found similar problems in the current implementation.
