### ISSUE TITLE
A large number of graphs from Maven are missing from the revision call graph database

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#157]
The FASTEN graph database stored on munich should contain by now most of Maven's call graphs. However, a scan of the RocksDB key/value store shows as of now that just 737288 revision call graphs have been stored. This is reflected in most lookups of DatabaseMerger.mergeCHA() returning null, in turn making the resulting stitched graph to miss a large part of the intended arcs.

**Comment by MihhailSokolov** [comment]
We have created a copy of the graph database on the Athens server, reset the Kafka topic offsets, and deployed the graph plugin on Athens. So the missing graphs are already being put into the graph database on Athens. Hopefully, it will be complete in a few days and then this issue should be resolved.

**Comment by vigna** [comment]
Can you point me at the location of the database? It is needed to stitch graphs. Is the copy on munich still available or should I wait for the copy on athens being rebuilt?

**Comment by MihhailSokolov** [comment]
Sure, the path to the database is exactly the same as on Munich `/home/msokolov/graphdb`.
For now, both copies are available for usage. The only difference is that in a couple of days the copy on Athens will be more complete than the one on Munich.

**Comment by ashkboos** [comment]
POMAnalyzer's recent improvements should mitigate this problem. I will close the issue. Please feel free to reopen it if you found similar cases.
