### ISSUE TITLE
JavaCGOpal CLI does not generate module name in the same way in FILE and COORD modes when merging.

### ISSUE THREAD

**Issue by cg122** [fasten-project/fasten#161]
## Describe the bug
JavaCGOpal CLI does not generate module name in the same way in FILE and COORD modes when merging.

`-m FILE` will take filename of JAR as module name, `-m COORD` will take 'groupId:artifactId$version' as module name.

## To Reproduce

Run JavaCGOpal CLI for the same artifact and dependency in two modes (`-m FILE`  and `-m COORD`).

## Expected behavior
The result merged call graphs have same module name in the two modes.

**Comment by ashkboos** [comment]
#401
