### ISSUE TITLE
GraphMavenResolver hangs

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#163]
In the missing_internal branch, try, as always on munich (or athens, depending on where the graph database is being hosted)

java  eu.fasten.core.maven.TestInternal br.com.objectos.core io 0.3.2

After loading the graph, the call to GraphMavenResolver.resolveDependencies() in the class above never exits (more precisely, after two hours the call has yet to return).

**Comment by MihhailSokolov** [comment]
Resolved in b054f34318f9fe613c45c4b279d16fcbf2ce85a7
@vigna Could you please confirm?

**Comment by vigna** [comment]
If you ran the test and it does not hang, it's confirmed.
