### ISSUE TITLE
GraphMavenResolver throws IllegalStateException

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#164]
In the missing_internal branch, try, as always on munich (or athens, depending on where the graph database is being hosted)

java eu.fasten.core.maven.TestInternal br.com.objectos.core io 0.3.2

The call to GraphMavenResolver.resolveDependencies() throws the following exception:

Exception in thread "main" java.lang.IllegalArgumentException: no such vertex in graph: org.projectodd.stilts:stilts-stomp-client:0.1.2 (1970-01-01 00:59:59.999)
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
	at org.jgrapht.graph.AbstractBaseGraph.outgoingEdgesOf(AbstractBaseGraph.java:452)
	at eu.fasten.core.maven.GraphMavenResolver.dependencyBFS(GraphMavenResolver.java:236)
	at eu.fasten.core.maven.GraphMavenResolver.resolveDependencies(GraphMavenResolver.java:206)
	at eu.fasten.core.maven.TestInternal.main(TestInternal.java:65)

**Comment by MihhailSokolov** [comment]
This exception means that this revision is not present in the dependency graph (i.e. is not in the database). What do you think should be an expected behavior in this case?

**Comment by vigna** [comment]
It is difficult to make a choice here.

One possibility is to have a setter/getter for a property of GraphMavenResolver, say, `ignoreMissing`, that decides whether missing dependencies are simply ignored (which might work for a demo) or an exception should be thrown (which might be useful in testing). How does that sound?

In any case, if an exception is thrown it would be useful for the final user if it could contain some descriptive error, as in "Revision with Maven coordinates x is not present in the database".

**Comment by MihhailSokolov** [comment]
> It is difficult to make a choice here.
> 
> One possibility is to have a setter/getter for a property of GraphMavenResolver, say, `ignoreMissing`, that decides whether missing dependencies are simply ignored (which might work for a demo) or an exception should be thrown (which might be useful in testing). How does that sound?
> 
> In any case, if an exception is thrown it would be useful for the final user if it could contain some descriptive error, as in "Revision with Maven coordinates x is not present in the database".

Sounds good. I will add a getter and setter to ignore missing artifacts if possible and otherwise throw the exception with better description.

**Comment by MihhailSokolov** [comment]
@vigna this is now implemented in e6a4c2d
There are now `getIgnoreMissing()` and `setIgnoreMissing(...)` methods to get/set `ignoreMissing` field that is `false` by default.
If set to `true`, it will ignore missing revisions during dependency/dependent resolution and otherwise throw `RuntimeException(...)` with a more descriptive error message.
