### ISSUE TITLE
Reverting the map from GID to FASTEN URIs requires more than 30 minutes

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#170]
The metadata database, as per deliverable D2.8, is supposed to contain the bijection GID <-> Fasten URI and make it available in both directions. However, while GID queries like
```
fasten_java=> select fasten_uri from callables where id=4;
 /com.eclipsesource.json/JsonObject$1.next()JsonObject$Member
```
are solved instantly, URI queries like
```
fasten_java=> select id from callables where fasten_uri='/org.tuckey.web.filters.urlrewrite/NormalRewrittenUrl.isTemporaryRedirect()%2Fjava.lang%2FBooleanType';
```
don't return a result after 30 minutes. This might be just a problem of incorrect indexing, but it makes impossible to obtain GIDs for example, from locally stitched graphs, and prevents a number of subsequent data processing that are based on GIDs.

**Comment by MihhailSokolov** [comment]
I think we already mentioned it at some point, but currently, we don't have that many indexes because they would significantly slow down the insertion queries and right now we insert a lot. When the database is in the final state, then we'll add all additional indexes (including one on the `fasten_uri`)

**Comment by vigna** [comment]
When will it be finalized?

**Comment by MihhailSokolov** [comment]
I don't really know. I think the plan is that once we fix all the issues, we will clean the database, re-run the whole pipeline and then add indexes.

**Comment by gousiosg** [comment]
What we can do is:

```
CREATE UNIQUE INDEX CONCURRENTLY "idx_callables_fasten_uri"
ON "callables"
USING btree (digest("fasten_uri",  'sha1'::text));
```

but then queries that use the index should look like:

```
select id from callables where fasten_uri=digest('/org.tuckey.web.filters.urlrewrite/NormalRewrittenUrl.isTemporaryRedirect()%2Fjava.lang%2FBooleanType', ,  'sha1'::text));
```

@vigna would that work?

**Comment by gousiosg** [comment]
This query returns instantly after the index was created

```sql
select id from callables 
where digest(fasten_uri, 'sha1'::text) = digest('/org.tuckey.web.filters.urlrewrite/NormalRewrittenUrl.isTemporaryRedirect()%2Fjava.lang%2FBooleanType', 'sha1'::text);
```
