### ISSUE TITLE
JavaCGOpal is limited to analysing Java 8, support for newer Java version should be planned

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#173]
Java 8 is on indefinite support from Oracle, but more and more project will use newer version (eg. 11). This will progressively make the Java analysis of FASTEN more incomplete.  

Request:
A clear roadmap of including newer Java versions in the analysis, based on OPAL or some other suitable analysis framework.

**Comment by ashkboos** [comment]
This is a fair point, however, I'm afraid that this is currently a limitation that we can not do much about it:
> OPAL supports Java 10 Bytecode and has preliminary support for Java 11; OPAL in particular provides support to facilitate the analysis of Java 8-10 lambda expressions (Invokedynamic instructions)

What I experienced with OPAL is that the "preliminary" support for Java 11 causes very rare successful CG generation for Java 11. Therefore, it is not completely reliable yet to expect Java 11 support in FASTEN. We also tried WALA and it has the same issue. Considering the fact that we are using the latest developments of OPAL and it seems to be the only option that can scale to the extent that we want, I'm afraid that we can only wait until they improve OPAL.

**Comment by gousiosg** [comment]
Or add support for Java > 8 to OPAL ourselves

**Comment by gousiosg** [comment]
From the OPAL project front page:

> OPAL supports Java 10 Bytecode and has preliminary support for Java 11

**Comment by proksch** [comment]
I have updated OPAL to version 4. While I have not looked at the results for Java 11 yet, it would be possible to extend our new OPAL test suite with a java 11 project. Please open another issue should you encounter any issue or noteworthy observation when it comes to Java 11.
