### ISSUE TITLE
The metadata endpoint of the REST API produce invalid JSON content

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#174]
A good example to reproduce the bug is to look at the JSON produced when you go to http://api.fasten-project.eu/api/mvn/packages/org.eclipse.jetty:jetty-webapp/9.4.17.v20190418/metadata.

The problem seems to come from the fact that the metadata field value is not fully inlined: while the escaping was removed there is still `"` characters around it.

**Comment by MihhailSokolov** [comment]
Turns out the invalid formatting was an internal jOOQ issue. I've updated the jOOQ dependency to the latest version and fixed formatting in 36d6d85.
