### ISSUE TITLE
Endpoint for module callables retrieval stopped working

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#176]
POST `mvn/packages/junit:junit/3.7/modules/callables`
```
{
    "module_namespace": "/junit.awtui/AboutDialog"
}
```

I'm not entirely sure if this specific endpoint should return any callables (it's just an example), but the endpoint doesn't work in general. Returns status 200 with an empty array.

If I am not mistaken, the issue persists for the module's `metadata` and `files` endpoints as well. Although here I'd suggest additional triage.

**Comment by romatallinn** [comment]
@MihhailSokolov can you please have a quick look at method `getModuleCallables` in `eu/fasten/core/data/metadatadb/MetadataDao.java`. Does it look correct to you? Can't spot the problem.

P.S. The goal is to find all callables of the module.

**Comment by MihhailSokolov** [comment]
I think in the body request should be only the namespace itself, not JSON. Could you try the following request body and let me know if it works? 
```
/junit.awtui/AboutDialog
```

**Comment by romatallinn** [comment]
Yes, it works. Thanks.
