### ISSUE TITLE
Optimize database storage size

### ISSUE THREAD

**Issue by gousiosg** [fasten-project/fasten#180]
The Postgres database for Java is currently > 15TB on a (zlib) compressed filesystem (Python (75GB) and C (1.5GB) are still manageable). In addition to the server space being depleted very fast, this makes all operations (stitching, backups etc) very slow. 

The following queries reveal the biggest offenders:
```sql
> SELECT pg_size_pretty( pg_total_relation_size('edges') );
 pg_size_pretty 
----------------
 13 TB

> SELECT pg_size_pretty( pg_total_relation_size('callables') );
 pg_size_pretty 
----------------
 2537 GB
```

In `callables` there is lots of duplication in the JSON fields, which is easy to address, but we will not gain a lot by addressing it. With a back of the envelop calculation, I don’t think we will save more than 100GB (considerable, but not game changer). We have do it though.

```sql
> select metadata from callables where random() < 0.01 limit 1000;
{"access": "protected", "defined": true}
 {"access": "public", "defined": true}
 {"access": "public", "defined": true}
 {"access": "public", "defined": true}
 {"access": "private", "defined": true}
[...]
```

This leaves us with `edges`. We currently don’t store any JSON metadata there. We do store information about the call receiving locations, which we need for stitching. This in the following format:

```sql
CREATE TYPE RECEIVER AS (  
  line         INTEGER,
  type         RECEIVER_TYPE,
  receiver_uri TEXT
);
```

If we run the following query (counts all different receiver paths in a random set of 10M edges):

```sql
select receiver, count(*) 
from (
	select (unnest(receivers) :: RECEIVER).receiver_uri as receiver
	from edges 
	where random() < 0.5
	limit 10000000
) as receivers
group by receiver
order by count(*) desc;
```

We see a lot of duplication:

```
/java.util/Iterator	2578316
/scala/Function1	2460646
/java.lang/Object	1603142
/java.util/Map	493536
/scala/Function0	224663
/java.util/List	201691
/java.util/Set	140577
/java.util/Collection	113107
/java.util/Map$Entry	100314
/com.amazonaws.transform/Unmarshaller	55305
/java.util.function/Function	50181
/java.lang/StringBuilder	44883
/java.util.function/BiConsumer	42004
/java.io/ObjectInputStream	38568
/javax.faces.component/UIComponent	36272
[63k more rows]
```

This means that if we pull out the receiver information to a new lookup table, we will be saving _a lot_ of space. The cost will be an extra join when we have to stitch. In addition, (some of?) those strings are also replicated in the modules table. This makes sense: a receiver must be within a class we have analysed / we will analyse. 

In addition, AFAIU from reading online, Postgres does _not_ do the right thing when storing enums, so we are saving strings instead of small integers when storing the `receiver.type` field. Given that we store 25B edges, for an average 10 byte identifier, this wastes 238GB of space! 

Finally, while our `metadata` field in edges is empty, some space is allocated. I could not find how much. One easy win would be to move the metadata to a different table.

### Potential optimisations in order of importance

1. We can create a simple lookup table like so:

```sql
create table namespaces (
  id integer,
  namespace txt
)
```

We will then use the `id` field in namespaces as FK in both `edges` and `modules`. 

2. Alternatively, we could use the `id` field in `modules` as an FK in `edges`.

3. Use a function to automatically convert `receiver.type` stings to constants when inserting to `edges`

4. Create a table like the following:
```sql
create table edge_metadata (
  id integer,
  metadata jsonb
)
```

and always `outer join` this table with `edges` when retrieving metadata

**Comment by gousiosg** [comment]
@StefanosChaliasos @vitsalis How would the above affect the Python and C databases, respectively?

**Comment by vitsalis** [comment]
For Python, we do not store any receiver objects nor metadata so the above changes won't affect the functionality of the DB. The only change that would be required would be migrating the database which I suppose can be done in exactly the same way as with Java.

**Comment by gousiosg** [comment]
I am not sure we can migrate, as currently the remaining space on the server is << the space occupied by `edges`.

**Comment by StefanosChaliasos** [comment]
I think that for both C and Python, we won't have a problem. If we cannot do migrations, then we have to re-run the MetadataPlugin for all packages. This is very quick in C's case; for Python, it could up to a month.

**Comment by gousiosg** [comment]
@ashkboos @ilyagrishkov If we create an extra `namespaces` table, how will the performance of the merging algorithm be affected?

**Comment by dspinellis** [comment]
Regarding migration, I think there is a way to avoid rerunning all the processing by utilizing space we have on *lima*.  Here is a sketch.

1. Create a map from `receiver_uri` into `id` and store it in a file `receiver_uri_map`.

```SQL
SELECT  receiver_uri, row_number() over (order by receiver_uri ) AS id FROM
  (SELECT distinct receiver_uri FROM edges) AS receiver_names
ORDER BY receiver_uri;
```

2. Create a file containing our current `edges` table, ordered by `receiver_uri`.
3. Drop the `edges` table.
4. Create the `namespaces` table from `receiver_uri_map`
5. Run Unix *join* on `receiver_uri_map` and `edges` to create (on the fly) the data to populate the new `edges` table.

**Comment by gousiosg** [comment]
@dspinellis Unfortunately, `receiver_uri`s are stored as an array in each `edge` row, so the proposed query and joining with Unix tools to will not work.

Moreover, to sort 40B rows (x 2 receivers on average), Postgres will need several TBs of temp space, which we don't have.

**Comment by dspinellis** [comment]
Ouch! I was hoping they would be indexed and thus we would avoid the temporary, but this won't work with array elements. I should have caught this when we were designing the schema.  Sorry.

Could we provide Postgres with some network mounted space and move there the current `edges` table?  With its current structure there no benefit in having it on fast storage for the migration step.  How much time would we need to rerun the Java analysis?

**Comment by gousiosg** [comment]
We designed the `edges` table to keep the array of receivers as part of the edge row because the alternative would be worse. In a fully normalised schema, we would need to have the `namespaces` table and an intermediate table between `edges` and  `namespaces`. With out current dataset statistics (we have only stored ~1M Maven artifacts), we would need to store 40B edges x ~2 namespaces and join them on the fly when stitching the callgraphs. The index of this intermediate table would necessarily need to consist of a `src_id`, `target_id`, `namespace_id`, i.e. the whole table would also need to be part of the index. Just the index would consume around 1.8TB. So we opted for de-normalization, but unfortunately we also dropped the `namespaces` table (bad decision).

It is possible to give Postgres an NFS mount with ample space. Why though? Are you talking about creating the `namespaces` table and then updating `edges` to use it?

We do not need to re-run the full analysis, just the part that puts the callgraph data into Postgres. To do that, we need to modify the code that does the insertion and several queries that use edges for stitching.

**Comment by dspinellis** [comment]
The following script could normalize the `edges` table to use a `BIGINT` for `receiver_uri`. Currently works on a sample. Replace `edges_sample` with `edges` for the final run.  Note that in a sample I am getting a slightly different number of rows as a result. Either we have a bug in how we aggregate receivers (I thought over `source_id`, `target_id`, `metadata`), or I am misunderstanding something.

```SQL
-- New receiver type
CREATE TYPE nreceiver AS (
        line integer,
        type public.receiver_type,
        receiver_uri BIGINT
);

-- Sample table for testing
DROP TABLE IF EXISTS edges_sample;

CREATE TABLE edges_sample
  AS SELECT * from edges TABLESAMPLE SYSTEM(0.00001);

-- Namespaces table for normalizing receiver_uri strings
DROP TABLE IF EXISTS namespaces;

CREATE TABLE namespaces AS
  SELECT  receiver_uri AS name,
    row_number() over (ORDER BY receiver_uri ) AS id FROM
    (SELECT DISTINCT (unnest(receivers)).receiver_uri FROM edges_sample)
      AS receiver_names;

CREATE UNIQUE INDEX name_index ON namespaces(name);


-- New normalized edges table
DROP TABLE IF EXISTS nedges;

CREATE TABLE nedges AS
  -- Unnest the receivers into separate rows
  WITH unnested AS
  (SELECT source_id, target_id, metadata, unnest(receivers) AS r
    FROM edges_sample ),
  -- Disaggregate each receiver into its members
  expanded AS (
    SELECT source_id, target_id, metadata,
      (r).line, (r).type, (r).receiver_uri FROM unnested),
  -- Replace receiver_uri with its namespace integer
  normalized AS (
    SELECT source_id, target_id, metadata, line, type,
      (SELECT id from namespaces WHERE name = receiver_uri) AS receiver_uri
      FROM expanded),
  -- Re-compose receivers into aggregate type
  composited AS (
    SELECT source_id, target_id, metadata,
      ROW(line, type, receiver_uri)::nreceiver as receiver
      FROM normalized)
  -- Aggregate multiple receivers into an array
  SELECT source_id, target_id, metadata, array_agg(receiver) AS receivers
    FROM composited
    GROUP BY source_id, target_id, metadata;
```

**Comment by gousiosg** [comment]
Beautiful! The migration plan will be as follows:

- [ ] Create a ZFS snapshot of the Postgres partition on `monster`
- [ ] Copy the ZFS snapshot to `lima`, create ZFS snapshot there
- [ ] Run the migration script on `lima`
- [ ] Create a ZFS snapshot on `lima`, move REST API DB endpoint to `lima`
- [ ] Remove the Postgres volume on `monster`
- [ ] Copy the `lima` Postgres volume to `monster`
- [ ] Restart replication with `monster` as master
- [ ] Resume operations on `monster`

As we are taking for 15TB compressed data (likely 30TB uncompressed), just moving the data around will take time.

**Comment by gousiosg** [comment]
WRT not getting the same edges, the following query reveals where they come from:

```
select es.source_id, es.target_id 
	from edges_sample es left outer join nedges ne on es.source_id = ne.source_id and es.target_id = ne.target_id
where ne.source_id is null;
```

Those are edges having the same source and target ids. Upon further investigation, this is due to a minor issue in the OPAL CG generator. It is not a problem if they are deleted.

**Comment by dspinellis** [comment]
* I see that Postgres is taking a full CPU load.  Shouldn't database operation be stopped while running the process?
*  Note that I haven't addressed `callables`, but they seem to be orders of magnitude fewer.
* We also need to adjust the way records are added to the database and create a compatibility view.

**Comment by ilyagrishkov** [comment]
> @ashkboos @ilyagrishkov If we create an extra `namespaces` table, how will the performance of the merging algorithm be affected?

It will require additional joins, so merge might become slightly slower.

**Comment by gousiosg** [comment]
The script was running for ~1.5 hours for a sample of around 4M. After investigating, it looks like Postgres (or this particular expression) does not like a lot the `select` that is part of the field list when creating the `normalized` sub-table. After rewriting this as a join, it finished in 38 seconds!

```sql
CREATE TABLE nedges AS
  -- Unnest the receivers into separate rows
  WITH unnested AS
  (SELECT source_id, target_id, metadata, unnest(receivers) AS r
    FROM edges_sample ),
  -- Disaggregate each receiver into its members
  expanded AS (
    SELECT source_id, target_id, metadata,
      (r).line, (r).type, (r).receiver_uri FROM unnested),
  -- Replace receiver_uri with its namespace integer
  normalized AS (
    SELECT source_id, target_id, metadata, line, type, n.id AS receiver_uri
      FROM expanded e join namespaces n on n.name = e.receiver_uri),
  -- Re-compose receivers into aggregate type
  composited AS (
    SELECT source_id, target_id, metadata,
      ROW(line, type, receiver_uri)::nreceiver as receiver
      FROM normalized)
  -- Aggregate multiple receivers into an array
  SELECT source_id, target_id, metadata, array_agg(receiver) AS receivers
    FROM composited
    GROUP BY source_id, target_id, metadata;
```

**Comment by dspinellis** [comment]
I had a bad feeling about the inner `SELECT id from namespaces WHERE name = receiver_uri`, but couldn't think of a reason why a join would perform faster.  I reasoned that if the inner select had a cost of log N, the total cost would be N log N.  For the join to be fast, the `namespaces` table would need to be sorted, which is also an N log N operation.  I guess I didn't realize that `namespaces` was already sorted through its index, and thus Posgres could perform a fast *sort-merge join*.  BTW, in the past I've struggled with mySQL's lack of this capability.

**Comment by gousiosg** [comment]
It looks like we will not be getting a dramatic size reduction if we apply the transformation discussed above. For 4k random edges, the numbers look like the following:

```sql
select sum(size_before - size_after) as total_gain, sum(size_before) as total_before, sum(size_after) as total
  (select pg_column_size(n.receivers) as size_after, pg_column_size(e.receivers) as size_before
  from nedges n join edges e on e.source_id = n.source_id and e.target_id = n.target_id) as sizes;

 total_gain | total_before | total_after 
------------+--------------+-------------
     129353 |       462079 |      332726
```

We can expect a 30% smaller table.

We can gain a bit more if we make the `metadata` field nullable (saving 4 bytes per edge).

**Comment by dspinellis** [comment]
That's disappointing.  I wish my math would allow me to avoid asking this (maybe silly) question, but won't the savings increase as we process more edges?  I would expect the cost of storing `metadata` to be amortized over a larger number of records.

Regarding the cost savings of `null`, my understanding [from the documentation](https://www.postgresql.org/docs/current/storage-page-layout.html) is that for up to eight rows storing nulls doesn't have an additional cost, because they are stored in a single byte in position 23, which is otherwise wasted to satisfy alignment restrictions.

**Comment by gousiosg** [comment]
Since my math is at best as good as yours, I 've decided to check this:

| num_records | gain (%) |
| --- | --- |
| 4096 | 27,0 |
| 40960| 26,4 |
| 409600| 27,1 |
| 4096000| 26,7 |

Apparently, since we are doing random sampling, we should expect the sample to represent the population, so the gain should be the same across the whole table.

Unfortunately, it looks like we are paying a high fixed cost for storing the `[n]receiver` type. Each `nreceiver` record should have a _fixed_ size of `4 + 4 + 8 = 16` bytes. Each `receiver` record should be `4 + 4 + n` bytes long, where `n` is the length of the string we store. So our gain should be at least `n - 8` bytes per record. This can be confirmed if we run the following query:

```sql
select pg_column_size(n.receivers[1]) as nreceivers_size, pg_column_size(e.receivers[1]) as receivers_size from nedges n join edges e on e.source_id = n.source_id and e.target_id = n.target_id limit 10;
nreceivers_size | receivers_size 
-----------------+----------------
              40 |             48
              40 |             48
              40 |             52
              40 |             52
[...]
```

However, we see that each record is at least 40 bytes instead of 16! Where did the extra 24 bytes go? Any insights? Perhaps any ideas on how to make this more efficient?

**Comment by MihhailSokolov** [comment]
Here is the SQL to create a new (optimized) schema:
```sql
CREATE TABLE packages
(
    id           BIGSERIAL PRIMARY KEY,
    package_name TEXT NOT NULL,
    forge        TEXT NOT NULL,
    project_name TEXT,
    repository   TEXT,
    created_at   TIMESTAMP
);

CREATE TABLE package_versions
(
    id           BIGSERIAL PRIMARY KEY,
    package_id   BIGINT NOT NULL REFERENCES packages (id),
    version      TEXT   NOT NULL,
    cg_generator TEXT   NOT NULL,
    architecture TEXT,
    created_at   TIMESTAMP,
    metadata     JSONB
);

CREATE TABLE virtual_implementations
(
    virtual_package_version_id BIGINT NOT NULL REFERENCES package_versions (id),
    package_version_id         BIGINT NOT NULL REFERENCES package_versions (id)
);

CREATE TABLE dependencies
(
    package_version_id BIGINT NOT NULL REFERENCES package_versions (id),
    dependency_id      BIGINT NOT NULL REFERENCES packages (id),
    version_range      TEXT[] NOT NULL,
    architecture       TEXT[],
    dependency_type    TEXT[],
    alternative_group  BIGINT,
    metadata           JSONB
);

CREATE TABLE namespaces
(
    id        BIGSERIAL PRIMARY KEY,
    namespace TEXT NOT NULL
);

CREATE TABLE modules
(
    id                 BIGSERIAL PRIMARY KEY,
    package_version_id BIGINT NOT NULL REFERENCES package_versions (id),
    namespace_id       BIGINT NOT NULL REFERENCES namespaces (id),
    created_at         TIMESTAMP,
    metadata           JSONB
);

CREATE TABLE files
(
    id                 BIGSERIAL PRIMARY KEY,
    package_version_id BIGINT NOT NULL REFERENCES package_versions (id),
    path               TEXT   NOT NULL,
    checksum           BYTEA,
    created_at         TIMESTAMP,
    metadata           JSONB
);

CREATE TABLE module_contents
(
    module_id BIGINT NOT NULL REFERENCES modules (id),
    file_id   BIGINT NOT NULL REFERENCES files (id)
);

CREATE TABLE binary_modules
(
    id                 BIGSERIAL PRIMARY KEY,
    package_version_id BIGINT NOT NULL REFERENCES package_versions (id),
    name               TEXT   NOT NULL,
    created_at         TIMESTAMP,
    metadata           JSONB
);

CREATE TABLE binary_module_contents
(
    binary_module_id BIGINT NOT NULL REFERENCES binary_modules (id),
    file_id          BIGINT NOT NULL REFERENCES files (id)
);

CREATE TYPE CALLABLE_TYPE AS ENUM ('internalBinary', 'externalProduct', 'externalStaticFunction', 'externalUndefined', 'internalStaticFunction');
CREATE TYPE CALLABLE_ACCESS AS ENUM ('private', 'public', 'packagePrivate', 'static');

CREATE TABLE callables
(
    id               BIGSERIAL PRIMARY KEY,
    module_id        BIGINT  NOT NULL REFERENCES modules (id),
    fasten_uri       TEXT    NOT NULL,
    is_internal_call BOOLEAN NOT NULL,
    created_at       TIMESTAMP,
    line_start       INTEGER,
    line_end         INTEGER,
    type             CALLABLE_TYPE,
    defined          BOOLEAN,
    access           CALLABLE_ACCESS,
    metadata         JSONB
);

CREATE TYPE RECEIVER_TYPE AS ENUM ('static', 'dynamic', 'virtual', 'interface', 'special');

CREATE TYPE RECEIVER AS
(
    line          INTEGER,
    receiver_type RECEIVER_TYPE,
    namespace_id  BIGINT
);

CREATE TABLE edges
(
    source_id BIGINT NOT NULL REFERENCES callables (id),
    target_id BIGINT NOT NULL REFERENCES callables (id),
    receivers RECEIVER[],
    metadata  JSONB
);

-- CREATE INDEX CONCURRENTLY package_versions_package_id ON package_versions USING btree (package_id);
-- CREATE INDEX CONCURRENTLY dependencies_package_version_id ON dependencies USING btree (package_version_id);
-- CREATE INDEX CONCURRENTLY dependencies_dependency_id ON dependencies USING btree (dependency_id);
-- CREATE INDEX CONCURRENTLY files_package_version_id ON files USING btree (package_version_id);
-- CREATE INDEX CONCURRENTLY modules_package_version_id ON modules USING btree (package_version_id);
-- CREATE INDEX CONCURRENTLY module_contents_module_id ON module_contents USING btree (module_id);
-- CREATE INDEX CONCURRENTLY module_contents_file_id ON module_contents USING btree (file_id);
-- CREATE INDEX CONCURRENTLY binary_modules_package_version_id ON binary_modules USING btree (package_version_id);
-- CREATE INDEX CONCURRENTLY binary_module_contents_binary_module_id ON binary_module_contents USING btree (binary_module_id);
-- CREATE INDEX CONCURRENTLY binary_module_contents_file_id ON binary_module_contents USING btree (file_id);
-- CREATE INDEX CONCURRENTLY callables_module_id ON callables USING btree (module_id);
-- CREATE INDEX CONCURRENTLY edges_source_id ON edges USING btree (source_id);
-- CREATE INDEX CONCURRENTLY edges_target_id ON edges USING btree (target_id);

CREATE UNIQUE INDEX CONCURRENTLY unique_package_forge ON packages USING btree (package_name, forge);
ALTER TABLE packages
    ADD CONSTRAINT unique_package_forge UNIQUE USING INDEX unique_package_forge;

CREATE UNIQUE INDEX CONCURRENTLY unique_package_version_generator ON package_versions USING btree (package_id, version, cg_generator);
ALTER TABLE package_versions
    ADD CONSTRAINT unique_package_version_generator UNIQUE USING INDEX unique_package_version_generator;

CREATE UNIQUE INDEX CONCURRENTLY unique_virtual_implementation ON virtual_implementations USING btree (virtual_package_version_id, package_version_id);
ALTER TABLE virtual_implementations
    ADD CONSTRAINT unique_virtual_implementation UNIQUE USING INDEX unique_virtual_implementation;

CREATE UNIQUE INDEX CONCURRENTLY unique_version_dependency_range ON dependencies USING btree (package_version_id, dependency_id, version_range);
ALTER TABLE dependencies
    ADD CONSTRAINT unique_version_dependency_range UNIQUE USING INDEX unique_version_dependency_range;

CREATE UNIQUE INDEX CONCURRENTLY unique_version_namespace ON modules USING btree (package_version_id, namespace_id);
ALTER TABLE modules
    ADD CONSTRAINT unique_version_namespace UNIQUE USING INDEX unique_version_namespace;

CREATE UNIQUE INDEX CONCURRENTLY unique_module_file ON module_contents USING btree (module_id, file_id);
ALTER TABLE module_contents
    ADD CONSTRAINT unique_module_file UNIQUE USING INDEX unique_module_file;

CREATE UNIQUE INDEX CONCURRENTLY unique_version_name ON binary_modules USING btree (package_version_id, name);
ALTER TABLE binary_modules
    ADD CONSTRAINT unique_version_name UNIQUE USING INDEX unique_version_name;

CREATE UNIQUE INDEX CONCURRENTLY unique_binary_module_file ON binary_module_contents USING btree (binary_module_id, file_id);
ALTER TABLE binary_module_contents
    ADD CONSTRAINT unique_binary_module_file UNIQUE USING INDEX unique_binary_module_file;

CREATE UNIQUE INDEX CONCURRENTLY unique_version_path ON files USING btree (package_version_id, path);
ALTER TABLE files
    ADD CONSTRAINT unique_version_path UNIQUE USING INDEX unique_version_path;

CREATE UNIQUE INDEX CONCURRENTLY unique_uri_call ON callables USING btree (module_id, fasten_uri, is_internal_call);
ALTER TABLE callables
    ADD CONSTRAINT unique_uri_call UNIQUE USING INDEX unique_uri_call;

CREATE UNIQUE INDEX CONCURRENTLY unique_source_target ON edges USING btree (source_id, target_id);
ALTER TABLE edges
    ADD CONSTRAINT unique_source_target UNIQUE USING INDEX unique_source_target;

ALTER TABLE callables
    ADD CONSTRAINT check_module_id CHECK ((module_id = -1 AND is_internal_call IS false) OR
                                          (module_id IS NOT NULL AND is_internal_call IS true));

CREATE UNIQUE INDEX CONCURRENTLY unique_namepaces ON namespaces USING btree (namespace);
ALTER TABLE edges
    ADD CONSTRAINT unique_namepaces UNIQUE USING INDEX unique_namepaces;

INSERT INTO packages (id, package_name, forge)
VALUES (-1, 'external_callables_library', 'mvn')
ON CONFLICT DO NOTHING;

INSERT INTO package_versions (id, package_id, version, cg_generator)
VALUES (-1, -1, '0.0.1', 'OPAL')
ON CONFLICT DO NOTHING;

INSERT INTO namespaces (id, namespace)
VALUES (-1, 'global_external_callables')
ON CONFLICT DO NOTHING;

INSERT INTO modules (id, package_version_id, namespace_id)
VALUES (-1, -1, -1)
ON CONFLICT DO NOTHING;
```

**Comment by proksch** [comment]
It seems that the corresponding PR has been merged, so I am closing this for now. Please feel free to re-open, should the issue emerge again.
