### ISSUE TITLE
Performance issue when writing code metrics to the metadata DB

### ISSUE THREAD

**Issue by cg122** [fasten-project/fasten#181]
## Performance issue when writing to the metadata DB

Currently we have deployed the [Quality Analyser plugin](https://github.com/fasten-project/fasten/tree/develop/analyzer/quality-analyzer) at monster to store code quality metrics from Kafka to metadata DB. The progress is very slow considering code metrics of 778M callables to write. 

Our plugin relies heavily on query to find callables in the DB and then does the updating of metadata JSONB field (similar to what vulnerability plugin does). For the moment we can process 20-30K messages from Kafka topic per day. This makes it hardly helpful to prepare code quality metadata for all the callables have been analysed in time.

We would like to see if indexing of DB will significantly speed up the underlying query and the overall processing.

**Comment by MihhailSokolov** [comment]
This has already been solved here https://github.com/fasten-project/fasten/issues/170#issuecomment-745579355

**Comment by gousiosg** [comment]
```sql
select id from callables 
where digest(fasten_uri, 'sha1'::text) = digest('/org.tuckey.web.filters.urlrewrite/NormalRewrittenUrl.isTemporaryRedirect()%2Fjava.lang%2FBooleanType', 'sha1'::text);
```

**Comment by zikanl** [comment]
I am afraid this is related to our case. We first have the performance issue with table module_contents that is not indexed. It takes usually around 4-5 minutes to execute a (simple) command to find corresponding module_ids for given file_id. Once that is resolved, we could move to writing to the database, and issue #181

**Comment by gousiosg** [comment]
Those slow join queries typically indicate a missing index. We have disabled indices on join conditions for insertion performance reasons. You can see which indices have been disabled here: https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema#sql-to-create-database-tables

The `module_contents_file_id` index is currently being created; your query should be instant when it is done.

**Comment by gousiosg** [comment]
BTW, the original question was about `callables`, not `module_contents`

**Comment by zikanl** [comment]
> Those slow join queries typically indicate a missing index. We have disabled indices on join conditions for insertion performance reasons. You can see which indices have been disabled here: https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema#sql-to-create-database-tables
> 
> The `module_contents_file_id` index is currently being created; your query should be instant when it is done.

Thanks for the info - my question then is when could we expect this table to be indexed, i.e. this "indexing" process to complete? A precision of a week would be a good estimate. TIA

**Comment by zikanl** [comment]
> BTW, the original question was about `callables`, not `module_contents`

The question is related to the performance when writing to the database. This consists of a number of steps and all of them contribute to the overall performance. I pointed out to one, and hopefully there are no other performance-related issues among other steps (to be checked).

**Comment by zikanl** [comment]
Resolved with table indexing.
