### ISSUE TITLE
Duplicate arcs in some call graphs in the FASTEN KB, causing issues when running (local) merger

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#195]
## Describe the bug
Some callgraphs obtained from the API contain duplicate arcs. This crashes the (local) merger. One example is the call graph for ch.qos.logback:logback-classic:1.2.3, which is attached [here](https://github.com/fasten-project/fasten/files/5816201/ch.qos.logback_logback-classic_1.2.3.json.zip).

The offending arc 943 can be seen in the JSON file at lines 17977-17978 and again at lines 28761-28762.

## To Reproduce

```
    @Test
    void duplicateArcsTest() throws IOException {
        var rcg = new ExtendedRevisionJavaCallGraph(new JSONObject(
                Files.readString(Path.of(
                        "src","test", "resources",
                        "ch.qos.logback_logback-classic_1.2.3.json"))));
        var depSet = new ArrayList<ExtendedRevisionJavaCallGraph>();
        depSet.add(rcg);
        var merger = new LocalMerger(depSet);

        assertThrows(java.lang.IllegalArgumentException.class, () -> {
            merger.mergeAllDeps();
        });
    }
```

## Expected behavior
No exception, a merged call graph.

## Logs
An excerpt from the exception trace:
```
java.lang.IllegalArgumentException: Duplicate arc 943 -> 943
	at
eu.fasten.core.data.ArrayImmutableDirectedGraph$Builder.addArc(ArrayImmutableDirectedGraph.java:78)
	at
eu.fasten.core.data.ExtendedRevisionJavaCallGraph.toLocalDirectedGraph(ExtendedRevisionJavaCallGraph.java:337)
	at eu.fasten.core.merge.LocalMerger.mergeAllDeps(LocalMerger.java:157)
......
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Java version: 11
 - develop branch [#63e5d74](https://github.com/fasten-project/fasten/commit/63e5d747d9b2837c050aab09b316f3e23fb1a500)

**Comment by ashkboos** [comment]
@MagielBruntink Do you confirm that the issue is fixed?

**Comment by MagielBruntink** [comment]
@ashkboos Yes, this issue seems resolved. Thanks!
