### ISSUE TITLE
Improve MavenResolver

### ISSUE THREAD

**Issue by MihhailSokolov** [fasten-project/fasten#200]
## Describe the bug
Currently, the MavenResolver can successfully resolve the dependencies in about 50% of the cases. There seems to be an improvement using this regex: `mvn dependency:tree -DoutputType=tgf | grep -Po "[0-9]+ (([A-Za-z0-9.\-_])*:){1,6}"` instead of the one currently used.

**Comment by MagielBruntink** [comment]
Hi Mihhail,

Please have a look at our solution for this, maybe it helps:
https://github.com/fasten-project/rapid-integration-tools/blob/develop/src/main/java/eu/fasten/rapid/MavenResolver.java

**Comment by MihhailSokolov** [comment]
> Hi Mihhail,
> 
> Please have a look at our solution for this, maybe it helps:
> https://github.com/fasten-project/rapid-integration-tools/blob/develop/src/main/java/eu/fasten/rapid/MavenResolver.java

Thank you, Magiel. This looks quite useful!
