### ISSUE TITLE
Kbapi: latest package version not found

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#205]
## Describe the bug
Response to the general request for the package (`mvn/packages/packageName`) is supposed to include the latest version. Some requests, however, return error `Latest package version not found`.

## To Reproduce

GET Request: `https://api.fasten-project.eu/api/mvn/packages/org.apache.spark:spark-core`

## Expected behavior
API shall return at least some version. If no version, then package with version `null` (?)

**Comment by MihhailSokolov** [comment]
There is also a problem with ordering. It uses `ORDER BY package_versions.created_at` clause when retrieving data from the database to get the latest version. However, apparently it cannot handle the `null` versions properly. For example, when sending request to get the latest version of `junit:junit`, it would respond with `3.7` even though the latest version in the database was actually `4.13`. v3.7 had null `created_at` and was apparently when ordering nulls appear first.
I think that either the query should be updated to add `WHERE package_versions.created_at IS NOT NULL` or all versions should be retrieved and properly sorted manually before sending the response.
It would be great if this could also be fixed.

**Comment by romatallinn** [comment]
Closed by #206
