### ISSUE TITLE
Switch to slimmer openjdk base Docker image to reduce size

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#212]
## Is your feature request related to a problem? Please describe.
The FASTEN Server image is quite large (1.17 GB @latest) which slows down local development and CI actions.

## Describe the solution you'd like
Switch to a slimmer version of openjdk:11, for instance openjdk:11-slim or openjdk:11-alpine

**Comment by mir-am** [comment]
I'll investigate this issue. Aside from the OpenJDK size, some plugins might have dependencies that can be excluded safely before building their JAR files.

**Comment by MagielBruntink** [comment]
Just did some test builds to see size differences:
```
REPOSITORY                                                                 TAG          IMAGE ID       CREATED          SIZE
fasten.server.develop.amazoncoretto-11-alpine.size-test                    latest       44d86a396103   57 seconds ago   862MB
fasten.server.develop.openjdk11-slim.size-test                             latest       6c17ccdd534c   2 minutes ago    960MB
fasten.server.develop.openjdk11.size-test                                  latest       5fffa86fac03   4 minutes ago    1.19GB
```
Note: the alpine images cause a problem with the graph DB due to differences in the included libc.

Including all the plugin jars is the biggest contributor to the size; we should consider splitting up and releasing a separate image for each plugin.

**Comment by mir-am** [comment]
> I'll investigate this issue. Aside from the OpenJDK size, some plugins might have dependencies that can be excluded safely before building their JAR files.

Thanks for the tests.
I am working on this in #228. Based on the initial test, the overall size of the image with `openjdk:11-jre-slim-buster` is around 712MB. The OPAL seems to work fine. However, other plugins should be tested.

Also, I've decreased the size of OPAL plugin's JAR to less than 100MB. Plugins mostly inherit dependencies from the `core` module that they may not need.
