### ISSUE TITLE
Missing callables for org.apache.commons:commons-lang3 3.9 on api.fasten-project.eu

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#216]
I can see that Apache Commons Lang3 exist on the FASTEN Central metadata database (see https://api.fasten-project.eu/api/mvn/packages/org.apache.commons:commons-lang3/3.9/metadata) but the metadata database does not seem to contain any of its callables (https://api.fasten-project.eu/api/mvn/packages/org.apache.commons:commons-lang3/3.9/callables).

Callables can be seen on https://api.fasten-project.eu/mvn/c/commons-lang3/commons-lang3_org.apache.commons_3.9.json, so it does not seem to be an OPAL related problem, looks more like a storage problem (or a REST API not doing the right select maybe).

**Comment by MihhailSokolov** [comment]
@tmortagne looks like the metadata plugin wasn't able to process the record from OPAL containing this CG, because the database does not contain any callables of `org.apache.commons:commons-lang3:3.9`
```sql
fasten_java=> select c.id from callables c join modules m on c.module_id=m.id join package_versions pv on m.package_version_id=pv.id join packages p on pv.package_id=p.id where p.package_name='org.apache.commons:commons-lang3' and pv.version='3.9';
 id 
----
(0 rows)
```
It might be related to the issue that @MagielBruntink and @wzorgdrager were discussing regarding the record size and Kafka not being able to handle records that are too large.

**Comment by tmortagne** [comment]
If Commons Lang CG is too big I'm afraid we are going to miss quite a lot of other artifacts.

**Comment by tmortagne** [comment]
I can reproduce the same problem with https://api.fasten-project.eu/api/mvn/packages/org.incava:java-diff/1.1/callables and https://api.fasten-project.eu/api/mvn/packages/xmlpull:xmlpull/1.1.3.1/callables both very small.

**Comment by mir-am** [comment]
We will run the FASTEN's DC with the said coordinate to see whether callables can be retrieved considering the newest improvements to the FASTEN pipeline.

**Comment by mir-am** [comment]
> We will run the FASTEN's DC with the said coordinate to see whether callables can be retrieved considering the newest improvements to the FASTEN pipeline.

We ran the FASTEN Docker compose with the said coordinate ` org.apache.commons:commons-lang3:3.9` and it does generate callables. So I close the issue.
