### ISSUE TITLE
/metadata/callables return an error 500 when trying to get metadata for a not existing callable

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#220]
## To Reproduce

Endpoint: `https://api.fasten-project.eu/api/metadata/callables`
METHOD: `POST`
Content-Type: `application/json`
Content: `["fasten://mvn!org.incava:java-diff$1.1/org.incava.util.diff/Difference.%3Cinit%3E(%2Fjava.lang%2FIntegerType,%2Fjava.lang%2FIntegerType,%2Fjava.lang%2FIntegerType,%2Fjava.lang%2FIntegerType)%2Fjava.lang%2FVoidType"]`

Respond with an error 500 without any specific message.

Note that https://api.fasten-project.eu/api/mvn/packages/org.incava:java-diff/1.1/callables returns an empty list. But it's different from #216 in which we get a 404.

**Comment by MihhailSokolov** [comment]
Fixed in 3c407b2af6189db4a530c13c25f3e344fa67dc10
Now the missing URIs are skipped.
