### ISSUE TITLE
How to pass argument to plugins when launched from server JAR

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#221]
I used to run my plugin as a standalone, like this:

```shel
mvn \
    # Maven property
    -DclusterCredentials=path/to/cluster/credentials.json \
    clean install exec:java \
    -f analyzer/compliance-analyzer/pom.xml \
    # Plugin's CLI argument
    -Dexec.args=“--namespace mykubernetesnamespace”
```

As you can see, I was using the `clusterCredentials` Maven property and a `--namespace` CLI argument for the [license plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/compliance-analyzer).

---

Now I have to run it from the server:

```bash
java \
    -jar docker/server/server-0.0.1-SNAPSHOT-with-dependencies.jar \
    […other flags...] \
    --plugin_list CompliancePluginExtension
```

and I don’t know how to pass these two parameters to my plugin: how I can do this?

**Comment by mir-am** [comment]
> I used to run my plugin as a standalone, like this:
> 
> ```
> mvn \
>     # Maven property
>     -DclusterCredentials=path/to/cluster/credentials.json \
>     clean install exec:java \
>     -f analyzer/compliance-analyzer/pom.xml \
>     # Plugin's CLI argument
>     -Dexec.args=“--namespace mykubernetesnamespace”
> ```
> 
> As you can see, I was using the `clusterCredentials` Maven property and a `--namespace` CLI argument for the [license plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/compliance-analyzer).
> 
> Now I have to run it from the server:
> 
> ```shell
> java \
>     -jar docker/server/server-0.0.1-SNAPSHOT-with-dependencies.jar \
>     […other flags...] \
>     --plugin_list CompliancePluginExtension
> ```
> 
> and I don’t know how to pass these two parameters to my plugin: how I can do this?

The FASTEN server doesn't accept arbitrary CLI inputs. Therefore, we need to add a new CLI argument for passing `clusterCredentials` to the license plugin. 
Regarding the issue #222, I don't know what's the plan for the deployment of the license plugin. When a deployment plan is devised, we'll see if a new CLI argument should be added to the FASTEN server.

**Comment by marcomicera** [comment]
Not needed anymore. Closing...
