### ISSUE TITLE
Synchronous license plugin's Kubernetes deployment

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#222]
The [license and compliance plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/compliance-analyzer) deploys Kubernetes resources to detect licenses. The [open source project](https://github.com/qmstr/qmstr) being used by this plugin is managed by the Linux Foundation, and major architecture decisions lie with it.

In short, it consumes a repository URL from [`fasten.RepoCloner.out`](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenrepocloner) and produces a [`fasten.qmstr.out` record](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenqmstr) containing licenses at the file level.

At the moment, the [`consume()` method](https://github.com/fasten-project/fasten/blob/83579c612eef7429af59d95fa1631df7556dfb90/analyzer/compliance-analyzer/src/main/java/eu/fasten/analyzer/complianceanalyzer/ComplianceAnalyzerPlugin.java#L89-L127):
1. Deploys Kubernetes resources on a cluster
1. Terminates immediately.

As discussed with @wzorgdrager, this immediate termination would cause the deployment of `n` other Kubernetes Jobs, being `n` the number of [`fasten.RepoCloner.out`](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenrepocloner) records in Kafka.
Therefore, its [`consume()` method](https://github.com/fasten-project/fasten/blob/83579c612eef7429af59d95fa1631df7556dfb90/analyzer/compliance-analyzer/src/main/java/eu/fasten/analyzer/complianceanalyzer/ComplianceAnalyzerPlugin.java#L89-L127) needs to be blocking, i.e., it needs to wait for the license detection to be over before terminating.

### Cleanup

The license and compliance plugin also needs to delete all the Kubernetes resources deployed during its execution.

**Comment by wzorgdrager** [comment]
I was thinking about this again; isn't there a way to run `quartermaster` as a library in your plugin? This would make everything much easier as I'm expecting you need to cover _a lot_ of corner cases to deal with deploying pods on the fly. Some of these cases include: 1) your compliance plugin being in a crash loop, it will launch pods and not clean them up and 2) your compliance plugin needs to re-deploy (for whatever reason), all currently running pods won't be terminated.

**Comment by wzorgdrager** [comment]
Or if it's hard to implement in the code, maybe run it _within_ the same pod/container as the license/compliance plugin?

**Comment by marcomicera** [comment]
> isn't there a way to run `quartermaster` as a library in your plugin?

I thought about it a lot and my conclusion is that: no, it cannot run as a library by nature.

> Or if it's hard to implement in the code, maybe run it _within_ the same pod/container as the license/compliance plugin?

This is a great idea. I would have to drop the plugin's JAR file, though. Can I? @wzorgdrager

**Comment by wzorgdrager** [comment]
> This is a great idea. I would have to drop the plugin's JAR file, though. Can I? @wzorgdrager 

What do you mean with that? We can just add the quartermaster jar file/executable in the Docker container so that you can access this from the same container as the plugin. We might need a slightly different Docker image than we built in this repo, but that should be relatively easy to setup.

**Comment by marcomicera** [comment]
> We can just add the quartermaster jar file/executable in the Docker container so that you can access this from the same container as the plugin.

I think I got it: we can still containerize the plugin's JAR file, but it should deploy local Docker containers instead of Kubernetes resources, right? Otherwise, the (on-the-fly) Pods management problem would still persist...

**Comment by wzorgdrager** [comment]
> I think I got it: we can still containerize the plugin's JAR file, but it should deploy local Docker containers instead of Kubernetes resources, right? Otherwise, the (on-the-fly) Pods management problem would still persist...

No, what I mean is that currently, the flow is roughly like this:
```
1. Plugin reads a message from Kafka
2. Plugin launches pod to process this message
3. Go back to step 1.
```
I propose to change it like this:
```
1. Plugin reads a message from Kafka
2. Plugin executes the quartermaster.jar from the code and wait until it finishes.
3. Go back to step 1.
```
So step 2 is executed _within_ the same Docker container as where the plugin runs. No external containers or pods are launched. 

Technically you could execute step 2 using something like:
```java
Process process = Runtime.getRuntime().exec("java -jar quartermaster.jar [arguments]");
```
and then wait for it to finish. However, there probably exists nicer ways to implement this. The point is that we want to process the message in the same container as where we read it.

**Comment by marcomicera** [comment]
> I propose to change it like this:
> 
> ```
> 1. Plugin reads a message from Kafka
> 2. Plugin executes the quartermaster.jar from the code and wait until it finishes.
> 3. Go back to step 1.
> ```

Sadly, there's no `quartermaster.jar`.
Quartermaster is a distributed app that runs natively on k8s, so it consists of multiple Kubernetes resources (simplified version [here](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/compliance-analyzer/src/main/resources/k8s)).

So if I containerize the plugin's (PF4J) JAR, it would still have to manage the k8s Pods that it deploys on the fly.

---

I think we can solve all this by:
- Stop using the license and compliance plugin's JAR file
- Adding a k8s Deployment for Quartermaster [here](https://github.com/fasten-project/k8s-deployments/tree/master/fasten), so that the license and compliance plugin can only be triggered by `kubectl`

How does this sound?

**Comment by wzorgdrager** [comment]
How do you consume from Kafka then? How do you ensure that Quartermaster keeps on processing new releases/artifacts? 

I'm not sure how Quartermaster works, but it needs an executable right (even if you run it inside a separate K8s pod). Why not execute this executable directly in the plugin container. I.e. substitute  `quartermaster.jar` with whatever command quartermaster uses to run.

**Comment by wzorgdrager** [comment]
If there are parts of quartermaster that need to run permanently we can just add those a separate deployment. We just want to avoid launching new pods or containers for _each_ Kafka message.

**Comment by marcomicera** [comment]
> How do you consume from Kafka then? How do you ensure that Quartermaster keeps on processing new releases/artifacts?

Oops, you're right, my bad. We definitely need the plugin's (PF4J) JAR file.

> If there are parts of quartermaster that need to run permanently we can just run those as a separate deployment in K8s (i.e. a master process).

No, at the moment there are no stateful components in Quartermaster.

> I'm not sure how Quartermaster works, but it needs an executable right (even if you run it inside a separate K8s pod). Why not execute this executable directly in the plugin container. I.e. substitute `quartermaster.jar` with whatever command quartermaster uses to run.

Sadly there's no single executable. [Here](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/compliance-analyzer/src/main/resources/k8s) you can see why: it's a modular application that needs at least a RabbitMQ and a DGraph instance to work, and even the [stripped-down Quartermaster Job](https://github.com/fasten-project/fasten/blob/endocode/compliancePlugin/analyzer/compliance-analyzer/src/main/resources/k8s/qmstr/job.yaml) is composed of several containers.


I'm still thinking about how to avoid managing these Pods that are deployed on the fly from Java...

**Comment by wzorgdrager** [comment]
Does it need this setup _per_ Kafka message it consumes? (i.e. a rabbitmq, dgraph and other containers per Kafka message?)

**Comment by marcomicera** [comment]
Unfortunately, yes. Quartermaster will treat them as stateful components in the future.

**Comment by proksch** [comment]
Ok, maybe we should take a step back here... we have an infrastructure that allows heavily-parallel processing in a data pipeline architecture. The idea that has been communicated from the get-go is that we have analyzers on different levels that integrate into this infrastructure. These analyzers consume information from the outside, perform local computation, and persist results in the knowledge base. By putting this under the umbrella of k8s, the whole pipeline is maintainable and k8s can easily react to crashes or changes in load.

The proposed solution that has been discussed in this issue obviously does not fit the current architecture. Offloading computation to the outside is not an option (it completely breaks the control flow and also makes us dependent on external services), and the proposed changes for internal computation (spawning multiple containers on the fly for every single message) do not only scale terribly, they are also hard to implement, debug, and maintain. All kinds of corner cases need to be handled that would be otherwise covered by k8s already. In simple words, the proposed solution is not acceptable from the project perspective.

It makes more sense to me to turn around the question. How do you plan to change the quartermaster deployment to fit into the current architecture? How do you want to integrate your tools with FASTEN?

If the answer is that you prefer to host your own license database somewhere, isolated from FASTEN, this is fine with me as well. In this case, we would reduce the FASTEN integration to an analyzer that requests the corresponding licensing info from your external DB and makes sure to map the results back into the KB... you just need to make sure that the data is available when requested.

**Comment by gousiosg** [comment]
On a practical side, what you should do @marcomicera would be to modify the Quartermaster build process to: 1. use an externally accessible Kafka instance instead of RabbitMQ, 2. use an externally accessible dgraph instance. Then, you should provide us with a kubernetes manifest(s) that deploys dgraph and your building process. This is the bare minimum to have Quartermaster deployed on our cluster.

**Comment by marcomicera** [comment]
As @proksch, @wzorgdrager and I discussed on Friday, I'll be trying to wrap everything in one single Pod (for cleanup purposes) that runs to completion (unfortunately that's how the project behind this plugin works). Assigning a [static membership](https://kafka.apache.org/27/documentation/#static_membership) to such a consumer group shouldn't trigger rebalance.

Closing: will reopen if this solution won't work for whatever reason...
