### ISSUE TITLE
Come up with license compatibility rules

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#223]
D4.4 expects the [license and compliance plugin](https://github.com/fasten-project/fasten/tree/endocode/compliancePlugin/analyzer/compliance-analyzer) to express compatibility issues when using multiple licenses.
We expect we will need a matrix that pairs licenses and contains compatibility metrics, e.g., an "incompatibility index", a severity level, etc.

The license compatibility matrix would look something like this:

|  | Apache 2 | MIT | GPL 3 | ... |
| -- | -- | -- | -- | -- |
| Apache 2 | &ndash; |   |  |  |
| MIT |   | &ndash; |  |  |
| GPL3 |   |   | &ndash; |  |
| ... |   |   |  |  |

Such a matrix might not be enough to describe more complex compatibility issues among multiple licenses, e.g., a set of licenses excluding another set.
We might need a "license compatibility graph" that stores the "direction" of [in]compatibilities.

If that ends up to be true, the result itself could consist of such a graph, depicting compatibility issues in a graphical form.

**Comment by michelescarlato** [comment]
Actually, we are writing a prototype that uses a compatibility matrix.

After using an array to store all the licenses used within a project, an algorithm scans its elements, comparing them and matching the value contained inside of the matrix.
The comparison is made for each element against the other elements.

The result is a list containing boolean values.
The algorithm reports each incompatibility.

**Comment by michelescarlato** [comment]
The repo [LCV-CM](https://github.com/endocode/LCV-CM) contains the Python logic of the License Compliance Verifier (LCV) and the Compatibility Matrix (CM), which is partially fulfilled.

Apart from being run from the command line, LCV can be run as a containerized service that provides REST APIs.
@wzorgdrager @MagielBruntink, it would be great if the Fasten architecture could run the LCVServer container.

This would allow me to write the PF4J plugin calling LCV API methods providing a compliance assessment.

The following diagram shows the main logic of this approach.
![Interaction diagram](https://github.com/endocode/LCV-CM/blob/main/LCV-Kafka.png)

**Comment by marcomicera** [comment]
> The following diagram shows the main logic of this approach.

Just a small remark (architecture-side) - maybe this is what you meant?

![LCV-Kafka](https://user-images.githubusercontent.com/13918587/112947791-8b3a1380-9137-11eb-96a8-2f9a2ad14543.png)

> @wzorgdrager @MagielBruntink, it would be great if the Fasten architecture could run the `LCVServer` container.

We need to do that: if you want to keep the license compliance logic into a separate container, that we'll need to wrap everything into one Pod (for cleanup purposes) and to assign a [static membership](https://kafka.apache.org/27/documentation/#static_membership) to that consumer group in order to avoid rebalancing ([as we decided for the license detector plugin](https://github.com/fasten-project/fasten/issues/222#issuecomment-809976731)).

**Comment by michelescarlato** [comment]
@marcomicera, what I wanted to mean, is expressed in my diagram.

If the `LCVServer` container cannot stay always-alive, I have to think differently about the whole architecture.

But if you already have a clear idea of running in one Pod the java plugin, together with the `LCVServer`, I am open to understanding it.

I wanted to avoid the kill the container for each execution, and eventually, I would test how many assessments can support before requiring to be destroyed and re-run. The amount of computation it has to do is relatively simple.

**Comment by marcomicera** [comment]
> I wanted to avoid the kill the container for each execution, and eventually, I would test how many assessments can support before requiring to be destroyed and re-run. The amount of computation it has to do is relatively simple.

Oops, you're right, I got mixed up: you can completely ignore my previous lines about static membership. I'll cross 'em out just in case!

As far as Kubernetes objects are concerned, I think my notes on that diagram are still correct, aren't they?

**Comment by michelescarlato** [comment]
My idea was to run the LCVContainer outside of the JAR plugin. 
Completely detached.
Probably is a wrong idea.

**Comment by marcomicera** [comment]
> My idea was to run the LCVContainer outside of the JAR plugin.
> Completely detached.

AFAIK the blue container should have:
- the Fasten server JAR that - as soon as it receives a [`fasten.qmstr.out` record](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenqmstr) will trigger the...
- ...LCV JAR, that is in charge of:
    1. contacting the Fasten REST API to retrieve licenses,
    2. trigger the license compliance verifier (the green container) through its internal API,
    3. store results into the Knowledge Base, directly or indirectly.

**Comment by michelescarlato** [comment]
Nope.
As my diagram shows since the beginning, the blue container will do both calls, the Fasten API, and then call the LCV API.
It is also in charge of the store the results into the KB.

The LCV is not a Jar; it should be used as a server run as a container.

**Comment by marcomicera** [comment]
> As my diagram shows since the beginning, the blue container will do both calls, the Fasten API, and then call the LCV API.
> It is also in charge of the store the results into the KB.
> 
> The LCV is not a Jar; it should be used as a server run as a container.

It's my understanding that - in this case - the LCV is not a unique entity. I'll try to explain why down below.

The blue container has two JARs: the first one is the [Fasten server](https://github.com/fasten-project/fasten/blob/e89d52b4881a010da4f38f4033fa1a94e31937e0/server/pom.xml#L29-L71), which essentially (I might oversimplify) triggers the execution of other JARs upon receiving some Kafka records.
Here's an [example](https://github.com/fasten-project/k8s-deployments/blob/511e8cc21d73eecd3fb5d404c6178977d78eb89c/fasten/opal/opal.yaml#L20) of how to bound a Kafka topic to a JAR consumer ([arguments description](https://github.com/fasten-project/fasten/tree/develop/server#arguments):

```yaml
args: [
  ...
  "-pl", "OPAL",
  "-kt", "OPAL=fasten.POMAnalyzer.out",
  ...
]
```

`-pl` tells the Fasten server what's the plugin JAR to be triggered upon the reception of a Kafka record belonging to the topic specified by `-kt`.
So in this case, upon receiving a record belonging to the `fasten.POMAnalyzer.out` topic, the `OPAL` plugin will be started.
**It is my understanding that the Fasten server can only start other JAR files**: plugins need to implement [this interface](https://github.com/fasten-project/fasten/blob/develop/core/src/main/java/eu/fasten/core/plugins/KafkaPlugin.java) so that the Fasten server can control their lifecycle.
So the second JAR of the blue container should contain the implementation of that interface. Its [`consume` method](https://github.com/fasten-project/fasten/blob/e89d52b4881a010da4f38f4033fa1a94e31937e0/core/src/main/java/eu/fasten/core/plugins/KafkaPlugin.java#L42-L48) should then do the following:

>   1. contacting the Fasten REST API to retrieve licenses,
>   2. trigger the license compliance verifier (the green container) through its internal API,
>   3. store results into the Knowledge Base, directly or indirectly.

That's at least what I learned by looking at other plugins.
I think the Fasten server can only trigger other JAR files, because the `-pl` flag only accepts names of those Java classes that implement the `KafkaPlugin` interface (e.g., `OPAL` [here](https://github.com/fasten-project/fasten/blob/e89d52b4881a010da4f38f4033fa1a94e31937e0/analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/OPALPlugin.java#L50)).

**Comment by proksch** [comment]
Is this issue still relevant?

**Comment by michelescarlato** [comment]
Nope.
Meanwhile we integrate LCV as an external service.

We can close this issue.
