### ISSUE TITLE
Make iteration over results of GraphMavenResult consistent

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#230]
Presently, GraphMavenResolver performs breadth-first visits, but results are stored in a HashSet, resulting in the following issues:

- it is impossible to iterate over the result in order of distance;
- the iteration order is unpredictable.

These problems can be easily fixed by replacing the current java.util.HashSet holding the results with a java.util.LinkedHashSet, or, even better, with a it.unimi.dsi.fastutil.objects.ObjectLinkedOpenHashSet, which uses less memory and generate less stress on the garbage collector.

**Comment by MihhailSokolov** [comment]
Now GraphMavenResolver uses and returns `ObjectLinkedOpenHashSet` as you suggested. Implemented in cc1c97b

**Comment by vigna** [comment]
Great, thanks!
