### ISSUE TITLE
[VULN] Check files extension + Validate PURLs published +  Drill-down

### ISSUE THREAD

**Issue by elanzini** [fasten-project/fasten#233]
- Check the file extension before querying the DB in order to optimize the number of queries, supported extensions should be  `{.java, .py, .c, .cpp}`
- Validate PURLs before publishing the vulnerability. Write only PURLs that were successfully injected in the KB
- Implement drill-down for `apache` projects. If a vulnerability affects `org.apache.kafka:kafka`, it will probably also affect a submodule e.g. `org.kafka:kafka-clients`. `drill-down` allows to find out the submodules that are also affected.

**Comment by elanzini** [comment]
@MihhailSokolov do you know if there is any other extension that I am missing there?

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov do you know if there is any other extension that I am missing there?

I don't think so. But maybe also add `.pyw`? But regarding Python and C better ask @vitsalis and @StefanosChaliasos

**Comment by StefanosChaliasos** [comment]
Probably you may add `.h` for C.
