### ISSUE TITLE
MetadataDatabasePythonPlugin generates unexpected file path in the DB

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#234]
## Describe the bug
After processing output from PyCG, the MetadataDatabasePythonPlugin generates some inconsistently constructed path entries.

See the [CSV](https://github.com/fasten-project/fasten/files/5931850/data-1612521172606.zip) extracted from the metadata DB  for several analyzed products:
- namesss 0.1.0
- edgar3 0.1.0 - 1.1.8
- Damian-Skier-92 0.1.1
- gen-name-szczep 0.1.0 - 0.1.2
 

For all but edgar3 the file paths are correct. For edgar3 there somehow is the prefix "edgar3/" with every file, which does not exist within the file structure of the downloaded code: `fasten/pypi/sources/e/edgar3/0.1.0/*.py`

For the other products, e.g. namesss, the directory structure on disk is similar: `fasten/pypi/sources/n/namesss/0.1.0/*.py` yet there is no 'namesss' prefix.

For some reason in case of edgar3 the file path in the DB erroneously gets the prefix, which then makes it impossible to match metadata against its callables.

**Comment by MagielBruntink** [comment]
@vitsalis Is this something you could look into please?

**Comment by vitsalis** [comment]
Does this regard a new deployed pipeline? I can't find the source directory on monster.

**Comment by vitsalis** [comment]
Nevermind, managed to reproduce the bug and pushed a fix on the `pypi-tools` repo. Thanks for finding this!

**Comment by MagielBruntink** [comment]
Great! In any case, I'm running these pipelines locally:
1. `git clone git@github.com:fasten-project/fasten-docker-deployment.git`
2. `cd fasten-docker-deployment`
3. `git branch pypi-metadata-debug`
4. `source start_debug_pypi_services.sh`
5. `cat test-resources/pypi.coords.txt | docker-compose exec -T kafka kafka-console-producer.sh --broker-list kafka:19092 --topic cf_pypi_releases --property 'parse.key=true' --property 'key.separator=|'`
6. access DB at localhost:25432 using pgadmin

**Comment by MagielBruntink** [comment]
> Nevermind, managed to reproduce the bug and pushed a fix on the `pypi-tools` repo. Thanks for finding this!

Thanks for the fix! Any chance you could push a new image to Dockerhub (or Github packages)?

**Comment by vitsalis** [comment]
Sure! Just did that.

**Comment by MagielBruntink** [comment]
Thanks! The issue is resolved indeed, I just tested a full run.
