### ISSUE TITLE
/metadata/callables return empty metadata

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#237]
## To Reproduce

Enpoint: https://api.fasten-project.eu/api/metadata/callables
Method: POST
Content-Type: application/json
Content: ["fasten://mvn!org.ow2.asm:asm$7.0/org.objectweb.asm/Label.%3Cinit%3E()%2Fjava.lang%2FVoidType"]

-> return:

```
{
  "fasten://mvn!org.ow2.asm:asm$7.0/org.objectweb.asm/Label.%3Cinit%3E()%2Fjava.lang%2FVoidType": {}
}
``` 

## Expected behavior

I don't understand why the returned metadata is empty. According to https://api.fasten-project.eu/api/mvn/packages/org.ow2.asm:asm/7.0/callables?limit=1000 it should return:

```
{"access": "packagePrivate", "defined": true}
```

**Comment by MihhailSokolov** [comment]
@tmortagne this endpoint must also either provide a list of metadata fields you are interested in or you must add `allAttributes=true` if you wish to request all available metadata. If you don't specify anything, then by default it is regarded as if you provided the empty list of attributes you are interested in, so it will return an empty object. See https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#stitchingintegration for information about the parameters.

So just add `?allAttributes=true` to your request and you should get your result :)

**Comment by tmortagne** [comment]
OK thanks @MihhailSokolov.

It feels a bit strange that API is basically doing nothing when we don't pass any parameter, I would have expected to get everything by default. Then the only parameter needed is `attributes`.

**Comment by MihhailSokolov** [comment]
> OK thanks @MihhailSokolov.
> 
> It feels a bit strange that API is basically doing nothing when we don't pass any parameter, I would have expected to get everything by default. Then the only parameter needed is `attributes`.

The idea was that the REST API should do the minimal amount of work unless specified otherwise, but if you feel that as a client it would be much mire convenient to have all metadata by default, I can easily change it. Should not take more than 2 minutes :)
So should I change it then?

**Comment by tmortagne** [comment]
> the REST API should do the minimal amount of work

I understand, it's just that here it actually does nothing which might come as a surprise :) Maybe it should return an error for missing mandatory parameters instead ?

**Comment by MihhailSokolov** [comment]
> Maybe it should return an error for missing mandatory parameters instead ?


Yes, this seems like a fine solution, I will implement it.
