### ISSUE TITLE
Add custom exceptions to the vulnerability consumer plugin

### ISSUE THREAD

**Issue by mir-am** [fasten-project/fasten#249]
We need to define custom exceptions for the vulnerability consumer. Therefore, we would be able to analyze the consumer's precision and performance better. The custom exceptions will go to the `fasten.vulnerability.err` Kafka topic by the FASTEN server.

I would like to propose the following custom exceptions:
- `EcosystemNotExist`: for vulnerability statements that do not contain a package information
- `PackageIDNotFound`: for packages that do not exist in the metadata DB
- `PackageVersionIDNotFound`: for package versions that do not exist in the metadata DB
- `PatchNotExist`: for package versions that do not contain patch(es)
- `CallablesNotFound`: for patched package versions that do not have callables in the metadata DB

**Comment by proksch** [comment]
Can we please review this issue? The linked PR has been closed as it was superseded by the work on the vulnerability processor... does it mean that this issues is outdated as well?

Generally speaking, if you want to use custom exception types in your plugin (I assume to improve logging/monitoring), feel free to just create them (in your plugin), no need to make this an issue.

**Comment by mir-am** [comment]
> 

This is an outdated issue. Later on, if needed, we can create custom exceptions for the vulnerability processor.

**Comment by proksch** [comment]
Ok, closing the issue. In the future, please feel free to close issues yourself, should you realize that the comments do no longer apply.
