### ISSUE TITLE
Kafka max request size is still too small

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#256]
The MetadataDBExtension (and maybe other) plugins need a larger max.request.size setting, and then I think it will successfully process fastutil. I suggest we set it to 200 MB.

```
[2021-03-18 20:40:45,644] [INFO ] [main] [e.f.a.m.MetadataDBExtension] - Saved the 'it.unimi.dsi:fastutil:8.5.2' callgraph metadata to the database with package version ID = 912

org.apache.kafka.common.errors.RecordTooLargeException: The message is 75017198 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.
```

**Comment by wzorgdrager** [comment]
@MagielBruntink The Kafka limit is now set to 50MB and updating this requires all brokers to be restarted. I will resolve this at the beginning of next week!

**Comment by proksch** [comment]
Would it be possible to use the same "trick" that we use for the call-graph generation and serialize the expensive part of the payload to the file system?

**Comment by MagielBruntink** [comment]
I think this message appears because the call graph is indeed send as a Kafka message from the Metadata DB Extension to the Graph DB Extension. It would indeed be better to use the file system JSON of the call graph, if possible.
