### ISSUE TITLE
Make FASTEN API URL a user configurable option in Vulnerability Producer

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#265]
## Is your feature request related to a problem? Please describe.
The FASTEN API URL is hard coded in the Vulnerability Producer, which prevents the lazy ingest functionality to work correctly on other deployments than on the main FASTEN server. This also hampers testing.

https://github.com/fasten-project/fasten/blob/c80491e85e335eb3afc5de02d0f2fe621f081b1c/analyzer/vulnerability-consumer/src/main/java/eu/fasten/analyzer/vulnerabilityconsumer/db/MetadataUtility.java#L449

## Describe the solution you'd like
The FASTEN API URL becomes user-configurable, either through some property file, or an environment variable.

**Comment by MagielBruntink** [comment]
@wzorgdrager @elanzini @mir-am What do you guys think is a good approach here? A plugin such as the VulnerabilityConsumer could need at least a user config for the API url. Environment variable? Or some plugin-specific properties file? Or adding it to the (already long) list of server command line parameters?

**Comment by elanzini** [comment]
Well, the fact that we are running the consumer using the `fasten-server` makes it a bit harder to add this configuration. A quick solution would be to add it as an environmental variable and have the consumer look for it before defaulting to the `https://api.fasten.eu/api/`.
