### ISSUE TITLE
Python package metadata & callables endpoints

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#270]
D.27 aims to integrate FASTEN with the default package manager for Python, PyPI.
The [Maven plugin](https://github.com/fasten-project/fasten-maven-plugin) currently interrogates the REST API for those projects that have already been released (e.g., [here](https://github.com/fasten-project/fasten-maven-plugin/blob/2582e895bbdb0cea1aed7a46baf83d843dae259d/src/main/java/eu/fasten/maven/CheckMojo.java#L426-L430) and [here](https://github.com/fasten-project/fasten-maven-plugin/blob/2582e895bbdb0cea1aed7a46baf83d843dae259d/src/main/java/eu/fasten/maven/CheckMojo.java#L432-L446)).

The [API endpoints list](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects) only contains endpoints for Maven: are these endpoints for Python yet to be implemented?

Cc: @amphioxis

**Comment by MihhailSokolov** [comment]
> The [API endpoints list](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects) only contains endpoints for Maven: are these endpoints for Python yet to be implemented?

Yes, regarding the REST API, everything for Python and C is still to be implemented.

**Comment by marcomicera** [comment]
@MihhailSokolov is there a timeline regarding its completion? @amphioxis would need such endpoints, so he could implement them on his own if it's ok.

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov is there a timeline regarding its completion? 

It is quite hard to say at the moment. Currently, we are focusing on deliverables and other things. However, most likely in a couple of weeks I will start working on this. So my (very) rough estimate of completion is that the Python endpoints will be working in a month.

**Comment by marcomicera** [comment]
Sure, I understand. @proksch can I please ask you to create a user for @amphioxis (martin.pauling@endocode.com) on the Monster server, so that he could start implementing the Python endpoints he needs? Thank you! I guess a read-only PostgreSQL user for the `fasten_python` database should be enough.

Also, I guess there would be a bit of refactoring to be done at the beginning (e.g., [this folder](https://github.com/fasten-project/fasten/tree/develop/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn) is not just for Maven), so I can help with that. For this, I'd also need (read-only) access to the `fasten_python` database (I already have access to the Monster server, though).

**Comment by proksch** [comment]
Please contact Wouter for that. He will also need the SSH key.

**Comment by amphioxis** [comment]
@MihhailSokolov Hey Mihhail, I am trying to feed the python database of the [docker project](https://github.com/fasten-project/fasten-docker-deployment) but I think I need a different command for the kafka `$ cat test-resources/mvn.coords.txt | docker-compose exec -T kafka kafka-console-producer.sh --broker-list kafka:19092 --topic fasten.mvn.releases --property 'parse.key=true' --property 'key.separator=|'` as this command (with the python.coords.txt file) doesn't seem to work. I guess the --topic part is wrong as it specifies mvn. Can you help me out?

**Comment by MihhailSokolov** [comment]
Hi @amphioxis 
The topic name depends on the topic from which the first plugin in the pipeline consumes. In our case it is `fasten.mvn.ingest`.
The command I usually use is taken from [here](https://github.com/fasten-project/fasten/tree/master/dataset#datasets) - `kafka-console-producer --broker-list localhost:9092 --topic fasten.mvn.ingest < mvn.dataset.txt`

**Comment by marcomicera** [comment]
> In our case it is `fasten.mvn.ingest`.

Is there an equivalent for Python? I can only see these [two input topics for Maven](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#input-topics) in the Wiki. In our docker-compose `python` profile I don't see an equivalent of the POM analyzer plugin, nor an equivalent of the repo cloner. Am I missing something?

**Comment by MihhailSokolov** [comment]
You should consult @vitsalis regarding the Python pipeline. I think he is the one who created it

**Comment by amphioxis** [comment]
Closed because the basic endpoints for python are working for the [docker-compose-deployment](https://github.com/fasten-project/fasten-docker-deployment).
To feed the python database check out this [issue](https://github.com/fasten-project/fasten-docker-deployment/issues/4) or just replace ```--topic fasten.mvn.releases``` with ```--topic fasten.PyPI.releases``` .
