### ISSUE TITLE
Include Pending Vulnerability Statements in the Vulnerability Consumer Injection Pipeline

### ISSUE THREAD

**Issue by elanzini** [fasten-project/fasten#272]
The calls to the `lazy` ingestion made by the `vulnerability-consumer` are not well-handled by the current pipeline, which just proceeds with the rest of the statements to ingest. The idea is to include a `fasten.vulnerability.pending.out` kafka topic where those can be funnelled and later ingested once the package versions have been lazily ingested.

**Comment by proksch** [comment]
This idea has been superseded by the pipeline extension.
