### ISSUE TITLE
REST API endpoints resolve/dependencies and resolve/dependents do not work

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#277]
## Describe the bug
The REST API endpoints resolve/dependencies and resolve/dependents generate error pages instead of the expected output.

This problem currently impedes our integration work of FASTEN into industrial use cases.

## To Reproduce
1. https://api.fasten-project.eu/api/mvn/packages/org.springframework.cloud.stream.app:geode-sink-kafka/3.0.0/resolve/dependencies
2. https://api.fasten-project.eu/api/mvn/packages/org.springframework.cloud.stream.app:geode-sink-kafka/3.0.0/resolve/dependents

The package-version is in the DB:
https://api.fasten-project.eu/api/mvn/packages/org.springframework.cloud.stream.app:geode-sink-kafka/3.0.0

According to Maven central, it also has dependencies:
https://mvnrepository.com/artifact/org.springframework.cloud.stream.app/geode-sink-kafka/3.0.0

## Expected behavior
A list of dependencies / dependents.

**Comment by MihhailSokolov** [comment]
I will look into this first thing tomorrow. Thanks for reporting!

**Comment by MihhailSokolov** [comment]
@MagielBruntink It is working now

**Comment by MihhailSokolov** [comment]
@MagielBruntink Good point. I added [this subsection](https://github.com/fasten-project/fasten/wiki/Resolution-and-Stitching#updating-dependency-graph-on-monster) which contains commands for updating dependency graph

**Comment by MagielBruntink** [comment]
@MihhailSokolov Thank you for the documentation. I ran the commands to update on our local deployment. Surprisingly, the updated dep_graph.nodes and dep_graph.edges is a lot smaller than the files that already existed. Is this expected? Also, how did the dep_graph.nodes and dep_graph.edges files get there in the first place? What other process generates them?

**Comment by MihhailSokolov** [comment]
> Surprisingly, the updated dep_graph.nodes and dep_graph.edges are a lot smaller than the files that already existed. Is this expected? Also, how did the dep_graph.nodes and dep_graph.edges files get there in the first place? What other process generates them?

They are smaller because your local database is smaller. The dependency graph is generated by traversing `packages`, `package_versions` and `dependencies` tables in the local database (`localhost:5432`), making all artifacts into Nodes and creating edges to all relevant dependency versions. So basically, dependency graph is a copy of the database with some additional dependency edges. Then the nodes and edges of this graph are serialized into files.

**Comment by MagielBruntink** [comment]
@MihhailSokolov I meant: smaller than the .nodes and .edges files that were there for the local database. These files are being created by some other process too, it must be, because I never ran the manual update myself before.

**Comment by MihhailSokolov** [comment]
Ah, I see. The files are also created by the same process when using the REST API for the first time in case they are missing. What is the database name you use? The dependency graph generation process connects to `localhost:5432/fasten_java`. If your deployment uses the same database, then I have no idea why the file sizes are different.

**Comment by MagielBruntink** [comment]
I think they were generated with some older versions of the REST API service. Did the way these dep graphs are created change recently?

**Comment by MagielBruntink** [comment]
@MihhailSokolov Is it accurate to say that re-generating the dep graphs can be done by deleting the files and restarting the REST API container?

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov Is it accurate to say that re-generating the dep graphs can be done by deleting the files and restarting the REST API container?

Yes, that should work

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov Would it be feasible to somehow automate this updating once a new artifacts enters the DB? I think it's quite useful to have the resolve functionality in the API, especially for artifacts you encounter for the first time (hence are just added to the DB).

It is possible but not quite feasible. For large enough databases, generating and serializing the dependency graph can take more than 10 minutes. Therefore, doing so whenever a new artifact is ingested is not a good idea.
My idea is to create a cron job that would periodically (for example once a day) delete old graph and generate a new one.
If you have any suggestions for a better solution, I would be glad to discuss it.
