### ISSUE TITLE
Remove non-existing `-du` flag from Wiki

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#285]
The `-du` flag I saw [in this paragraph](https://github.com/fasten-project/fasten/wiki/Development-Environment#plug-ins-with-db-connection) doesn't exist anymore.
The username is included in the database address now:
https://github.com/fasten-project/fasten/blob/142891de4147f9bb50503b3a3b08727d9be96cfa/server/src/main/java/eu/fasten/server/FastenServer.java#L99-L104

**Comment by proksch** [comment]
For these kind of inconsistencies it is not necessary to open an issue, feel free to correct the documentation yourself!
