### ISSUE TITLE
REST API needs to be generalized to Python/PyPI and C/Debian

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#288]
## Is your feature request related to a problem? Please describe.
The currently available REST API implementation is specific to Java/MVN, partially, and some endpoints fail with eg. PyPI coordinates. Let's use this issue to discuss and come up with the next iteration.

## Describe the solution you'd like
A more generic REST API implementation that will work for all ecosystems within FASTEN, and that can be easily extended in the future as well.

## Additional context
Related issue:
https://github.com/fasten-project/fasten-pypi-plugin/issues/4

**Comment by marcomicera** [comment]
I could only provide my initial support by refactoring code & endpoints, i.e., by moving all the common parts out of the `mvn` Java package and by getting rid of the `/mvn/` for all the endpoints.

I remember though I started doing this to help @amphioxis out with his PyPI plugin but there were a lot of connections to external services that were new to me, so I gave up after one day.

Other than that, unfortunately I don't know which endpoints are Maven-specific.

**Comment by MagielBruntink** [comment]
@MihhailSokolov I believe you implemented most of the Maven endpoints. What would be your suggested approach here? Is it feasible to generalize in some way?

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov I believe you implemented most of the Maven endpoints. What would be your suggested approach here? Is it feasible to generalize in some way?

Some of the endpoints cannot be really generalized, for example endpoints that involve dependency resolution. But all endpoints that only deal with getting simple data from the database should be fairly simply generalizable.

**Comment by MagielBruntink** [comment]
Let's discuss the overall setup we envision. It is given that there is a seperate Metadata-DB for each language. The current REST API components connects to a single such database. 
1. Do we want to go to the situation where we will deploy a separate REST API container for each ecosystem? Or do we deploy 1 container which decides internally what API to route to?
2. On the code level, do we want to have a separate package for each ecosystem, eg. `eu.fasten.analyzer.restapiplugin.mvn.api`, `eu.fasten.analyzer.restapiplugin.pypi.api` and `eu.fasten.analyzer.restapiplugin.debian.api` with classes for each endpoint like https://github.com/fasten-project/fasten/blob/develop/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/CallableApi.java ? 
3. How are we going to avoid having large amounts of duplicated API/endpoint descriptions and implementations?

Perhaps @gousiosg could add to the discussion?

**Comment by MagielBruntink** [comment]
Some endpoints in the `mvn` set of classes do not start their URL with `/mvn/` such as `/callables`. In the current deployment they are actually specific to an ecosystem as the code only connects to 1 specific DB. What should we do about those? Add the `/mvn` prefix after all?
https://github.com/fasten-project/fasten/blob/b60ea2f467c490fb8dc0d16feaa333af134359e9/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/CallableApi.java#L60
