### ISSUE TITLE
Update metadata DB schema in Wiki

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#289]
The [Metadata DB wiki page](https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema) contains an outdated image of its schema (e.g., the [`module_names` table](https://github.com/fasten-project/fasten-docker-deployment/blob/05b8f3d83a58555354b918c51e87d55b7573750b/metadata-db/psql_create_tables_java.sql#L54-L58) is missing).

**Comment by MihhailSokolov** [comment]
Thanks for the reminder @marcomicera!
[It is updated now.](https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema)

**Comment by marcomicera** [comment]
Thanks a lot! Closing.
