### ISSUE TITLE
MergerEfficiencyTests.localMergerEfficiencyTest test fail

### ISSUE THREAD

**Issue by amottier** [fasten-project/fasten#293]
## Describe the bug
When building the `fasten` project (`mvn clean install` after git checkout of `develop` branch) I get the following error:
```
[ERROR] localMergerEfficiencyTest  Time elapsed: 13.725 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <50513> but was: <50511>
        at eu.fasten.core.merge.MergerEfficiencyTests.localMergerEfficiencyTest(MergerEfficiencyTests.java:83)
```

## To Reproduce
1. Checkout the `develop` branch
2. Run the build with Maven `3.6.3` and Java `11.0.11` provided by the `openjdk-11-jdk:amd64` Debian Buster package version `11.0.11+9-1~deb10u1` on Linux Debian kernel from backports (`5.10.0-0.bpo.7-amd64`).

## Expected behavior
A successful build.

## Logs
[Maven build log](https://github.com/fasten-project/fasten/files/6861340/log-clean-install-root-mvn-3.6.3.log)

## Environment (please complete the following information):
 - OS: Debian 10 Buster kernel 5.10.0-0.bpo.7-amd64
 - Java version: `11.0.11` (Debian Buster package version `11.0.11+9-1~deb10u1`)

## Additional context
Compare to successful build on GitHub, the only difference I can spot is the JVM: GitHub action using Zulu OpenJDK.

**Comment by MagielBruntink** [comment]
I also run into this problem. Locally (Windows 10) I get 50515 nodes in localMergerEfficiencyTest. Thought I would fix it with https://github.com/fasten-project/fasten/commit/ea478f3afaaf67dd3cb7f007b911603fd97eb050 but on CI the node count is 50513...

**Comment by MagielBruntink** [comment]
50513 nodes on local run on MacOS laptop.

**Comment by marcomicera** [comment]
It passes on my local machine as well, macOS 11.0.1, java 11.0.2, Maven 3.6.3.

**Comment by marcomicera** [comment]
I can replicate this issue in one of my Dockerfile stages I use during development:

https://github.com/fasten-project/fasten/blob/c7701dcfd7305ad204425ab9a036a72896209287/docker/license-detector/Dockerfile#L35

Exactly the same behavior.

Base image is:

https://github.com/fasten-project/fasten/blob/c7701dcfd7305ad204425ab9a036a72896209287/docker/license-detector/Dockerfile#L22

**Comment by ashkboos** [comment]
Passes locally: Apache Maven 3.6.2, Java version: 11.0.9.1, "mac os x" version: "10.15.7"

**Comment by amottier** [comment]
I run again the build locally on my computer with Java `11.0.11` and Maven `3.6.2` and still reproduce the issue.

@marcomicera replicate on Docker image `maven:3.8.1-jdk-11-slim`. This image is based on `openjdk:11-jdk-slim` that is actually based on Debian Buster image with Java version `11.0.12` (see https://github.com/docker-library/openjdk/blob/6c18f690c35e42950119a92d2edd854a869745c5/11/jdk/slim-buster/Dockerfile#L30)

I also try to use Java `11.0.9.1` from `openjdk` Docker image (`openjdk:11.0.9.1-jdk-slim`) and use Maven wrapper to run Maven `3.6.2` (basically exact same environment as @ashkboos) but still get the same error :disappointed: 

So no progress on my side so far.

**Comment by marcomicera** [comment]
It [fails in the CI](https://github.com/fasten-project/fasten/runs/3201289122?check_suite_focus=true) too... what a bummer 😞

**Comment by marcomicera** [comment]
I rebased on top of [`develop`](https://github.com/fasten-project/fasten/tree/develop) and [it still fails](https://github.com/fasten-project/fasten/runs/3203339658?check_suite_focus=true).

**Comment by marcomicera** [comment]
I'll temporarily disable this test in my plugin's GitHub Actions workflow as a workaround, I need the CI to build images. I'll make sure I'll include a `FIXME` comment there so I won't lose it!

**Comment by romatallinn** [comment]
_**From weekly meeting:**_

Server's JDK version:
```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)
```

It can be a good try to use the same version locally, run the test and see if it is the issue.

**Comment by amottier** [comment]
I reproduce the issue with:
```
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)
```
running locally on my computer. I attached the build [log](https://github.com/fasten-project/fasten/files/6954678/log-clean-install-root-develop-mvn-3.8.1-openjdk-11.0.12%2B7-202108091448.log)
.

**Comment by proksch** [comment]
Is this issue still relevant?

**Comment by ashkboos** [comment]
We do not check the number of nodes and edges anymore on the develop branch so this problem should not occur. Now we only check the time that this unit test takes which is the main purpose of this test. Such minor differences are expected in different environments and setups. Especially because the number of edges does not differ, the output CG should be correct in any case. 
Hence, I will close this PR, please feel free to reopen if you experienced a relevant problem.
