### ISSUE TITLE
RepoCloner hangs for a couple of mins right at the end of cloning

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#299]
It's more a performance thing rather than a bug, as nothing is broken.

On my local machine, the RepoCloner plugin often hangs right at the end of cloning a repo:

```
[2021-07-27 16:53:33,621] [DEBUG] [main] [o.e.j.t.PacketLineOut] - git> want 40b31ae43973800c83a58db8c68fba9da9128138

[2021-07-27 16:53:33,625] [DEBUG] [main] [o.e.j.t.PacketLineOut] - git> 0000
[2021-07-27 16:53:33,634] [DEBUG] [main] [o.e.j.t.PacketLineOut] - git> done

[2021-07-27 16:53:34,002] [DEBUG] [main] [o.e.j.t.PacketLineIn] - git< NAK
[2021-07-27 17:00:08,392] [INFO ] [main] [e.f.a.r.RepoClonerPlugin$RepoCloner] - Successfully cloned the repository for info.picocli:picocli:4.0.4 from https://github.com/remkop/picocli/tree/master
[2021-07-27 17:00:08,549] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Successfully processed message offset 1 from partition 0.
[2021-07-27 17:00:08,584] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Committed offsets [1] of partitions [0].
```

Notice that it spent almost 7 minutes right at the end, between `git< NAK` and the `Successfully cloned the repository` message. It's slowing the pipeline by just a bit.

## Test record

```shell script
echo 'info.picocli:picocli:4.0.4|{"groupId":"info.picocli","artifactId":"picocli","version":"4.0.4"}' | docker-compose exec -T kafka kafka-console-producer.sh --broker-list kafka:19092 --topic fasten.mvn.releases --property 'parse.key=true' --property 'key.separator=|'
```

**Comment by marcomicera** [comment]
A quick git blame brought me to you, @MihhailSokolov: is it easy to fix? It's not super important.

**Comment by MihhailSokolov** [comment]
Yep, I noticed this problem from time to time. I don't really know what causes it. Will try to investigate it when I have time. Thanks @marcomicera

**Comment by MihhailSokolov** [comment]
Hey @marcomicera 
I wasn't really able to reproduce the issue locally. When I run it, it hangs only for a few seconds at the end, not a few minutes as in your case.
```
11:57:21.034 [main] DEBUG org.eclipse.jgit.transport.PacketLineOut - git> want c80e7d112dfb48805c078bfeb629911c651c3369

11:57:21.034 [main] DEBUG org.eclipse.jgit.transport.PacketLineOut - git> want 13370719cb589da6a9275444022d60ab473535a0

11:57:21.035 [main] DEBUG org.eclipse.jgit.transport.PacketLineOut - git> want 40b31ae43973800c83a58db8c68fba9da9128138

11:57:21.035 [main] DEBUG org.eclipse.jgit.transport.PacketLineOut - git> 0000
11:57:21.036 [main] DEBUG org.eclipse.jgit.transport.PacketLineOut - git> done

11:57:21.324 [main] DEBUG org.eclipse.jgit.transport.PacketLineIn - git< NAK
11:57:35.627 [main] INFO eu.fasten.analyzer.repoclonerplugin.RepoClonerPlugin$RepoCloner - Successfully cloned the repository for info.picocli:picocli:4.0.4 from https://github.com/remkop/picocli/tree/master
```
My guess is that it uses a lot of RAM and starts to hang when there is not enough heap space. I would suggest you try to increase the heap space and see if the problem persists.

**Comment by marcomicera** [comment]
> My guess is that it uses a lot of RAM and starts to hang when there is not enough heap space. I would suggest you try to increase the heap space and see if the problem persists.

I think you're right, I'm not even experiencing a delay in my dev k8s cluster. This might be a bummer only for those who still need to develop on docker-compose...

**Comment by proksch** [comment]
Seems that the issue has been clarified. Please feel free to re-open should the issue persist.
