### ISSUE TITLE
Files without documentation

### ISSUE THREAD

**Issue by mir-am** [fasten-project/fasten#3]
This is a list of files without documentation, which helps us find the files and improve their docs.
I can also help with the documentation.

- https://github.com/fasten-project/fasten/blob/b0421f2d3360c7a528defbd608baeedd3bd2b15b/core/src/main/java/eu/fasten/core/query/Query.java#L7

- https://github.com/fasten-project/fasten/blob/b0421f2d3360c7a528defbd608baeedd3bd2b15b/core/src/main/java/eu/fasten/core/index/FenwickTree.java#L24

- https://github.com/fasten-project/fasten/blob/b0421f2d3360c7a528defbd608baeedd3bd2b15b/pipeliner/src/main/java/eu/fasten/pipeliner/Pipeliner.java#L36

- https://github.com/fasten-project/fasten/blob/b0421f2d3360c7a528defbd608baeedd3bd2b15b/server/src/main/java/eu/fasten/server/FastenServer.java#L34

- https://github.com/fasten-project/fasten/blob/b0421f2d3360c7a528defbd608baeedd3bd2b15b/core/src/main/java/eu/fasten/core/index/KBStats.java#L38

- https://github.com/fasten-project/fasten/blob/85a013c2525a5c87047a6c9e7bb308f16a9b37ad/core/src/main/java/eu/fasten/core/index/BVGraphSerializer.java#L29

**Comment by proksch** [comment]
I am always in favor of documenting interfaces well, but all these examples are implementations... I think we should be lenient there. For real programmers, code is self-documenting! 😜
