### ISSUE TITLE
Allow passing a custom maven repository to javacg analyzers

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#30]
javacg-wala and javacg-opal used a hardcoded `https://repo.maven.apache.org/maven2/` for the repository when passing coordinates.

Would be very useful to allow passing an list of alternative Maven repositories to look at to find the artifact and its dependencies.

**Comment by ilyagrishkov** [comment]
New version of MavenCoordinate allows to pass a list of repos. If nothing is passed, `https://repo.maven.apache.org/maven2/` will be used by default.
