### ISSUE TITLE
Multi-topic subscription

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#300]
https://github.com/fasten-project/fasten/pull/297 aims to extend our license detector to work also for C & Python projects.
Therefore, the `license-detector` plugin would need to subscribe to multiple topics (https://github.com/fasten-project/fasten/pull/297#issuecomment-888264361):

> As of now, it consumes records belonging to the `fasten.SyncJava.out` topic, which combines `fasten.RepoCloner.out` and `fasten.MetadataDBJavaExtension.out`. The latter is Maven-specific, so that's a problem.

Is there currently a way to let a plugin subscribe to multiple topics?
I don't see such a feature in the [`KafkaPlugin` interface](https://github.com/fasten-project/fasten/blob/develop/core/src/main/java/eu/fasten/core/plugins/KafkaPlugin.java), hence this question.

_Assigning after a quick git-blame on [`KafkaPlugin`](https://github.com/fasten-project/fasten/blob/develop/core/src/main/java/eu/fasten/core/plugins/KafkaPlugin.java)._

**Comment by marcomicera** [comment]
My idea would be to use 3 different Flink sync jobs and to make [`KafkaPlugin`](https://github.com/fasten-project/fasten/blob/develop/core/src/main/java/eu/fasten/core/plugins/KafkaPlugin.java) an abstract class rather than an interface, so that we can add a method with a body that essentially does [this](https://stackoverflow.com/a/39569746/3927431).

**Comment by luxb70** [comment]
or perhaps, without converting it to an abstract class, we could add a default method to the interface

**Comment by marcomicera** [comment]
@luxb70 can you do this? Adding that method shouldn't be a big deal, it's more a matter of testing whether that actually works, and that it doesn't break anything, etc.

**Comment by mir-am** [comment]
I want to close this issue. As the new improvements to the FASTEN server allow to subscribe Kafka topics including normal/priority topics.
