### ISSUE TITLE
Graph resolver doesn't resolve dependencies transitively

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#303]
## Describe the bug
There is a utility method of Graph Resolver that resolves dependencies. It accepts argument that forces the method to resolve transitive dependencies. It does not in fact retrieves transitive dependencies.

## To Reproduce
1. `com.fasterxml.jackson.core:jackson-databind/2.8.11` depends on `junit:junit/4.12` - [CHECK HERE](https://api.fasten-project.eu/api/mvn/packages/com.fasterxml.jackson.core:jackson-databind/2.8.11/resolve/dependencies) ✅
2. `com.fasterxml.jackson.core:jackson-databind/2.8.11` has a dependent `com.lightbend.lagom:lagom-scaladsl-cluster_2.11/1.4.1` - [CHECK HERE](https://api.fasten-project.eu/api/mvn/packages/com.fasterxml.jackson.core:jackson-databind/2.8.11/resolve/dependents) ✅
3. If `com.lightbend.lagom:lagom-scaladsl-cluster_2.11/1.4.1` resolves dependencies with transitive flag, it doesn't have `junit` in results. [CHECK HERE](https://api.fasten-project.eu/api/mvn/packages/com.lightbend.lagom:lagom-scaladsl-cluster_2.11/1.4.1/resolve/dependencies?transitive=true) ❌

## Expected behavior
As transtive flag suggests, it is supposed to force the method to retrieve not only first level dependencies, but transitive dependencies as well. Thus, `com.lightbend.lagom:lagom-scaladsl-cluster_2.11/1.4.1` shall have in dependencies `junit:junit/4.12`, but it doesn't.

## Additional context
Although the justifications are given by API endpoints, which theoretically could mess up something inside, but debugging of Vulnerability Cache Processor plugin that uses the graph resolver directly also shows the same problem, thus API is not the source of the problem.

> In figure you see example of `com.lightbend.lagom:lagom-scaladsl-cluster_2.11/1.4.1` from direct use of graph resolver by Vulnerability Cache Processor plugin. Although we force transitivity in code, we get only 3 dependencies that are 1st level dependencies.

<img width="1184" alt="Screenshot 2021-08-26 at 01 41 58" src="https://user-images.githubusercontent.com/14923964/130878474-40172845-1ad4-4103-b311-1fe7d68cf72d.png">

**Comment by proksch** [comment]
How do we handle Maven scopes? Ist this caused by junit probably only being added as dependency in the test scope?

**Comment by proksch** [comment]
With a bit more insight into the pipeline, I am assuming that the transitive dependencies were simply not part of the database, as they have never been ingested. This changes in the new PomAnalyzer. For now, I would like to close this issue... we can re-open, should the problem not be fixed after resetting the pipeline. We will also look into the graph resolver as one of our very next tasks, so we will also discover any problem there that might cause this.
