### ISSUE TITLE
CGMerger generates again impossibly small graphs

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#305]
In the test_merge branch, on monster, try 

java eu.fasten.core.search.Test jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/graphdb resolver.graph

The code tries to stitch the graph with id 9028. The err output is

```
2021-09-27 18:31:10,617 13373 INFO [main] e.f.c.s.Test - Analyzing graph io.gravitee.rest.api:gravitee-rest-api-service$3.3.1 with id 9028 and 7480 nodes
2021-09-27 18:31:11,284 14040 INFO [main] e.f.c.m.CGMerger - Created the Universal CHA with 644 vertices in 0.660
2021-09-27 18:31:11,508 14264 INFO [main] e.f.c.m.CGMerger - Created the type dictionary with 605 types in 0.220 seconds
2021-09-27 18:31:11,544 14300 INFO [main] e.f.c.m.CGMerger - Merging graph with 7480 nodes and 9761 edges
2021-09-27 18:31:11,706 14462 INFO [main] e.f.c.m.CGMerger - Merged call graphs in 0.165 seconds, num node: 74, num edges: 228
2021-09-27 18:31:11,713 14469 INFO [main] e.f.c.s.Test - Nodes in deps: 4152
2021-09-27 18:31:11,715 14471 INFO [main] e.f.c.s.Test - Nodes in stitched graph: 74

```

Note that the base graph has 9028 nodes, and there are 4152 nodes in the dependencies.

The stitched graph contains only 74 nodes—less than 1% of the nodes of the graph it is supposed to stitch with other graphs.

**Comment by ashkboos** [comment]
I looked into your test script, I noticed one problem in this line: https://github.com/fasten-project/fasten/blob/18ed04791784855dddef01d97376a673edf28717/core/src/main/java/eu/fasten/core/search/Test.java#L109
Please call mergeAllDeps() method after you instantiate the CGMerger. Currently, you are only getting the edges of the 9028 excluding the dependencies.

**Comment by vigna** [comment]
I see. Where is the documentation on how to use this class? CGMerger has zero class documentation.

**Comment by ashkboos** [comment]
It is here: https://github.com/fasten-project/fasten/wiki/Resolution-and-Stitching

**Comment by vigna** [comment]
Oh OK. So there was a change of API from the LocalMerger when the two approaches were merged together.

I found this code in the documentation:

```
var merger = new CGMerger(depSet, dbContext, rocksDao);
var mergedDirectedGraph = merger.mergeWithCHA(artifact);
//or by calling databaseMerger.mergeAllDeps() the whole dependency set will be stitched.
```

It is very confusing for me because there is a suggested code _in a comment_ invoking a variable _that does not exists_.

Let's see if I can derive the correct code.

It seems the correct sequence to obtain the stitched graph is getting the dependencies using `resolver.resolveDependencies()` and then

```
var merger = new CGMerger(depSet, dbContext, rocksDao);
var mergedDirectedGraph = merger.mergeAllDeps();
```

Am I correct?

Note that it would be infinitely easier, given the lack of class documentation and the confusion in the Wiki, if you would modify the Test so that it works.

**Comment by ashkboos** [comment]
Yes, it was a mistake in the documentation the variable name is `merger` not `databaseMerger`, I fixed it. Thanks for pointing this out.
I also modified the Test.

**Comment by vigna** [comment]
Now we're getting to the point.

I could not understand how this could possibly work, or have _ever_ worked, because the dependency set does not contain the original graph.

Now that finally you have fixed Test I can see you are adding _manually_ the gid of the revision to the dependency set.

This fundamental fact is nowhere to be found in the "documentation" at https://github.com/fasten-project/fasten/wiki/Resolution-and-Stitching

The output is now reasonable. It is a fact that there is zero correct documentation on how to use this class.

**Comment by ashkboos** [comment]
I added a note to the Wiki page.
