### ISSUE TITLE
Merged graphs contain isolated nodes

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#310]
## Describe the bug
While trying to build paths between packages to find the chain of callables to vulnerabilities, I encountered at least one example where the merged graph seems to contain in fact isolated nodes.

## To Reproduce

For reproduction, please see the attached logs and instructions on how to identify the problem there.

### Prerequisites
The goal is to have a path from internal callables to vulnerable callables.

Set of internal callables in the graph (wanted root; artifact `cn.onekit.x2x.cloud:thekit:1.3.0`):
```
[4947271, 4947273, 4947275, 4947276, 4947277, 4947278, 4947279, 4947281, 4947284]
```

Set of vulnerable callables in the graph (wanted target):
```
[146885033, 146888712, 146892904, 146892908, 146891185, 146888723, 146897682, 146887477, 146891189, 146893653, 146891191, 146891192, 146885051, 146896698, 146898298, 146893661, 146893692, 146888735]
```

[Nodes & Edges Logs.txt](https://github.com/fasten-project/fasten/files/7322317/Nodes.Edges.txt)

### Instructions 
1. Take any callable ID from the vulnerable set provided above (e.g., `146885033`);
2. Open [Nodes & Edges Logs.txt](https://github.com/fasten-project/fasten/files/7322317/Nodes.Edges.txt) log file;
3. Try to search in the file by the chosen callable ID;
4. The first result should show the callable in the set of graph nodes (ids separated by comma) -> not a problem;
5. The results that follow after that are edges (in format of `( ID : ID)`);
6. The problem is that the chosen vulnerable callable ID has one edge with itself (f.e., `(146885033 : 146885033)`), thus isolated from the rest of the graph.

**Comment by romatallinn** [comment]
Another example for `io.micronaut.servlet:micronaut-http-server-tomcat:2.0.0`

Vulnerable Callables: 
```
[146885033, 146888712, 146892904, 146892908, 146891185, 146888723, 146897682, 146887477, 146891189, 146893653, 146891191, 146891192, 146885051, 146896698, 146898298, 146893661, 146893692, 146888735]
```

[Nodes & Edges.txt](https://github.com/fasten-project/fasten/files/7381833/Edges.txt)

**Comment by mir-am** [comment]
This should be resolved by the new vulnerable call chain detection is developed by @ashkboos recently.
