### ISSUE TITLE
javagc-wala does not seems to take into account the -jre parameter

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#32]
Command: `java -jar javacg-wala-0.0.1-SNAPSHOT-with-dependencies.jar -jre /media/DATA/utils/jdk8 -c org.xwiki.commons:xwiki-commons-collection:12.4 -o .`

The command work fine and produce an accurate JSON file but it also log the following warning:
> WARNING: java_runtime_dir /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home in wala.properties is invalid.  Using boot class path instead.

This seems to suggest that the -jre parameter was not really taken into account and that it instead tried some hardcoded test path.

**Comment by ilyagrishkov** [comment]
You're right, there was a problem with changing the path to JRE. `-jre` is no longer a parameter for Wala plugin. 
Note: Wala is no longer a module of Fasten. A standalone version of Wala can be found here: https://github.com/fasten-project/javacg-wala

**Comment by tmortagne** [comment]
> A standalone version of Wala can be found here: fasten-project/javacg-wala

Great news :)
