### ISSUE TITLE
javacgopal does not build: cannot find symbol class AllocationSiteBasedPointsToCallGraphKey$ 

### ISSUE THREAD

**Issue by plaird** [fasten-project/fasten#320]
## Describe the bug
I am looking forward to [your talk at EclipseCon](https://eclipsecon.app.swapcard.com/event/eclipsecon-2021/planning/UGxhbm5pbmdfNjA4NTY4). I wanted to try the project tonight so I can ask more detailed questions, but I am having issues adding the plugin to my project.

## To Reproduce

I followed the instructions here: [add fasten maven plugin to pom.xml](https://github.com/fasten-project/fasten-maven-plugin/wiki).
But the plugin seems not to be available [in Maven Central](https://search.maven.org/search?q=fasten-maven-plugin).
So I then tried to follow the instructions here to build Fasten plugin myself.

```
git clone git@github.com:fasten-project/fasten-maven-plugin.git
mvn clean install
[ERROR] Failed to execute goal on project fasten-maven-plugin: Could not resolve dependencies for project eu.fasten:fasten-maven-plugin:maven-plugin:1.0-SNAPSHOT: Could not find artifact eu.fasten.analyzer:javacg-opal:jar:0.0.1-SNAPSHOT -> [Help 1]
```

Which failed because I need to build Fasten locally. So I tried to build Fasten, but this is the problem:

```
git clone https://github.com/fasten-project/fasten
mvn clean install
...
javacg-opal 0.0.1-SNAPSHOT ......................... FAILURE [  0.500 s]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project javacg-opal: Compilation failure: Compilation failure: 
[ERROR] /Users/plaird/dev/fasten/analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/CallGraphConstructor.java:[35,24] cannot find symbol
[ERROR]   symbol:   class AllocationSiteBasedPointsToCallGraphKey$
[ERROR]   location: package org.opalj.tac.cg
[ERROR] /Users/plaird/dev/fasten/analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/CallGraphConstructor.java:[39,24] cannot find symbol
[ERROR]   symbol:   class TypeBasedPointsToCallGraphKey$
[ERROR]   location: package org.opalj.tac.cg
```

## Expected behavior
Successful build of Fasten, then a successful build of the Maven plugin.

## Environment (please complete the following information):
 - OS: MacOS
 - Java version: 11.0.10

**Comment by proksch** [comment]
Is this issue still relevant? We are in the process of migrating to a [new loader platform](https://github.com/fasten-project/data-processing), where all Maven dependencies are properly released (admittedly, only as GitHub packages for now). We will migrate all tools and repositories to that infrastructure over the next weeks, which should solve accessibility problems like the one at hand. Please re-open this issues if you need further help.
