### ISSUE TITLE
Re-Instantiation of the MavenGraphResolver to reflect new packages/dependencies

### ISSUE THREAD

**Issue by proksch** [fasten-project/fasten#333]
My understanding of the current `MavenGraphResolver` implementation is that it is being instantiated with information from the Postgres DB whenever it is started, but it does never update. As we constantly add new packages to the DB, the contained information is quickly outdated, which makes the resolution of dependencies unreliable... as such, we need to find a better solution to update the contents of the dependency graph.

In a perfect world, we would subscribe to the corresponding Kafka topics and maintain the graph on-the-fly when new packages are added, but this is a more extensive task... A quick and dirty first solution would be to schedule a nightly restart of the REST API to have at least a *somewhat* recent representation of the dependencies. Unfortunately, restarting is costly, as building the graph takes around 5-10min, and we definitely need a better solution for this rather sooner than later... but I think a 10min downtime at 2am is better then inconsistent information.

**Comment by mir-am** [comment]
I'd like to close this issue as I've created a Kubernetes cron job to restart the REST API and the dep. graph at 3 AM every day. The corn job manifest files are uploaded to our k8s repository.
