### ISSUE TITLE
Create a license feeder for the Debian use case

### ISSUE THREAD

**Issue by lisa-noeth** [fasten-project/fasten#336]
For the Debian use case, the license information at the file level will be retrieved by querying the Debian API instead of running Scancode (as for Java and Python).
As suggested by Alexios Zavras @zvr, at least for this specific use case, we would like to implement the approach of pre-collecting license information and storing them in a persistent database.

We currently data-scraped half of the whole set of packages present in the last Debian distro (version 11, bullseye). To finally retrieve license information at the file level, we will use their checksum (implying a further call to the APIs).

This pre-collection doesn't rely on any Kafka messages, which are persistently stored—not helping us feed the db in case of restart.

On the other hand, surges the need of having a separate persistent DB, hopefully keeping the exact structure of the current metadata DB, that can be then synced with the Fasten metadata DB when bootstrapped. 

Keep in mind that 23k packages are already scraped, each containing the original directory and files structure.

**Comment by michelescarlato** [comment]
Hi Amir @mir-am, 

I am writing a Debian license feeder that will be used to pre-populate the metadata DB. 

Looking at the [db schema](https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema), I was wondering if I have to set the ID for the `packages` table, or if it is assigned automatically (as I guess).

The following two questions are:

1. I guess I have to retrieve the `id` from the `packages` table (if not assigned by me during the feeding) and use it as `package_id` to insert an entry on the `package_versions` table. Is that right?

2. To populate the `files` table, I should use the `id` of the `package_versions` table, which will become the `package_version_id` of the `files` table. Do you confirm this reasoning?

Thank you in advance,
Michele

**Comment by mir-am** [comment]
> Hi Amir @mir-am,
> 
> I am writing a Debian license feeder that will be used to pre-populate the metadata DB.
> 
> Looking at the [db schema](https://github.com/fasten-project/fasten/wiki/Metadata-Database-Schema), I was wondering if I have to set the ID for the `packages` table, or if it is assigned automatically (as I guess).
> 
> The following two questions are:
> 
> 1. I guess I have to retrieve the `id` from the `packages` table (if not assigned by me during the feeding) and use it as `package_id` to insert an entry on the `package_versions` table. Is that right?
> 2. To populate the `files` table, I should use the `id` of the `package_versions` table, which will become the `package_version_id` of the `files` table. Do you confirm this reasoning?
> 
> Thank you in advance, Michele

Hi Michele (@michelescarlato),

To answer your two questions:
1- Yes. You need to use the `id` from the packages table, which is generated automatically.
2- As you described, to populate the `files` table, you first need to locate the Debian package in the `package_versions` table, then find its files and insert the license metadata.

**Comment by michelescarlato** [comment]
Thank you, Amir (@mir-am) for your fast and clear response!

**Comment by michelescarlato** [comment]
Hi Amir @mir-am , 

Reasoning following the previous questions.

The `package id` should be assigned after a package has been `repo-cloned`, right?

From my understanding, this means that I cannot feed a db with pre-collected data following the original schema.
Because if I have a set of pre-collected data, the `repo-cloner` should check the db, preventing writing a double entry.
Do you agree with this?

For this specific case (`C-Debian), probably the repo-cloner should behave differently from the other cases (`Maven`, `Pypi`). Is my supposition correct?

**Comment by mir-am** [comment]
> The `package id` should be assigned after a package has been `repo-cloned`, right?

No! Not necessarily. The `package_id` is already assigned by the other plug-in (dep. analyzer). You need to use it to locate packages and insert the license info in the `metadata` field.

> From my understanding, this means that I cannot feed a db with pre-collected data following the original schema. Because if I have a set of pre-collected data, the `repo-cloner` should check the db, preventing writing a double entry. Do you agree with this?

AFAIK, the `repo-cloner` doesn't interact with the DB. You need to **update** the metadata field and insert license info in it.

> For this specific case (`C-Debian), probably the repo-cloner should behave differently from the other cases (`Maven`, `Pypi`). Is my supposition correct?

AFAIK, the `repo-cloner` job is to receive source code for packages if available.

**Comment by michelescarlato** [comment]
> > The `package id` should be assigned after a package has been `repo-cloned`, right?
> 
> No! Not necessarily. The `package_id` is already assigned by the other plug-in (dep. analyzer). You need to use it to locate packages and insert the license info in the `metadata` field.


So I have a problem @mir-am Amir!
To populate the metadatadb with a set of data pre-collected, I would need to create an entry (and not to update it).

The data-scraping that I am doing for Debian, has the main goal to have 46k packages and their files with pre-collected license information.

The need to have license information pre-collected has widely discussed with Alexios (@zvr ) and it seems to be the most logical approach.

How do you suggest dealing with this?

IMHO the possible solutions are:
1. fulfilling another DB with license information, and when the whole fasten pipeline starts the license detector is going to take license information from this second DB.
2. enabling the dep.analyzer for searching if an entry already exists in the db (an entry that has been created while feeding with pre-collected data).

**Comment by michelescarlato** [comment]
Currently, the `c` pipeline is partially functioning, so the issue can be closed.
