### ISSUE TITLE
Clean-up of MavenCoordinate required

### ISSUE THREAD

**Issue by proksch** [fasten-project/fasten#338]
Right now, we have the class [MavenCoordinate](https://github.com/fasten-project/fasten/blob/develop/core/src/main/java/eu/fasten/core/data/opal/MavenCoordinate.java) to abstract away some Maven details... Unfortunately, the class is a big mess and urgently requires a thorough refactoring.

- It is supposed to be a data structure, but it contains a download method that downloads Maven artifact from a repository. This should be split up into two classes. The data structure and a utils class.
- The test for the class are still located in the `javacg-opal` plugin, apparently the class has been moved, but the tests were left in the old place.
- The tests of `CallGraphConstructor` are based on the downloading functionality and *download actual packages on every build*, this is not acceptable. I propose two extensions 1) downloads should be cached in a configurable folder, which should also reduce the network footprint of the FASTEN pipeline. 2) The download logic in `MavenCoordinate` should be refactored such that it can be mocked for the `CallGraphConstructorTest` to avoid a download and make the test faster.

Do we have any volunteer that wants to clean up this class?

**Comment by mir-am** [comment]
I can take care of the first two tasks. We have `MavenUtilties` in `core` which downloads Maven artifacts.
I leave the third task to Mehdi as he's the main developer for the OPAL plug-in.

**Comment by mir-am** [comment]
The first and second tasks were done in #344. I'd like to close the issue. We can do the third task in another issue or PR.

**Comment by proksch** [comment]
Agreed, but then please open another issue or this will be forgotten. ;)
