### ISSUE TITLE
GraphMavenResolver returns very small dependency graphs

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#347]
Using the usual Example in the integration branch, try

```
java eu.fasten.core.search.Example 1200159 jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/callable-index/ resolver.graph
```

which will try to stich BUbiNG's graph. We read in the output

```
2021-11-30 18:11:41,235 83740 INFO [main] e.f.c.s.Example - Analyzing graph it.unimi.di.law:bubing$0.9.12 with id 1200159
2021-11-30 18:11:41,236 83741 INFO [main] e.f.c.s.Example - Dependencies: {junit:junit:4.12, org.apache.commons:commons-math3:3.6.1, org.hamcrest:hamcrest-core:1.3, com.google.guava:guava:21.0}
2021-11-30 18:11:43,080 85585 INFO [main] e.f.c.m.CGMerger - Created the Universal CHA with 3937 vertices in 1.773
2021-11-30 18:11:43,257 85762 INFO [main] e.f.c.m.CGMerger - For 5 dependencies failed to retrieve 0 graph data and 0 metadata from rocks db.
2021-11-30 18:11:43,258 85763 INFO [main] e.f.c.m.CGMerger - Created the type dictionary with 4167 types in 0.166 seconds
```

The actual dependencies are about 70, and in fact even in the Postgres database the set of direct dependencies is much larger.

**Comment by vigna** [comment]
Analogously, using id 628341 (LAW library 2.7.2) we obtain about 30 dependencies instead of more than 300.

**Comment by mir-am** [comment]
Thanks for posting the issue.
How do you obtain the actual dependencies? It would be good if you could post the SQL query that is used for obtaining dependencies from Postgres.

**Comment by vigna** [comment]
What do you mean? There's a test class. Did you read the report? It is about GraphMavenResolver. There's no direct interaction with Postgres.

**Comment by mir-am** [comment]
I mean how did you come up with 70 actual dependencies? Based on the posted logs above, there are 5 dependencies.

**Comment by vigna** [comment]
Those are the dependencies actually found by Ivy (or Maven). Real-life dependencies.

**Comment by mir-am** [comment]
To investigate the issue further, I have queried the metadata DB to find the dependencies for `it.unimi.di.law:bubing:0.9.12`. Indeed, there are way fewer dependencies on Postgres than it should be. For that package version, there are 3 dependencies in the metadata (i.e. Postgres) using the following SQL query:
```sql
;WITH dep AS (SELECT d.dependency_id, d.version_range from packages pkg, package_versions pkg_v, dependencies d 
 WHERE pkg.id = pkg_v.package_id
 AND d.package_version_id = pkg_v.id
 AND pkg.package_name = 'it.unimi.di.law:bubing'
 AND pkg_v.version = '0.9.12')
 SELECT p.package_name, pv."version" FROM packages p, package_versions pv, dep d WHERE
 p.id = d.dependency_id AND
 pv.package_id =p.id AND
 pv."version" = SUBSTRING(CAST(d.version_range AS TEXT), 2, LENGTH(CAST(d.version_range as TEXT))-2);
```
Looking at the package version's [POM file](https://repo.maven.apache.org/maven2/it/unimi/di/law/bubing/0.9.12/bubing-0.9.12.pom), there are way more direct dependencies.

--------------------------
@vigna, BTW, do you have a SQL query that retrieves direct deps. for a particular package version? Maybe the above SQL query is an invalid way of getting direct deps.

**Comment by mir-am** [comment]
I assume that the new POMAanalyzer should fix this issue. Feel free to re-open the issue if it persists.
