### ISSUE TITLE
Compress JSON callgraph files stored on disk

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#353]
## Is your feature request related to a problem? Please describe.
Every revision and global call graph is stored to a JSON file on disk. While this is a good idea wrt. passing the data to consumers, it does grow the disk footprint of the FASTEN pipeline quite quickly.

## Describe the solution you'd like
Create shared JSON read/write utility methods that transparently compress by default (with flag to disable if needed).

## Additional context
In our deployment the size of the directories containing call graphs is over 50% of the metadata DB size:

- DB: 39 GB
- Java data: 27 GB, of which JSON call graphs: 26 GB

**Comment by mir-am** [comment]
On monster, the total size of JSON call graphs is ~8TB! Also, note that the file system on `/mnt/fasten/` (lima) is compressed using `lz4`.

**Comment by MagielBruntink** [comment]
Wow! Is that 8TB before or after the LZ4 compression?

**Comment by mir-am** [comment]
I used `du -Th` to calculate the total size and I think that is after the LZ4 compression.

**Comment by proksch** [comment]
@MagielBruntink I have no experience with lz4, but I would imagine that the compression is done transparently for the user. Therefore, I would highly expect that the 8TB is the effective size of the content, not the compressed size on disk, but I could be wrong...

Regarding your proposed solution: In the new loader platform the serialization is no longer "automagically" handled, but left to the individual plugin, so whatever requirement we have in any of the plugins, this can now be easily realized locally and does not require a global solution.

I take a note that we will improve this specifically in the `OPALPLugin` once we migrate it. In this concrete case, all consumers of OPAL now need to add one extra call in the code to de-serialize the CG. This also means that all consumers in the pipeline after OPAL that DO NOT need the CG, will be much quicker in the deserialization as the CG is not being serialized/deserialized all the time.

Once concern that I have regarding compressing message contents is that storage on monster will then be rather inefficient, as files will be effectively compressed twice. Should we introduce native compression on a large scale, we should think about changing the file system on said partition.

**Comment by mir-am** [comment]
I want to close this issue. We can address this later. On lima, we have a big storage, which uses `lz4`. In the future, we can think of a solution for compression, which is suitable for running FASTEN's DC on systems with small storage.
