### ISSUE TITLE
JavaCGOpal fails to produce, throws errors only

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#356]
## Describe the bug
After recent changes, the JavaCGOpal container does not create revision call graphs correctly, throwing "scala.MatchError: Seq (of class java.lang.String)".

Surprisingly, all unit tests succeed.

## To Reproduce
1. Clone https://github.com/fasten-project/fasten-docker-deployment
2. `docker-compose --profile java pull`
3. `docker-compose --profile java up -d`
4. `cat test-resources/mvn.coords.txt | docker-compose exec -T kafka kafka-console-producer.sh --broker-list kafka:19092 --topic fasten.mvn.releases --property 'parse.key=true' --property 'key.separator=|'`

## Logs
```
{
   "input": {
      "input": {
         "groupId": "log4j",
         "artifactId": "log4j",
         "version": "1.2.17"
      },
      "plugin_version": "0.1.2",
      "consumed_at": 1638546198,
      "payload": {
         "date": 1338025419000,
         "repoUrl": "http://svn.apache.org/viewvc/logging/log4j/tags/v1_2_17_rc3",
         "groupId": "log4j",
         "version": "1.2.17",
         "parentCoordinate": "",
         "artifactRepository": "https://repo.maven.apache.org/maven2/",
         "forge": "mvn",
         "sourcesUrl": "https://repo.maven.apache.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17-sources.jar",
         "artifactId": "log4j",
         "dependencyData": {
            "dependencyManagement": {
               "dependencies": []
            },
            "dependencies": [
               {
                  "versionConstraints": [
                     {
                        "isUpperHardRequirement": false,
                        "isLowerHardRequirement": false,
                        "upperBound": "1.4.3",
                        "lowerBound": "1.4.3"
                     }
                  ],
                  "groupId": "javax.mail",
                  "scope": "",
                  "classifier": "",
                  "artifactId": "mail",
                  "exclusions": [],
                  "optional": true,
                  "type": ""
               },
               {
                  "versionConstraints": [
                     {
                        "isUpperHardRequirement": false,
                        "isLowerHardRequirement": false,
                        "upperBound": "5.0-2",
                        "lowerBound": "5.0-2"
                     }
                  ],
                  "groupId": "org.apache.openejb",
                  "scope": "provided",
                  "classifier": "",
                  "artifactId": "javaee-api",
                  "exclusions": [],
                  "optional": false,
                  "type": "jar"
               },
               {
                  "versionConstraints": [
                     {
                        "isUpperHardRequirement": false,
                        "isLowerHardRequirement": false,
                        "upperBound": "2.0.8",
                        "lowerBound": "2.0.8"
                     }
                  ],
                  "groupId": "oro",
                  "scope": "test",
                  "classifier": "",
                  "artifactId": "oro",
                  "exclusions": [],
                  "optional": false,
                  "type": ""
               },
               {
                  "versionConstraints": [
                     {
                        "isUpperHardRequirement": false,
                        "isLowerHardRequirement": false,
                        "upperBound": "3.8.2",
                        "lowerBound": "3.8.2"
                     }
                  ],
                  "groupId": "junit",
                  "scope": "test",
                  "classifier": "",
                  "artifactId": "junit",
                  "exclusions": [],
                  "optional": false,
                  "type": ""
               },
               {
                  "versionConstraints": [
                     {
                        "isUpperHardRequirement": false,
                        "isLowerHardRequirement": false,
                        "upperBound": "1.0",
                        "lowerBound": "1.0"
                     }
                  ],
                  "groupId": "org.apache.geronimo.specs",
                  "scope": "",
                  "classifier": "",
                  "artifactId": "geronimo-jms_1.1_spec",
                  "exclusions": [],
                  "optional": true,
                  "type": ""
               }
            ]
         },
         "projectName": "Apache Log4j",
         "commitTag": "",
         "packagingType": "bundle"
      },
      "host": "2df704f8cf99",
      "created_at": 1638546199,
      "plugin_name": "POMAnalyzer"
   },
   "plugin_version": "0.1.2",
   "err": {
      "msg": "scala.MatchError: Seq (of class java.lang.String)",
      "stacktrace": [
         "eu.fasten.analyzer.javacgopal.data.OPALCallGraphConstructor.construct(OPALCallGraphConstructor.java:70)",
         "eu.fasten.analyzer.javacgopal.data.OPALCallGraphConstructor.construct(OPALCallGraphConstructor.java:49)",
         "eu.fasten.analyzer.javacgopal.data.PartialCallGraphConstructor.createExtendedRevisionJavaCallGraph(PartialCallGraphConstructor.java:120)",
         "eu.fasten.analyzer.javacgopal.OPALPlugin$OPAL.consume(OPALPlugin.java:88)",
         "eu.fasten.server.plugins.kafka.FastenKafkaPlugin.lambda$consumeWithTimeout$7(FastenKafkaPlugin.java:556)",
         "java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)",
         "java.base/java.util.concurrent.FutureTask.run(Unknown Source)",
         "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)",
         "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)",
         "java.base/java.lang.Thread.run(Unknown Source)"
      ],
      "error": "OPALException"
   },
   "consumed_at": 1638546199,
   "host": "81a5b1d24388",
   "created_at": 1638546201,
   "plugin_name": "OPAL"
}
```

## Environment (please complete the following information):
 - OS: Linux in Docker
 - Java version: 11

**Comment by proksch** [comment]
Hmm, this is difficult without seeing the details of the OPAL exception... As you will see in the [corresponding code](https://github.com/fasten-project/fasten/blob/develop/analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/OPALCallGraphConstructor.java#L70), the crash happens within OPAL, there is not much logic that we can adopt around it. Also, it is strange that I can actually execute the logic locally, the tests construct CGs for .jar files, so I am not sure what's special in the k8s setting.

@mir-am: Instead of preserving this custom error object in the return, couldn't we just store as a string what would normally be printed on the terminal? This would include nested exceptions, descriptions, etc... right now, we are loosing these details.

**Comment by MagielBruntink** [comment]
It happens in for all artifacts here - not just this example. There must be something going on with the Kafka plugin providing the data to OPAL, or something.

**Comment by proksch** [comment]
I took the liberty to implement the proposed change, see #357. I will try to investigate the OPAL problem over the weekend before my vacation starts.

**Comment by proksch** [comment]
I have no solution yet, but I am starting to understand the problem. OPALs config has changed from v3 to v4. It was necessary to [remove an offending config parameter](https://github.com/fasten-project/fasten/commit/8873ac3cb18c0167ee8688afd9e1d343221133c3#diff-120c3dae34948c3a5e92dfb9d27e7d9420bbafc9219b3d74f62151357efa6a75), `PKECPropertyStore`, from `reference.conf`, which was set to `Seq`. Ultimately, I even decided to [completely removed the whole config file](https://github.com/fasten-project/fasten/commit/e2e479fe95d14b5a23919a2cd9d77ff9daef6648#diff-120c3dae34948c3a5e92dfb9d27e7d9420bbafc9219b3d74f62151357efa6a75), roll with the default settings, and only set a few selected properties when initializing OPAL.

To understand what's going on, I checked the OPAL code and looked up the source of the `MatchError`, it refers to a case distinction of `PKECPropertyStore`, which does not contain an entry for `Seq`. Exactly the problem again that we already saw during the update. As this setting was never in our code and the config does no longer exist in our repo, my working hypothesis right now is that at some point in the packaging pipeline the workspace does not get cleaned, still contains old data like the `reference.conf` and still packages it... where else could this old file come from? I have no other idea.

My problem is that I have not really worked with the build pipeline of the project yet, so I would highly appreciate any pointers or comments/ideas from others... Do we store the .jar files somewhere, so I could inspect the contents, or only the Docker images?

**Comment by proksch** [comment]
It is as expected: I just looked into the .jar files in the running containers... both the `server.jar` and the `javacg-opal.jar` contain a `reference.conf`. This causes the problem. As of now, I still have no idea, where it comes from.

**Comment by proksch** [comment]
My experience with Github Actions is limited, so I am not quite sure what the `setup-java` action does... does it automatically preserve the content in `target` for later actions? Maybe a simple first shot in the dark would be using a `mvn -B clean package --file pom.xml` in our [Maven Action](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/maven.yml#L27).

**Comment by proksch** [comment]
Not sure what to say. xD This should fix the issue.

**Comment by MagielBruntink** [comment]
Sorry to say another issue appeared: https://github.com/fasten-project/fasten/pull/358#pullrequestreview-823689794
