### ISSUE TITLE
Getting NegativeArraySizeException when requesting metadata from RocksDao

### ISSUE THREAD

**Issue by ashkboos** [fasten-project/fasten#361]
While trying to merge a dependency set I get this exception:
``` 
java.lang.NegativeArraySizeException: -1
        at eu.fasten.core.utils.VariableLengthByteCoder.readByteArray(VariableLengthByteCoder.java:202)
        at eu.fasten.core.utils.VariableLengthByteCoder.readString(VariableLengthByteCoder.java:225)
        at eu.fasten.core.data.callableindex.RocksDao.getGraphMetadata(RocksDao.java:452)
        at eu.fasten.core.merge.CGMerger.getGraphMetadata(CGMerger.java:568)
        at eu.fasten.core.merge.CGMerger.createTypeDictionary(CGMerger.java:536)
        at eu.fasten.core.merge.CGMerger.<init>(CGMerger.java:199)
        at eu.fasten.core.merge.Merger.mergeWithDB(Merger.java:194)
        at eu.fasten.core.merge.Merger.run(Merger.java:109)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at eu.fasten.core.merge.Merger.main(Merger.java:88)
```

Based on the documentation of RocksDao class we get RocksDBException if a problem occurs while retrieving data from RocksDB, I think this is a different case. Hence I did not try to catch this exception, or is this expected and should be caught? 

The dependency set that I was trying to stitch was:

` org.apache.sling:org.apache.sling.xss:2.0.6,org.owasp.antisamy:antisamy:1.5.2:provided,net.sourceforge.nekohtml:nekohtml:1.9.16:provided,xerces:xercesImpl:2.9.1:provided,commonshttpclient:commonshttpclient:3.1:provided,commonslogging:commonslogging:1.0.4:provided,commonscodec:commonscodec:1.2:provided,batik:batikcss:1.6:provided,batik:batikext:1.6:provided,batik:batikutil:1.6:provided,batik:batikguiutil:1.6:provided,xmlapis:xmlapisext:1.3.04:provided,org.owasp.esapi:esapi:2.1.0:provided,commonsconfiguration:commonsconfiguration:1.5:provided,commonsdigester:commonsdigester:1.8:provided,commonsbeanutils:commonsbeanutilscore:1.7.0:provided,commonsfileupload:commonsfileupload:1.2:provided,commonscollections:commonscollections:3.2:provided,log4j:log4j:1.2.16:provided,xom:xom:1.2.5:provided,xmlapis:xmlapis:1.3.03:provided,xalan:xalan:2.7.0:provided,org.beanshell:bshcore:2.0b4:provided,org.owasp.encoder:encoder:1.1.1:provided,javax.servlet:javax.servletapi:3.1.0:provided,org.osgi:osgi.core:6.0.0:provided,org.slf4j:slf4japi:1.7.6:provided,org.apache.sling:org.apache.sling.api:2.11.0:provided,org.apache.sling:org.apache.sling.serviceusermapper:1.2.0:provided,com.google.code.findbugs:jsr305:2.0.0:provided,org.apache.geronimo.specs:geronimojson_1.0_spec:1.0alpha1:provided,org.apache.commons:commonslang3:3.6:provided,junit:junit:4.12:test,org.hamcrest:hamcrestcore:1.3:test,org.mockito:mockitoall:1.10.19:test,org.powermock:powermockapimockito:1.6.5:test,org.mockito:mockitocore:1.10.19:test,org.objenesis:objenesis:2.1:test,org.powermock:powermockapimockitocommon:1.6.5:test,org.powermock:powermockapisupport:1.6.5:test,org.powermock:powermockcore:1.6.5:test,org.powermock:powermockreflect:1.6.5:test,org.apache.sling:org.apache.sling.commons.johnzon:1.0.0:test,org.slf4j:slf4jsimple:1.7.6:test,org.apache.sling:org.apache.sling.testing.slingmock:2.2.14:test,org.apache.sling:org.apache.sling.testing.osgimock:2.3.4:test,org.osgi:osgi.cmpn:6.0.0:provided,com.google.guava:guava:15.0:test,org.reflections:reflections:0.9.9:test,org.javassist:javassist:3.18.2GA:test,com.google.code.findbugs:annotations:2.0.1:test,org.apache.sling:org.apache.sling.testing.jcrmock:1.3.2:test,org.apache.jackrabbit:jackrabbitjcrcommons:2.8.0:test,org.apache.sling:org.apache.sling.testing.resourceresolvermock:1.1.20:test,org.apache.sling:org.apache.sling.servlethelpers:1.1.2:test,org.apache.sling:org.apache.sling.commons.osgi:2.4.0:test,org.apache.sling:org.apache.sling.models.api:1.2.2:test,org.apache.sling:org.apache.sling.models.impl:1.2.2:test,org.apache.sling:org.apache.sling.resourceresolver:1.4.8:test,org.apache.sling:org.apache.sling.jcr.api:2.3.0:test,org.apache.sling:org.apache.sling.jcr.resource:2.7.4:test,org.apache.sling:org.apache.sling.scripting.api:2.1.8:test,org.apache.sling:org.apache.sling.scripting.core:2.0.36:test,org.apache.sling:org.apache.sling.commons.mime:2.1.8:test,org.apache.sling:org.apache.sling.jcr.contentparser:1.2.4:test,org.apache.jackrabbit.vault:org.apache.jackrabbit.vault:3.1.18:test,org.apache.johnzon:johnzoncore:1.0.0:test,org.apache.sling:org.apache.sling.commons.classloader:1.3.2:test,org.apache.sling:org.apache.sling.settings:1.3.8:test,org.apache.sling:org.apache.sling.i18n:2.4.4:test,org.apache.sling:org.apache.sling.adapter:2.1.6:test,org.apache.sling:org.apache.sling.resourcebuilder:1.0.2:test,org.apache.jackrabbit:jackrabbitapi:2.11.3:test,commonsio:commonsio:2.4:test,commonslang:commonslang:2.5:provided,commonsbeanutils:commonsbeanutils:1.8.3:provided,org.apache.geronimo.specs:geronimoatinject_1.0_spec:1.0:test,javax.jcr:jcr:2.0:provided,org.osgi:osgi.annotation:6.0.1:provided,org.osgi:org.osgi.service.component.annotations:1.3.0:provided,org.osgi:org.osgi.service.metatype.annotations:1.3.0:provided 
`

**Comment by vigna** [comment]
Can you provide a short class replicating the problem on monster? Thanks!

**Comment by ashkboos** [comment]
> Can you provide a short class replicating the problem on monster? Thanks!

You can checkout to the branch vul_path, build and run the following command:

```
PGPASSWORD=fasten java -cp docker/server/server-0.0.1-SNAPSHOT-with-dependencies.jar eu.fasten.core.merge.Merger -a org.apache.sling:org.apache.sling.xss:2.0.6 -d org.owasp.antisamy:antisamy:1.5.2:provided,net.sourceforge.nekohtml:nekohtml:1.9.16:provided,xerces:xercesImpl:2.9.1:provided,commonshttpclient:commonshttpclient:3.1:provided,commonslogging:commonslogging:1.0.4:provided,commonscodec:commonscodec:1.2:provided,batik:batikcss:1.6:provided,batik:batikext:1.6:provided,batik:batikutil:1.6:provided,batik:batikguiutil:1.6:provided,xmlapis:xmlapisext:1.3.04:provided,org.owasp.esapi:esapi:2.1.0:provided,commonsconfiguration:commonsconfiguration:1.5:provided,commonsdigester:commonsdigester:1.8:provided,commonsbeanutils:commonsbeanutilscore:1.7.0:provided,commonsfileupload:commonsfileupload:1.2:provided,commonscollections:commonscollections:3.2:provided,log4j:log4j:1.2.16:provided,xom:xom:1.2.5:provided,xmlapis:xmlapis:1.3.03:provided,xalan:xalan:2.7.0:provided,org.beanshell:bshcore:2.0b4:provided,org.owasp.encoder:encoder:1.1.1:provided,javax.servlet:javax.servletapi:3.1.0:provided,org.osgi:osgi.core:6.0.0:provided,org.slf4j:slf4japi:1.7.6:provided,org.apache.sling:org.apache.sling.api:2.11.0:provided,org.apache.sling:org.apache.sling.serviceusermapper:1.2.0:provided,com.google.code.findbugs:jsr305:2.0.0:provided,org.apache.geronimo.specs:geronimojson_1.0_spec:1.0alpha1:provided,org.apache.commons:commonslang3:3.6:provided,junit:junit:4.12:test,org.hamcrest:hamcrestcore:1.3:test,org.mockito:mockitoall:1.10.19:test,org.powermock:powermockapimockito:1.6.5:test,org.mockito:mockitocore:1.10.19:test,org.objenesis:objenesis:2.1:test,org.powermock:powermockapimockitocommon:1.6.5:test,org.powermock:powermockapisupport:1.6.5:test,org.powermock:powermockcore:1.6.5:test,org.powermock:powermockreflect:1.6.5:test,org.apache.sling:org.apache.sling.commons.johnzon:1.0.0:test,org.slf4j:slf4jsimple:1.7.6:test,org.apache.sling:org.apache.sling.testing.slingmock:2.2.14:test,org.apache.sling:org.apache.sling.testing.osgimock:2.3.4:test,org.osgi:osgi.cmpn:6.0.0:provided,com.google.guava:guava:15.0:test,org.reflections:reflections:0.9.9:test,org.javassist:javassist:3.18.2GA:test,com.google.code.findbugs:annotations:2.0.1:test,org.apache.sling:org.apache.sling.testing.jcrmock:1.3.2:test,org.apache.jackrabbit:jackrabbitjcrcommons:2.8.0:test,org.apache.sling:org.apache.sling.testing.resourceresolvermock:1.1.20:test,org.apache.sling:org.apache.sling.servlethelpers:1.1.2:test,org.apache.sling:org.apache.sling.commons.osgi:2.4.0:test,org.apache.sling:org.apache.sling.models.api:1.2.2:test,org.apache.sling:org.apache.sling.models.impl:1.2.2:test,org.apache.sling:org.apache.sling.resourceresolver:1.4.8:test,org.apache.sling:org.apache.sling.jcr.api:2.3.0:test,org.apache.sling:org.apache.sling.jcr.resource:2.7.4:test,org.apache.sling:org.apache.sling.scripting.api:2.1.8:test,org.apache.sling:org.apache.sling.scripting.core:2.0.36:test,org.apache.sling:org.apache.sling.commons.mime:2.1.8:test,org.apache.sling:org.apache.sling.jcr.contentparser:1.2.4:test,org.apache.jackrabbit.vault:org.apache.jackrabbit.vault:3.1.18:test,org.apache.johnzon:johnzoncore:1.0.0:test,org.apache.sling:org.apache.sling.commons.classloader:1.3.2:test,org.apache.sling:org.apache.sling.settings:1.3.8:test,org.apache.sling:org.apache.sling.i18n:2.4.4:test,org.apache.sling:org.apache.sling.adapter:2.1.6:test,org.apache.sling:org.apache.sling.resourcebuilder:1.0.2:test,org.apache.jackrabbit:jackrabbitapi:2.11.3:test,commonsio:commonsio:2.4:test,commonslang:commonslang:2.5:provided,commonsbeanutils:commonsbeanutils:1.8.3:provided,org.apache.geronimo.specs:geronimoatinject_1.0_spec:1.0:test,javax.jcr:jcr:2.0:provided,org.osgi:osgi.annotation:6.0.1:provided,org.osgi:org.osgi.service.component.annotations:1.3.0:provided,org.osgi:org.osgi.service.metatype.annotations:1.3.0:provided -gd /mnt/fasten/callable-index -du fastenro -md "jdbc:postgresql://172.16.45.119/fasten_java" -m DATABASE -o /home/ashkboos/fasten/cg
```

**Comment by vigna** [comment]
The graph for id 4674 and the metadata contain incompatible data. The graph has 1819 nodes, but the metadata contains only 1782 items. The loop writing the metadata items uses an iterator on the graph nodes, so that's alarming.

The first thing we have to ascertain is whether it is possible that metadata has been written separately from the graph data, maybe during the database repopulation (remember that there were many graphs without metadata). If somehow metadata has been written without the associated graph data being rewritten, that might be the cause of the problem, as a different version of the software computing the call graph might have generated a different call graph.

I do not think that RocksDB keeps timestamps of each write, so we cannot possibly know whether the graph for id 4674 and its metadata has been written in different moments. If this is the case, we have to remove both items and recompute them from scratch. That's the first step to be sure that the problem is in the read/write code.

Can someone at TU Delft take care of that?

**Comment by ashkboos** [comment]
I doubt that it is caused by multiple runs. In the callable-index folder, we only ran one version of our program. So it should not result in different outputs. However, it is worth investigating how this package version 4674 was handled by the callable-index plugin to make sure this is caused by read/write code. We will look into logs related to this id.

We were planning to do some refactorings/improvements on the callable-index plugin in one of our upcoming Monday sessions within TUD. This week I will suggest that we look into this.

I also have one suggestion for improvement. Let me know what do you think about this:
Within the callable-index plugin, we make sure we insert both metadata and graph of a package version successfully and the number of their records match otherwise we fail without inserting anything to the RocksDB. This way we guarantee all package versions in the RocksDB have consistent metadata and graph. Then we can also debug the records that end up in the error topic and rerun the plugin only for them after possible fixes.

**Comment by vigna** [comment]
Yes, that was in fact my second hypothesis: during an update there has been a crash so only the new graph has been written. Something like this should be visible from the log. If we cannot find any evidence, we need a way to run repeatedly the saving of that graph so we can identify where is the problem. 

But it is a fact that the code might leave the database in an inconsistent state. At that time there were other far more urgent problems. I'll look into RocksDB transactions, it might be the case that it is easy to force atomicity.

**Comment by mir-am** [comment]
How does `CallableIndexer` deal with duplicate records? i.e. What does `CallableIndexer` do if a graph is already inserted?
I attribute inconsistent metadata to (1) multiple runs (2) inconsistent data in the pipeline.

**Comment by mir-am** [comment]
Sorry, I was referring to `CallableIndexFastenPlugin` here:
https://github.com/fasten-project/fasten/blob/eb191803e6b8b2aa889075c9fb8cd2022c21847e/analyzer/callable-index/src/main/java/eu/fasten/analyzer/callableindex/CallableIndexServerPlugin.java#L51

**Comment by vigna** [comment]
OK, but I never wrote a single line of that file. You can use `git blame` to find the authors if you need to ask. `RocksDao` (which is the underlying mechanism) will just write data into RocksDB, overwriting previous data. Since everything we are analyzing is immutable, that is in theory a good idea. However, this also assumes that the Postgres database associates bijectively revisions with ids in an immutable manner. I do not know if we have this guarantee (in particular with all the restarts of the pipeline).

**Comment by vigna** [comment]
BTW, do the logs show anything anomalous about the revision with id 4674?

**Comment by ashkboos** [comment]
Unfortunately, there was no log for that artifact. We looked into the ExtendedGID file of that package version and it was correct so now we are trying to debug the insertion code to see what goes wrong.

**Comment by vigna** [comment]
But we would be happy to debug it ourselves, given a way to trigger the code...

**Comment by vigna** [comment]
Has there been any progress on this? We are getting this exception when retrieving data from the callable index.

**Comment by ashkboos** [comment]
> Has there been any progress on this? We are getting this exception when retrieving data from the callable index.

Not much progress but there is some news. 
After spending some time using callable-index for finding vulnerable paths we decided to first go for the local merging to 1) make sure that it works end-to-end 2) have some kind of baseline for callable-index. Fortunately, this worked and we managed to produce some results. 
On another note, we discussed here the transaction idea and concluded that it might be useful to use something like this in RocksDao class: https://stackoverflow.com/questions/67831858/rocksdb-java-api-support-for-transactions
As for debugging, didn't this command https://github.com/fasten-project/fasten/issues/361#issuecomment-988588170 help? Please let me know what extra information is needed.

**Comment by vigna** [comment]
I identified the defect: commit 7e87c0af660ec92542c2b830878b12059c2586e3 removed the only reference to ExtendedGidGraph from the plugin building the callable index. RocksDao will save metadata only if the argument to saveToRocksDB is an ExtendedGidGraph. Thus, since code posterior to that commit went into production no metadata has ever been saved. 

New graphs sometimes are however written and thus associated to old metadata already in the database. Indeed, by adding a check to RocksDao, I was able to locate a large number of metadata objects that are too _long_, instead of too _short_ (like the one associated with this issue).

At this point it is necessary to rebuild the callable index from scratch—the data stored therein is a complete mess. It is necessary to reinstate the generation of an ExtendedGidGraph in CallableIndexServerPlugin, and then rebuild.

**Comment by mir-am** [comment]
> I identified the defect: commit [7e87c0a](https://github.com/fasten-project/fasten/commit/7e87c0af660ec92542c2b830878b12059c2586e3) removed the only reference to ExtendedGidGraph from the plugin building the callable index. RocksDao will save metadata only if the argument to saveToRocksDB is an ExtendedGidGraph. Thus, since code posterior to that commit went into production no metadata has ever been saved.
> 
> New graphs sometimes are however written and thus associated to old metadata already in the database. Indeed, by adding a check to RocksDao, I was able to locate a large number of metadata objects that are too _long_, instead of too _short_ (like the one associated with this issue).
> 
> At this point it is necessary to rebuild the callable index from scratch—the data stored therein is a complete mess. It is necessary to reinstate the generation of an ExtendedGidGraph in CallableIndexServerPlugin, and then rebuild.

We indeed need to rebuild the callable index. Its current deployment is 2 months old on monster and it doesn't contain recent commits like 7e87c0a.

**Comment by vigna** [comment]
That is a defect that certainly must be fixed (I installed the dockerized version and I checked: no metadata is ever saved by the pipeline in the callable index).

But If that code is not in production, then there must be another explanation as to why some metadata is longer than needed, and some is shorter than needed, and it must be isolated. Are you absolutely sure that the current code building the callable index does not contain those commits?

**Comment by vigna** [comment]
@mir-am otherwise, is it possible to know which commit has been running through December and January on monster? I can use the dockerize setup to replicate the same codebase and see whether the exception is thrown or not.

**Comment by mir-am** [comment]
@vigna 
Sorry for the late update. Mehdi and I fixed the metadata issue in #385 by using `ExtendedGidGraph` in the code. Now, the metadata is saved for every graph node as expected. We also tested the fix in the Docker compose.
We need to re-run the callableIndexer with this fix again.

**Comment by vigna** [comment]
OK. Did you test with junit 4.12? That was the artifact unleashing the bug. But you need to read the data back with getGraphMetadata().

Please be sure to restart from a completely empty callable index or we will run into this again (given that my diagnosis is correct).

**Comment by mir-am** [comment]
> OK. Did you test with junit 4.12? That was the artifact unleashing the bug. But you need to read the data back with getGraphMetadata().
> 
> Please be sure to restart from a completely empty callable index or we will run into this again (given that my diagnosis is correct).

Yes, we tested it with `junit:4.12` and used `getGraphMetadata`.

**Comment by vigna** [comment]
OK, then it is not our code. Good!
