### ISSUE TITLE
 MetaDataPlugin cannot be executed as a standalone tool

### ISSUE THREAD

**Issue by gdrosos** [fasten-project/fasten#366]
## Describe the bug
According to MetadataDB Plugin's [documentation](https://github.com/fasten-project/fasten/blob/develop/analyzer/metadata-plugin/README.md#usage), apart of being executed as part of the fasten server,  the plugin can be used as a standalone tool. After succesfully building the jar file, I try to execute it but a```java.lang.NoClassDefFoundError``` is triggered. This is caused when there is a class file that the code depends on and it is present at compile time but not found at runtime. (In our example the eu/fasten/core/plugins/KafkaPlugin)

## To Reproduce
1. ```cd fasten```
2.  ```mvn clean install```
3.  ```java -cp docker/plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar  eu.fasten.analyzer.metadataplugin.Main -h ```

## Expected behavior
The jar file should be succesfully executed and the Plugin help message should be shown

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).
```
Error: Unable to initialize main class eu.fasten.analyzer.metadataplugin.Main
Caused by: java.lang.NoClassDefFoundError: eu/fasten/core/plugins/KafkaPlugin
```

## Environment (please complete the following information):
 - OS: Linux
 - Java version: 11

**Comment by ashkboos** [comment]
Strangely, there some core packages are there but the plugin package is not! @mir-am Do you have any idea how this could happen?

**Comment by mir-am** [comment]
This issue stems from the fact that plug-ins interfaces, i.e., `KafkaPlugin` are excluded. 
See this
https://github.com/fasten-project/fasten/blob/f148c3a3bee8199f28a099ad2fe595c66fa4d061/analyzer/metadata-plugin/pom.xml#L118
The main class seems to use the plug-in class, which depends on the interfaces. If you implement the plug-in's main logic in another class like the OPAL plug-in, then you can use the Main class.  That said, I don't recommend changing the metadata plug-in. Instead, use the FASTEN server and create a dummy input Kafka topic for testing. Or use the Docker compose deployment. You can borrow some CGs from the main Kafka topics and create a dummy input topic for testing.
