### ISSUE TITLE
javacg-opal: mvn install has test failures on Windows 10

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#38]
JAVA_HOME is set c:/Program Files/OpenJDK/openjdk-11.0.7_10

Please see trace attached.
[trace.txt](https://github.com/fasten-project/fasten/files/4937010/trace.txt)

**Comment by ilyagrishkov** [comment]
We have updated OPAL plugin and also created new tests for it. Could you run `mvn install` once again to see if it works now?

**Comment by MagielBruntink** [comment]
This issue is caused by the MavenResolver, which in its current implementation uses Linux tools (eg. bash, grep, awk, sed, uniq, sort) to process Maven's output. See code [here](https://github.com/fasten-project/fasten/blob/0c829ec7f1fdb021b687224287a137f47ff83a85/core/src/main/java/eu/fasten/core/maven/MavenResolver.java#L281).  A better solution would be to use the [Maven Invoker](http://maven.apache.org/shared/maven-invoker/usage.html) and Java string processing to get a more platform independent implementation.

**Comment by proksch** [comment]
The issue is obsolete. Also, since Windows is part of our build matrix, we will be able to detect problems like this in the future.
