### ISSUE TITLE
GraphMavenResolver.buildDependencyGraph() throws a NoSuchMethodError

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#412]
In the develop branch, try

```
java -Xmx16G eu.fasten.core.search.SearchEngine jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/callable-index/ foobar.graph
```
One obtains

```
Exception in thread "main" java.lang.NoSuchMethodError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:575)
        at eu.fasten.core.maven.DependencyGraphBuilder.getDependencyList(DependencyGraphBuilder.java:133)
        at eu.fasten.core.maven.DependencyGraphBuilder.buildDependencyGraph(DependencyGraphBuilder.java:195)
        at eu.fasten.core.maven.utils.DependencyGraphUtilities.buildDependencyGraphFromScratch(DependencyGraphUtilities.java:191)
        at eu.fasten.core.maven.GraphMavenResolver.buildDependencyGraph(GraphMavenResolver.java:535)
        at eu.fasten.core.search.SearchEngine.<init>(SearchEngine.java:212)
        at eu.fasten.core.search.SearchEngine.<init>(SearchEngine.java:193)
        at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:703)
Caused by: java.lang.NoSuchMethodError: 'void org.json.JSONArray.forEach(java.util.function.Consumer)'
        at eu.fasten.core.maven.data.Dependency.fromJSON(Dependency.java:216)
        at eu.fasten.core.maven.DependencyGraphBuilder.lambda$getDependencyList$0(DependencyGraphBuilder.java:126)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

The same code was working a few weeks ago. We don't know if you are using wrong parameters, in view of the recent flood of improvements to the codebase. Please let us know if we can do more to solve the problem.

**Comment by mir-am** [comment]
Stupid question! How did you run the above-mentioned command on monster? We've tried to run it in the core module and it gives `ClassnotFoundException`.

**Comment by mir-am** [comment]
@vigna
We have built the project with the latest commits from `develop` on `monster` and run the following command:
```
java -cp server/server-0.0.1-SNAPSHOT-with-dependencies.jar eu.fasten.core.search.SearchEngine jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/callable-index/ foobar.graph
```
It builds the dependency graph and shows `[$help for help]>`.

**Comment by vigna** [comment]
We run it from core (we put target/classes in the classpath), but it does not run from server either. But if you cannot reproduce it I suspect some weird classpath problem in our setting at this point. I'll see what I can dig...

**Comment by vigna** [comment]
OK sorry, no, it's a jar with dependencies.

So, assuming I'm in develop, and in ~/fasten/server, can you give me compilation and run instructions that work for you? If I compile server with 

```
mvn clean install -DskipTests=True -Dmaven.javadoc.skip=true
```

your command gives me ClassNotFoundException.

**Comment by vigna** [comment]
And, I'm doing all this with an empty classpath.

**Comment by vigna** [comment]
More in general, we have a setup that worked for 38 months: compiling core, downloading the dependency jar and running classes using target/classes. We do

```
mvn dependency:copy-dependencies -DoutputDirectory=jars
export CLASSPATH=$(find $(pwd)/jars | paste -d: -s):$(pwd)/target/classes:$CLASSPATH
```

and then compile and run.

This setup stopped working in the last two weeks, so something has radically changed. How can we modify the setup according to these changes?

**Comment by mir-am** [comment]
> OK sorry, no, it's a jar with dependencies.
> 
> So, assuming I'm in develop, and in ~/fasten/server, can you give me compilation and run instructions that work for you? If I compile server with
> 
> ```
> mvn clean install -DskipTests=True -Dmaven.javadoc.skip=true
> ```
> 
> your command gives me ClassNotFoundException.

Here are the commands that we use to run the search engine module.
Run these in the root of the project on monster (on `develop`):
```
git pull && mvn clean install -DskipTests
```

Then, run this at `fasten/docker/server`:
```
java -cp server-0.0.1-SNAPSHOT-with-dependencies.jar eu.fasten.core.search.SearchEngine jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/callable-index/ foobar.graph
```

**Comment by vigna** [comment]
OK. Now this docker directory enters the picture. Nice. I was able to run.

So, what did change? How can we run core without building the whole project? Rebuilding the whole project while developing is not viable path.

**Comment by mir-am** [comment]
> OK. Now this docker directory enters the picture. Nice. I was able to run.
> 
> So, what did change? How can we run core without building the whole project? Rebuilding the whole project while developing is not viable path.

Unfortunately, I do not know a better way to do that.

**Comment by vigna** [comment]
@proksch , any comment?

**Comment by proksch** [comment]
Sorry that I was not able to look into this sooner. I take from the recent comments that the issue was caused by a change in the startup, but that this could be solved now.

I understand your frustration with the build time. If you want to get rid of the waiting time for building the whole project all the time, I would suggest to move the search engine out of core into a separate project (it is a bit weird to have a main method in the middle of a utility jar anyways)... as long as you either `mvn install` the complete project once into your local .m2 folder or just depend on the stable version that is now released in the GitHub Maven registry, you can just depend on the core project and do not have to re-build everything all the time.

**Comment by proksch** [comment]
I start to take offense by your constant accusations. Of course I read your posts and I tried to react to them. This issue started with a report of `NoSuchMethodError` and some answers ago you said that

> OK. Now this docker directory enters the picture. Nice. I was able to run.

To me, your answers suggest a startup issue (that you seem to have resolved through @mir-am commits) and you are raising a question about how to avoid the inconvenience of the build time, which I addressed. Now you say that this is not the issue that you want to report. Based on your follow-up explanation this thread seems to have morphed into a duplicate of #413 (or vice versa).

**Comment by vigna** [comment]
I really apologize if those sounded like accusations. I just could not understand what you were suggesting to do because it did not seem related to our problem.

I'll try to explain again from scratch—probably my first report was written in a hurry and so it was not very clear. A posteriori, using a test class that was not the problematic class certainly did not help clarity.

We're just trying to make GraphMavenResolver work again without building the whole project, but rather compiling just core, as we did since we started using it. Presently, using GraphMavenResolver when compiling from core throws the exceptions above. It was not throwing those exceptions before the refactoring that happened in the last few weeks.

So your comments do not address our problem, as moving our code out of core will not make GraphMavenResolver work.

Our problem remains thus unsolved: if you compile just core, running GraphMavenResolver without a pre-built resolver graph causes exceptions during the call to DependencyGraphUtilities.buildDependencyGraphFromScratch().

Presently, the only workaround is to compile the whole project and run it from the server jar as suggested by Amir.

It would be easier for us if GraphMavenResolver would work again when compiling it from core, as it has been doing throughout the project.

Note that issue #413 has no connection with the problem reported here. This issue looks more like a classpath problem.

**Comment by proksch** [comment]
I am a bit lost... I think I managed to start the search engine using the instructions above and by executing `FASTEN_DBPASS="XXX" java -cp server-0.0.3-SNAPSHOT-with-dependencies.jar eu.fasten.core.search.SearchEngine jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/data/callable-index/ foobar.graph` in the `fasten/docker/server` folder. At least I think that it is working, as I see the `[$help for help]` prompt as well.

Which command do I need to execute now to run something, so I can see the error?

**Comment by proksch** [comment]
As already said in the other thread, I was able to run a [minimal example](https://gist.github.com/proksch/f5be87227aab45906a0912c63fde7551) and I did not run into any kind of dependency issues. One change that I have introduced is that I have excluded an outdated transitive dependency of `json-assert` that has conflicted with `org.json`. Instead, the more recent `org.json` dependency is now used that we have in the project anyways.

Thinking about it and knowing about your workflow now, I believe that the issue has been caused by how you are executing the class. You are essentially "exporting" the project out of Maven by compiling all dependencies in a folder and essentially running plain Java there. Normally, dependency resolution is affected by the order in which jars are declared, which correlates with the declaration order in the pom file... when you now just copy everything together into one folder and simply use all jars to fill the classpath, I would expect that the jars are ordered by name, which is different to the Maven build. In the concrete case, the same class (`org.json.JSONArray`) has been declared multiple times, so declaration order has mattered... at least I assume so, as it would explain the two weird phenomena: 1) The offending dependency that I have excluded happens to start with "android" and, alphabetically, is the first dependency in the list. 2) It explains why a test dependency suddenly shows up during runtime, which in Maven-land does not make sense.

It might be a good idea for you to move the search engine into a dedicated Maven project that you either create as a dedicated "PF4J plugin", move to the new loader platform, or at least configure in a way so you can bundle it and start it as a jar.

**Comment by vigna** [comment]
The minimal example you are running won't show the problem because you are using the server jar with dependencies; that's the workaround we are using now.

The command of the search engine is needed for the other bug—the one caused by the `equals()` implementation and the version problem. It is not useful to reproduce this problem—the exception is thrown well before any command is issued.

Your last analysis I think is correct—as I said before this looks like a classpath problem—and it fact the fix works.

Our setup might be not entirely Maven-friendly, but it has worked flawlessly for three years and makes it possible to use locally Eclipse's incremental compiler in debugging and optimizing sessions. The fact that the same class appears in several dependencies in incompatible versions looks like a source of future problems to me, but I do not have a clear understanding of all dependencies throughout the project, so I'll take your word that  that's the way to do it.

Anyway: thank you for locating this. Removing the dependency makes GraphMavenResolver work again from core, and removing a jar is definitely easier than recompile the whole project!

**Comment by proksch** [comment]
Just for the record, I did not execute the jar with dependencies... I was executing the minimal example directly from within the IDE (right click, run as Java application...).

Great to hear that it is working for you now!

**Comment by vigna** [comment]
Yeah, sorry, that got mixed up. I meant, the search engine.
