### ISSUE TITLE
GraphMavenResolver throws an exception on revisions in the database

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#413]
We are trying to use GraphMavenResolver on revisions that are actually in the Postgres database, such as `commons-lang3` version 3.2.

```
 10487 |        156 | 3.2          | OPAL         |                     34 |              | 2013-12-28 17:06:34 | {"forge": "mvn", "groupId": "org.apache.commons", "repoUrl": "scm:svn:http://svn.apache.org/repos/asf/commons/proper/lang/trunk", "version": "3.2", "commitTag": "HEAD", "artifactId": "commons-lang3", "sourcesUrl": "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.2/commons-lang3-3.2-sources.jar", "projectName": "Apache Commons Lang", "releaseDate": 1388250394000, "dependencies": [{"id": 0, "type": "jar", "scope": "test", "groupId": "org.easymock", "optional": false, "artifactId": "easymock", "classifier": "", "exclusions": [], "versionConstraints": ["3.2"]}, {"id": 0, "type": "jar", "scope": "test", "groupId": "junit", "optional": false, "artifactId": "junit", "classifier": "", "exclusions": [], "versionConstraints": ["4.11"]}, {"id": 0, "type": "jar", "scope": "test", "groupId": "commons-io", "optional": false, "artifactId": "commons-io", "classifier": "", "exclusions": [], "versionConstraints": ["2.4"]}], "packagingType": "jar", "parentCoordinate": "org.apache.commons:commons-parent:pom:32", "artifactRepository": "https://repo1.maven.org/maven2/", "dependencyManagement": []}                   |    156 | org.apache.
```

Since the knowledge base contains a very small portion of Maven, the only way to run a search on a stored artifact has always been to look up in Postgres an revision actually stored.

However, running SearchEngine this is what we get:

```
[$help for help]>-fasten://org.apache.commons:commons-lang3$3.2
java.lang.RuntimeException: Revision org.apache.commons:commons-lang3:3.2 is not in the dependents graph. Probably it is missing in the database
        at eu.fasten.core.maven.GraphMavenResolver.dependentBFS(GraphMavenResolver.java:372)
        at eu.fasten.core.maven.GraphMavenResolver.resolveDependents(GraphMavenResolver.java:348)
        at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:602)
        at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:578)
        at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:563)
        at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:736)
```

However, as explained above, the graph is in the database. The resolver graph we generated following Amir's instruction contains the same number of nodes as the size of the package_revisions table of the Postgres database, so that seems to be correct.

Note that the callable index contains >700000 entries, so an order of magnitude more than those in Postgres. Also these two pieces of data are difficult to match. How is that possible?

**Comment by mir-am** [comment]
I am not sure whether I mention this before. The new callable indexer is stored at `/mnt/fasten/data/callable-indexer/`. You used the previous one.
Could you please run the search engine again with the new path? 
To avoid confusion, we want to delete the previous callable indexer at `/mnt/fasten/callable-indexer/` if you are okay with it.

**Comment by vigna** [comment]
Yes, if you change continuously paths deleting the old databases is definitely a good idea.

**Comment by vigna** [comment]
I mean, /mnt/graphdb, /mnt/fasten/graphdb, etc. I don't know which are meaningful. Some have modification dates of years ago.

**Comment by vigna** [comment]
OK, the new database has a number of items comparable with Postgres. That is one fix towards usability. Hurray!

**Comment by mir-am** [comment]
> 



> I mean, /mnt/graphdb, /mnt/fasten/graphdb, etc. I don't know which are meaningful. Some have modification dates of years ago.

The only valid path for callable-indexer is at `/mnt/fasten/data/callable-indexer/`.
I will delete the other previous path to stay consistent.

**Comment by vigna** [comment]
OK, located.

@proksch made a mistake in commit 73adb300b (or at least git blames him for implementing the `equals()` method of `MavenProduct`).

GraphMavenResolver relies on Revision instances to be equal() if they represent the same artifact. By using `EqualsBuilder` to build an `equals()` method, beside checking that `groupId` and `artifactId` are the same (which is good) the code is checking _also_ `id` equality. This does not make any sense, because then `GraphMavenResolver` at line 274 will always receive the return value `false`—the id of the Revision instances in the graph are all nonzero, and the query is made with a Revision object that has id equal to zero.

The second mistake is more difficult to track but triggers the same problem. If I print the version field of a `Revision` node of the graph returned by GraphMavenResolver, I get
```
bsh % print(w.version)
;
2.0
```

However, if I do the same with a `Revision` as the one used at line 274 of `GraphMavenResolver`, I get
```
bsh % print(v.version)

2.0
```

So the problem lies not only in equality of `MavenProduct`, but also somewhere in the handling of the revision string.

Presently, we cannot proceed any further. `GraphMavenResolver` just returns "not in the database" for any revision.

**Comment by proksch** [comment]
I think we have a different understanding of the contract of an equals method. ;) It might be that it does not do what you want it to do, but it seems that the object equality should consider the id. In any way, I did not realize that any of my changes had a  side effect that altered the behavior of the resolver, the tests are all running fine.

I started looking into the `GraphMavenResolver`, as I strongly feel that this 620 LoC beast needs to be revised and I would also like to incrementalize it to make it more usable by the REST API. Technically, I only started reading about it, as the Maven resolution strategies are not simple, but it is the next thing that I will touch... If you have any further insights into the responsibilities of the different classes in the `eu.fasten.core.maven` package, please help me out (like what is the difference between `MavenResolver` and `GraphMavenResolver`? Why is there a benchmark? And why do we have executables everywhere in the core package?).

I am trying to follow your instructions, but the `GraphMavenResolver` does only [perform a contains checks](https://github.com/fasten-project/fasten/blob/develop/core/src/main/java/eu/fasten/core/maven/GraphMavenResolver.java#L274) of `Revision` in Line 74, but I did not touch `Revision` and the `version` that you point out is actually a Maven class. I guess I need to understand where the version comes from. As of now, I have no idea where in a Maven coordinate a semicolon could originate come from.

**Comment by vigna** [comment]
> On 1 Mar 2022, at 01:31, Sebastian Proksch ***@***.***> wrote:
> 
> 
> I think we have a different understanding of the contract of an equals method. ;) It might be that it does not do what you want it to do, but it seems that the object equality should consider the id. In any way, I did not realize that any of my changes had a side effect that altered the behavior of the resolver, the tests are all running fine.

GraphMavenResolver stopped working again--that's our concern now. I tracked the defect at the root of the problem for you guys--a "thank" would be appreciated. :)

> I started looking into the GraphMavenResolver, as I strongly feel that this 620 LoC beast needs to be revised and I would also like to incrementalize it to make it more usable by the REST API. Technically, I only started reading about it, as the Maven resolution strategies are not simple, but it is the next thing that I will touch... If you have any further insights into the responsibilities of the different classes in the eu.fasten.core.maven package, please help me out (like what is the difference between MavenResolver and GraphMavenResolver? Why is there a benchmark? And why do we have executables everywhere in the core package?).

That is not my code, so frankly I can't help you. I use GraphMavenResolver because the wiki documentation you guys wrote says so.

> I am trying to follow your instructions, but the GraphMavenResolver does only perform a contains checks of Revision in Line 74, but I did not touch Revision and the version that you point out is actually a Maven class. I guess I need to understand where the version comes from. As of now, I have no idea where in a Maven coordinate a semicolon could originate come from.

Revision extends MavenProduct. You implemented equals() in MavenProduct in the commit included in the report. You replaced a method that did not compare id with a method that compares id. This is very clearly explained in the report, and very visible in the commit. It might be a better equals() method, but it is incompatible with GraphMavenResolver's code, which requires the old equals() method.

For the version part, as I explained in the meeting, my suspicion is that something has changed in the pipeline through which artifacts land in the serialized graph generated by GraphMavenResolver. I don't know in which point of the pipeline, but somewhere in the way the version is passed, or parsed, has been changed and now there's spurious data in the state of the Apache class used for versions. Refactorings happened everywhere, so I hope this rings a bell in someone's mind...

Ciao,

					seba

**Comment by proksch** [comment]
No need to freak out about it, this was an honest mistake and has been directly fixed. As soon as you review and accept the PR, you get the old behavior back.

Just to point out the obvious, the GraphResolver is also not my code. So thank you for helping me to help you. I would suggest that instead of blaming each other we should maybe start trying to solve this together... seems like a more constructive and goal-oriented approach to me.

**Comment by vigna** [comment]
> On 1 Mar 2022, at 03:34, Sebastian Proksch ***@***.***> wrote:
> 
> Just to point out the obvious, the GraphResolver is also not my code. So thank you for helping me to help you. I would suggest that instead of blaming each other we should maybe start trying to solve this together... seems like a more constructive and goal-oriented approach to me.
> 

We must have a very different idea of what "constructive" and "goal-oriented" is, because I see few things more constructive and goal-oriented than chasing and finding your bugs 😂.

Ciao,

					seba

**Comment by proksch** [comment]
I do appreciate the effort that you put into this, but you might not realize the effect that the tone of your communication has on the recipient. I am doing my best to improve the code base and go an extra mile in the past months to stabilize and improve what we have. Most changes have been motivated by several of your request, but I do not feel that these efforts are appreciated or even recognized. On the contrary, you rub every small mistake in my face. Yes, when there are changes (especially when they are at the scale of what we did in the last weeks), sometimes things might break and I am sorry that it affected the part of the project that you rely on. I am happy to work on the `GraphMavenResolver` to get things fixed, but the feeling of being on defense trial here has dampened my motivation big time.

**Comment by vigna** [comment]
I really appreciate that you want to consolidate the code, and I thank you for putting personal effort to this end. I also fully understand that when you make a lot of refactoring some bugs are going, unavoidably, to slip in.

But please try for a second to see things from our side: the end of the project is in a very short time and having basic classes such as GraphMavenResolver suddenly not working is a very, very big problem for us. 

It is very frustrating for us because first the callable-index data-corruption bug (which required rebuilding again from scratch the callable index) and then this new problem have made our progress very difficult.

We would like to have a minimum of freedom in organizing our time in the last months of the project, but this freedom will be reduced to nothing if we cannot work properly on our work package soon.

So thank you in advance for any help! Let's focus on the technical part. I'll do my best to avoid the blame game in the future, I promise.

**Comment by proksch** [comment]
I am very aware of the effect that the state of the pipeline has on the partners and I am truly sorry that you are in this position, just because you sit "at the end of the pipeline". Let's try to get this fixed as soon as possible!

**Comment by proksch** [comment]
I still find the usage of all `DependencyGraphBuilder` related classes highly confusing and will first try to figure out how to run this whole construct locally now before I continue with debugging this on the server. Given that you are the only one that has used this functionality so far, do you have any other information that you can share about the process/usage that goes beyond [what's in the Wiki](https://github.com/fasten-project/fasten/wiki/Resolution-and-Stitching)?

**Comment by proksch** [comment]
Small update: running the coordinate locally using the snippet from the wiki, I get a bit more context to the error:

    DEBUG eu.fasten.core.maven.GraphMavenResolver - BFS from root: org.apache.commons:commons-parent:pom
    WARN eu.fasten.core.maven.GraphMavenResolver - Parent for revision org.apache.commons:commons-lang3:3.3.2 not found: Revision org.apache.commons:commons-parent:pom is not in the dependency graph. Probably it is missing in the database
    DEBUG eu.fasten.core.maven.GraphMavenResolver - BFS from root: org.apache.commons:commons-lang3:3.3.2

I 'll have to dig deeper into how the parent poms play into this... I am actually surprised that these are expected to be in the graph, as all information that could be taken out of them is already included in the `PomAnalysisResult`, which is extracted from the *effective* POM (= the union of the POM with all of its parents). Maybe that is the difference to before that is causing the issue now.

**Comment by proksch** [comment]
I was able to run the MavenGraphResolver in a [minimal example](https://gist.github.com/proksch/f5be87227aab45906a0912c63fde7551) for `commons-lang3`. There is still testing/refactoring to be done, but these changes should fix the immediate issue.

**Comment by vigna** [comment]
> I still find the usage of all `DependencyGraphBuilder` related classes highly confusing and will first try to figure out how to run this whole construct locally now before I continue with debugging this on the server. Given that you are the only one that has used this functionality so far, do you have any other information that you can share about the process/usage that goes beyond [what's in the Wiki](https://github.com/fasten-project/fasten/wiki/Resolution-and-Stitching)?

Mmmhhh... nothing in particular. I totally agree that the usage is very confusing.

**Comment by vigna** [comment]
> I was able to run the MavenGraphResolver in a [minimal example](https://gist.github.com/proksch/f5be87227aab45906a0912c63fde7551) for `commons-lang3`. There is still testing/refactoring to be done, but these changes should fix the immediate issue.

Unfortunately you're testing with a revision that does not reproduce the problem. You should try with revision 3.2. It is in the resolver graph, but it won't be found. Here:

http://vigna.di.unimi.it/MavenGraphResolverRunner.java

you can find a modified version that will print the available versions of commons-lang3, and show that GraphMavenResolver cannot retrieve 3.2, even if it is available.

However, I still see the `equals()` method of MavenProduct comparing `id`. I somehow understood you had fixed that. That might be the cause.

```

Available versions of commons-lang3:

2022-03-03 09:19:41,344 21563 INFO [main] e.f.c.m.u.DependencyGraphUtilities - Found serialized dependency graph at resolver.graph. Deserializing.
2022-03-03 09:19:47,240 27459 INFO [main] e.f.c.m.u.DependencyGraphUtilities - Deserialized graph at resolver.graph: 5896 ms
org.apache.commons:commons-lang3:3.2.1 0 org.apache.commons commons-lang3 3.2.1
org.apache.commons:commons-lang3:3.3.1 0 org.apache.commons commons-lang3 3.3.1
org.apache.commons:commons-lang3:3.3.2 0 org.apache.commons commons-lang3 3.3.2
org.apache.commons:commons-lang3:3.2 0 org.apache.commons commons-lang3 3.2
org.apache.commons:commons-lang3:3.0 0 org.apache.commons commons-lang3 3.0
...
Trying to resolve commons-lang3:3.2...
2022-03-03 09:19:47,281 27500 WARN [main] e.f.c.m.GraphMavenResolver - Parent for revision org.apache.commons:commons-lang3:3.2 not found: Revision org.apache.commons:commons-parent:pom is not in the dependency graph. Probably it is missing in the database
Exception in thread "main" java.lang.RuntimeException: Revision org.apache.commons:commons-lang3:3.2 is not in the dependency graph. Probably it is missing in the database
        at eu.fasten.core.maven.GraphMavenResolver.dependencyBFS(GraphMavenResolver.java:275)
        at eu.fasten.core.maven.GraphMavenResolver.resolveDependencies(GraphMavenResolver.java:226)
        at eu.fasten.core.maven.MavenGraphResolverRunner.main(MavenGraphResolverRunner.java:50)
```

**Comment by proksch** [comment]
Oh, I was using `3.3.2`, but it resulted in the same mistake for me. The important change *on the PR branch*(!) is that I do not longer try to look up the parent, as this information is already contained in the artifact itself.

**Comment by proksch** [comment]
I first had to ingest version 3.2 into my local DB before I could test your example. The good news is that I can actually resolve dependencies of `commons-lang:3.2` without problems (the crash that you show above)! However, directly after, I get a crash when I try to resolve its dependents, so there seems to be another fault hidden somewhere... I will look into this.

**Comment by proksch** [comment]
I think I found the solution and it seems that the exceptions have as well been caused by the changes to the equals/hashCode methods. To fix the situation, I have reverted all these changes and brought the methods back to their original form. I have provided integration tests to document their weird behavior to prevent us from accidentally introducing this issue again in the future.

With this revert that is contained in draft-PR #418, i am able to resolve dependencies and dependents. If you want to test that locally, you can ingest `org.apache.drill:drill-common:1.17.0` into the docker compose setup, which is a direct dependent of `commons-lang3:3.2`.

**Comment by vigna** [comment]
Yes, it seems to work!
