### ISSUE TITLE
Package name in Debian API.

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten#414]
Hi @gdrosos , consider this question not urgent, please.

Anyway, I prefer to write it down to understand better.

I take this package as example:

`{"package": "python-m2crypto", "version": "0.31.0-4", "arch": "amd64", "release": "buster", "source": "m2crypto", "source_version": "0.31.0-4", "date": ""}
`

On Debian API, the package python-m2crypto doesn't exist ("package" key), instead it exists the m2crypto one ("source" key). 
This implies that the Debian license detector should take the "source" key instead of the "package" one.

Similar thing happen for, e.g.:

`{"package": "libc-client2007e-dev", "version": "8:2007f\~dfsg-6", "arch": "amd64", "release": "buster", "source": "uw-imap", "source_version": "8:2007f~dfsg-6", "date": ""}
`

`{"package": "nfs-common", "version": "1:1.3.4-2.5+deb10u1", "arch": "amd64", "release": "buster", "source": "nfs-utils", "source_version": "1:1.3.4-2.5+deb10u1", "date": ""}
`

[This is ](https://github.com/fasten-project/fasten-docker-deployment/blob/5088c6dda86862630bbee99221ddf823620a1772/test-resources/debian.coords.txt) the `debian.coords.txt` that I used.

####################################################

Related to this reasoning, I also noticed that when I try to feed with bunches of coordinates the docker-compose pipeline, all of them are included in the `fasten.debian.releases` Kafka topic, but only a few of them are then included in `fasten.cscout.out` , `fasten.RapidPlugin.out` and `fasten.MetadataDBCExtension.out.`

![Selection_028](https://user-images.githubusercontent.com/10910590/155132651-a63d2d17-120c-4eb2-8f58-8ab0a71ae42f.png)

![Selection_029](https://user-images.githubusercontent.com/10910590/155136954-1263044c-b415-44ef-835a-0a9377fe1169.png)

![Selection_030](https://user-images.githubusercontent.com/10910590/155136972-8016ea68-80ec-400a-8baf-5c84998507ac.png)

![Selection_031](https://user-images.githubusercontent.com/10910590/155136981-104b5fad-6adf-4829-b8d6-994d45e2082d.png)

I also tried to write down a diagram of the Debian pipeline, but I am not sure if it is correct (please get in touch with me on gitter, and I will send you the draw.io link to update/modify it).

![PipelineIntegrations_Debian drawio](https://user-images.githubusercontent.com/10910590/155133829-6dafae0e-f26d-4974-bf86-865efb26361b.png)

The main question is: are all the plugins in the middle correctly elaborating the `fasten.debian.releases` Kafka messages?

Please, feel free to tag more people for the answer.

**Comment by gdrosos** [comment]
Hello @michelescarlato, the diagrams oy have drawn are describing the C pipeline correctly. Regarding the `fasten.debian.releases` topic, I must do a refactoring to the cscout to see why some call graphs fail. I will start working on this issue hopefully after I haven finished some refactorings on PyCG.

**Comment by michelescarlato** [comment]
@gdrosos please let's leave open this issue, inasmuch I would really like to double-check whether or not we are correctly matching the package name in Debian.

The main question is: should I take `source` or `package` as a package name?

**Comment by gdrosos** [comment]
If the package names on the Debian API have the source name of the debian topic, then I think you should take the source as a package name.

**Comment by michelescarlato** [comment]
I close this question/issue because we understood that on Debian APIs there is information at the source/package level, while other plugins are inserting data in the db after compiling the source.
