### ISSUE TITLE
Some package-versions are missing files but still have modules and callables

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#423]
## Describe the bug
In the metadata DB, some package-versions do not have their files listed in the `files` table, but they still have `modules` and `callables`. This causes eg. the quality metrics plugin to fail, because it queries first the `files` table to match `module_id`s later.

## To Reproduce
Example: https://api.fasten-project.eu/api/mvn/packages/org.bouncycastle:bcprov-jdk15on/1.54/files
https://api.fasten-project.eu/api/mvn/packages/org.bouncycastle:bcprov-jdk15on/1.54/callables

## Expected behavior
Package-versions should have complete information in the metadata DB.

**Comment by proksch** [comment]
Which plugin is actually responsible for adding this information? Is it the `metadata-db-extension`?

**Comment by mir-am** [comment]
> Which plugin is actually responsible for adding this information? Is it the `metadata-db-extension`?

Yes, it is the job of the metadata DB plugin.

**Comment by proksch** [comment]
Didn't @ashkboos and @gousiosg introduce a simplification/change there? Could this behavior be caused by that?

**Comment by proksch** [comment]
Also, when we have to touch this anyways, we could also think about addressing #102 in the same go.

**Comment by MagielBruntink** [comment]
Ok, that clears it up. What I think might be going on is that we previously did not even get these coordinates in the DB at all because of missing info? Now we do and we have a bit more error rate in downstream plugins. Let’s accept that though. Thanks, Mehdi.

**Comment by ashkboos** [comment]
> Ok, that clears it up. What I think might be going on is that we previously did not even get these coordinates in the DB at all because of missing info? Now we do and we have a bit more error rate in downstream plugins. Let’s accept that though. Thanks, Mehdi.

Yeah, that might be. We have way more dependencies now. 
Your welcome.
