### ISSUE TITLE
Error building jar for the debian license detector - Pom.xml related error.

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten#424]
@mir-am @MagielBruntink 
Hi Amir and Magiel,

I just added a minor modification (a cleanup for json files inside the `Debian license detector plugin`), and I noticed two GH actions failing.

These GH actions are related to the license detector and the license feeder (the generic one for Java and Python). But these two plugins don't have any issues with the jar creation.

Instead, it seems that I wrote a wrong pom.xml for the Debian license detector, which breaks these two GH actions.

The strange thing is that in the previous commit ([detector](https://github.com/fasten-project/fasten/actions/runs/1957871416), [feeder](https://github.com/fasten-project/fasten/actions/runs/1957871417)), without modifying the pom.xml, these GH actions were completed correctly.

The last commit instead, is raising the error ([detector](https://github.com/fasten-project/fasten/runs/5509238484?check_suite_focus=true), [feeder](https://github.com/fasten-project/fasten/runs/5509131066?check_suite_focus=true)).

Could you please try to help me out fixing this?

I appreciate any help you can provide.
Michele

PS locally IntelliJ is ignoring that pom.xml. That's why I have no issues with testing the code improvements.
![image](https://user-images.githubusercontent.com/10910590/157850101-7bf887d6-a801-47a2-84df-d068c4523b50.png)

**Comment by MagielBruntink** [comment]
Hi @michelescarlato you need to pull in the latest changes from the develop branch, which include a version number bumb of the analyzer to 0.0.4-SNAPSHOT. Please then check your poms to refer to 0.0.4-SNAPSHOT.

**Comment by michelescarlato** [comment]
Thanks @MagielBruntink (and @mir-am ) for the precious support.
After pulling from develop, merging it into debian-license-detector-feeder, and updating accordingly the pom.xml of the Debian license detector, the two GH actions are now completed correctly.

Thanks again.
