### ISSUE TITLE
C/Debian: augmenting Metadata field for package_versions and files tables.

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten#425]
Hi @MagielBruntink ,

after a talk with Giorgos @gdrosos, a doubt remains regarding how to augment the `Metadata` field for `package_versions` and `files` tables for `C/Debian`. 

Our `license feeder` for Java is using a specific construct where:
- consuming the Kafka message (produced by the `RepoCloner`) the function [extractMavenCoordinates](https://github.com/fasten-project/fasten/blob/develop/analyzer/license-feeder/src/main/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPlugin.java#L90-L116) returns a `Revision` data type ( from to `eu.fasten.core.maven.data.Revision` ) called `coordinates`.
- These coordinates include `groupId`, `artifactId` and `version`.
AFAIK for C/Debian, we are using only `product` and `version` as coordinates (can you confirm this?).

The coordinates are then used by the [insertOutboundLicenses](https://github.com/fasten-project/fasten/blob/develop/analyzer/license-feeder/src/main/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPlugin.java#L125-L137) and [insertFileLicenses](https://github.com/fasten-project/fasten/blob/develop/analyzer/license-feeder/src/main/java/eu/fasten/analyzer/licensefeeder/LicenseFeederPlugin.java#L139-L161) functions, to augment the metadata field of the package_versions and files table. 

Do you have or did you write a similar construct to insert data in the metadata field for C/Debian ? (the same question will be for the Python use case).

Thank you in advance,
Michele

**Comment by MagielBruntink** [comment]
Hi @michelescarlato,

We update the metadata field of callables, like here: https://github.com/fasten-project/fasten/blob/53248f6314789d06b706cb537586b62116459220/analyzer/quality-analyzer/src/main/java/eu/fasten/analyzer/qualityanalyzer/MetadataUtils.java#L75

I don't see methods in `eu.fasten.core.data.metadatadb.MetadataDao` for updating package-version or files metadata; they will need to be created.

**Comment by proksch** [comment]
As far as I know, the construct `groupId:artifactId` is used in Java equivalent to how the product is used in C/Python.

**Comment by michelescarlato** [comment]
As far as I understood for both, Python and C, the groupId doesn't exist.

**Comment by michelescarlato** [comment]
@gdrosos we can close just because I am overriding in the feeder the logic used for Java (`Revision`).

But still, I can see this related to #414 .

I would really like to double-check the data inserted in the DB, once deployed on Monster.

**Comment by michelescarlato** [comment]
Solved.
Data in the DB are inserted correctly.
