### ISSUE TITLE
RepoCloner/shared volume for Python?

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten#429]
Hi @gdrosos Giorgos,

I am looking at the cleanest (and lighter) way to run Scancode (which is part of the Python license detection) against a cloned repository/decompressed package for Python.

For Java, we are using this [shared volume](https://github.com/fasten-project/fasten-docker-deployment/blob/develop/docker-compose.yml#L402) ([env](https://github.com/fasten-project/fasten-docker-deployment/blob/develop/.env#L67-L69) file), which is firstly populated by the RepoCloner and then used by the Java license detector to run Scancode.

1. Is there anything similar for Python?
2. Do you think it is possible to have a similar approach?
3. Can you point me to the code where you decompress python sources?

Thanks for your time,
M

**Comment by gdrosos** [comment]
Hello @michelescarlato, actually PyCG also stores the source code of Python Packages, and they are currently located on `/mnt/fasten/pypi/pypi/sources/` on monster. So you can retrieve the repos from there. Those repositories are also available through lima: (for example https://lima.ewi.tudelft.nl/pypi/pypi/sources/a/adafruit-circuitpython-adxl34x/1.10.2/). 

Also, after a quick search I found that on [deliverable 2.1](https://www.fasten-project.eu/download/Main/Deliverables/FASTEN%20%28825328%29_D1.2_Code%20sourcing%20process.pdf?rev=1.2) 
a tool was created  which can be used to download projects from PyPi. It can be found [here](https://github.com/fasten-project/source-populate).

**Comment by MagielBruntink** [comment]
Yep, we also use the sources put in place by PyCG in our quality analyzer plugin. Here is a message from the `fasten.PyCG.out` topic that you can use to get the sources path, as the `sourcePath` field, eg `"sourcePath": "/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0"`
```
{
   "payload": {
      "product": "namesss",
      "forge": "PyPI",
      "nodes": 9,
      "generator": "PyCG",
      "depset": [],
      "version": "0.1.0",
      "modules": {
         "internal": {
            "/setup/": {
               "sourceFile": "setup.py",
               "namespaces": {
                  "0": {
                     "namespace": "/setup/",
                     "metadata": {
                        "first": 1,
                        "last": 18
                     }
                  }
               }
            },
            "/gen_names_bozydar.gen_names_bozydar/": {
               "sourceFile": "gen_names_bozydar/gen_names_bozydar.py",
               "namespaces": {
                  "1": {
                     "namespace": "/gen_names_bozydar.gen_names_bozydar/",
                     "metadata": {
                        "first": 1,
                        "last": 11
                     }
                  }
               }
            },
            "/gen_names_bozydar/": {
               "sourceFile": "gen_names_bozydar/__init__.py",
               "namespaces": {
                  "2": {
                     "namespace": "/gen_names_bozydar/",
                     "metadata": {
                        "first": 0,
                        "last": 0
                     }
                  }
               }
            }
         },
         "external": {
            "setuptools": {
               "sourceFile": "",
               "namespaces": {
                  "3": {
                     "namespace": "//setuptools//setuptools.setup",
                     "metadata": {}
                  },
                  "4": {
                     "namespace": "//setuptools//setuptools.find_packages",
                     "metadata": {}
                  }
               }
            },
            "argparse": {
               "sourceFile": "",
               "namespaces": {
                  "5": {
                     "namespace": "//argparse//argparse.ArgumentParser",
                     "metadata": {}
                  }
               }
            },
            ".builtin": {
               "sourceFile": "",
               "namespaces": {
                  "6": {
                     "namespace": "//.builtin//print",
                     "metadata": {}
                  },
                  "8": {
                     "namespace": "//.builtin//len",
                     "metadata": {}
                  }
               }
            },
            "names": {
               "sourceFile": "",
               "namespaces": {
                  "7": {
                     "namespace": "//names//names.get_full_name",
                     "metadata": {}
                  }
               }
            }
         }
      },
      "graph": {
         "internalCalls": [],
         "externalCalls": [
            [
               "0",
               "3",
               {}
            ],
            [
               "0",
               "4",
               {}
            ],
            [
               "1",
               "5",
               {}
            ],
            [
               "1",
               "6",
               {}
            ],
            [
               "1",
               "7",
               {}
            ],
            [
               "1",
               "8",
               {}
            ]
         ],
         "resolvedCalls": []
      },
      "timestamp": "1581173493",
      "sourcePath": "/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0",
      "metadata": {
         "loc": 21,
         "time_elapsed": 0.08,
         "max_rss": 19924,
         "num_files": 3
      }
   },
   "plugin_name": "PyCG",
   "plugin_version": "0.0.1",
   "input": {
      "product": "namesss",
      "version": "0.1.0",
      "version_timestamp": 1581173493,
      "requires_dist": []
   },
   "created_at": 1648114604
}
```

**Comment by gdrosos** [comment]
Thank you very much @MagielBruntink for the clarificarion. Also the code responsible for downloading the source packages for pycg can be found [here](https://github.com/fasten-project/pypi-tools/blob/b2c591dec180c0eaa333644055f2996994cb9139/cg-producer/entrypoint.py#L211).

**Comment by michelescarlato** [comment]
Thanks both, Giorgos and Magiel @gdrosos @MagielBruntink .

A rapid way to retrieve the correct path seems to me the following:
1. In `Python` **_we don't need_** `Flink` (whose goal is to sync two different Kafka topics), because `pycg` is the plugin in charge of cloning the repository (while for Maven Opal and RepoCloner are two different plugins).
2. As indicated in the next diagram, the `license detector` is triggered by the `fasten.MetadataDBPythonExtension.out`.
3. So, the `license detector` should look for `sourcePath` recursively inside of the input key of the `fasten.MetadataDBPythonExtension.out` .
4. Manipulate the `sourcePath` string: `/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0`, removing the `/revision-callgraphs/` directory, in order to finally have `/mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0`.


I report here a schema that Giorgos wrote recently to double-check the correctness of the reasoning.
![image](https://user-images.githubusercontent.com/10910590/160274124-59a7ea94-9131-4e34-b35e-1abf3a8b8395.png)


If both @gdrosos and @MagielBruntink agree upon the reasoning, I will start to implement this logic as soon as possible.

Thanks for your time and the special instructions.

**Comment by MagielBruntink** [comment]
Yes, LGTM. This is the same approach as our RAPID plugin for quality metrics.

**Comment by gdrosos** [comment]
> Thanks both, Giorgos and Magiel @gdrosos @MagielBruntink .
> 
> A rapid way to retrieve the correct path seems to me the following:
> 
> 1. In `Python` **_we don't need_** `Flink` (whose goal is to sync two different Kafka topics), because `pycg` is the plugin in charge of cloning the repository (while for Maven Opal and RepoCloner are two different plugins).
> 2. As indicated in the next diagram, the `license detector` is triggered by the `fasten.MetadataDBPythonExtension.out`.
> 3. So, the `license detector` should look for `sourcePath` recursively inside of the input key of the `fasten.MetadataDBPythonExtension.out` .
> 4. Manipulate the `sourcePath` string: `/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0`, removing the `/revision-callgraphs/` directory, in order to finally have `/mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0`.
> 
> I report here a schema that Giorgos wrote recently to double-check the correctness of the reasoning. ![image](https://user-images.githubusercontent.com/10910590/160274124-59a7ea94-9131-4e34-b35e-1abf3a8b8395.png)
> 
> If both @gdrosos and @MagielBruntink agree upon the reasoning, I will start to implement this logic as soon as possible.
> 
> Thanks for your time and the special instructions.

LGTM also.

**Comment by michelescarlato** [comment]
Hi Giorgos @gdrosos ,

I would need some help debugging this.

When I run Scancode upon this path:
`/mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0`, it cannot find it.
This is the [docker-compose.yml](https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/docker-compose.yml) that I am using, and this the [.env](https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/.env) file.

Here is the python-license-detector output.

```
[2022-03-29 05:56:35,513] [INFO ] [main] [e.f.a.p.PythonLicenseDetectorPlugin$PythonLicenseDetectorExtension] - Python license detector started.
sourcePath
/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0
/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0
/mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0
[2022-03-29 05:56:35,519] [INFO ] [main] [e.f.a.p.PythonLicenseDetectorPlugin$PythonLicenseDetectorExtension] - Scanning project in /mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0...
/usr/local/bin/scancode/src/cluecode/copyrights.py:3128: FutureWarning: Possible set difference at position 3
  re.MULTILINE | re.UNICODE
/usr/local/bin/scancode/lib/python3.7/site-packages/nltk/tag/sequential.py:532: FutureWarning: Possible nested set at position 7
  self._regexs = [(re.compile(regexp), tag,) for regexp, tag in regexps]
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try the 'scancode --help' option for help on options and arguments.

Error: Invalid value for "input": Path "/mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0" does not exist.
[2022-03-29 05:56:36,719] [ERROR] [main] [e.f.a.p.PythonLicenseDetectorPlugin$PythonLicenseDetectorExtension] - Scancode returned with exit code 2.

[2022-03-29 05:56:36,742] [WARN ] [kafka-producer-network-thread | eu.fasten.analyzer.pythonlicensedetector.PythonLicenseDetectorPlugin.PythonLicenseDetectorExtension_producer] [o.a.k.c.NetworkClient] - [Producer clientId=eu.fasten.analyzer.pythonlicensedetector.PythonLicenseDetectorPlugin.PythonLicenseDetectorExtension_producer] Error while fetching metadata with correlation id 3 : {fasten.PythonLicenseDetectorExtension.err=LEADER_NOT_AVAILABLE}
[2022-03-29 05:56:36,854] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Successfully processed normal message offset 0 from partition 0.
[2022-03-29 05:56:36,858] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Committed offsets [0] of partitions [0].
[2022-03-29 05:56:36,860] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Read normal message offset 1 from partition 0.

```


Any hint regarding this?

(@MagielBruntink  Also Magiel, if he can helps to understand where the problem is, it would be very helpful)

Thanks for your time.


https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/docker-compose.yml

**Comment by MagielBruntink** [comment]
Something is wrong with the path that the python-license-feeder tries to look. At line 2 of the log it says
`/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0` which is the correct path, I think.
but later it reports `"/mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0" does not exist.` which is not the right path.

**Comment by MagielBruntink** [comment]
For the python-license-feeder container, the `/mnt/fasten` directory is bound to the directory `fasten-docker-deployment/docker-volumes/fasten/python` on the local filesystem. Within that directory you should see the directory structure and whether the expected files are there.

If I look in `fasten-docker-deployment/docker-volumes/fasten/python/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0` the sources are definitely there. The container should be able to find them at `/mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0`.

**Comment by michelescarlato** [comment]
> Hello @michelescarlato, actually PyCG also stores the source code of Python Packages, and they are currently located on `/mnt/fasten/pypi/pypi/sources/` on monster. So you can retrieve the repos from there. 

Sry @MagielBruntink , but I was relying on this info. 
I also described at point 4. of my last comment the procedure I was going to write:

>  Manipulate the sourcePath string: /mnt/fasten/revision-callgraphs/pypi/pypi/sources/n/namesss/0.1.0, removing the /revision-callgraphs/directory, in order to finally have /mnt/fasten/pypi/pypi/sources/n/namesss/0.1.0.


Anyway thanks for the support! I will test, and hopefully close this issue...

**Comment by MagielBruntink** [comment]
I would advise against doing path manipulation in the plugin itself, instead use a command line argument to specify the sources path, eg. in docker-compose.yml
` "-po", "PythonLicenseDetectorExtension=/mnt/fasten/revision-callgraphs/pypi/pypi/sources"`
Most other plugins also do that, `-po` is the default argument to use. This way, specifics of each deployment can be easily accounted for.

**Comment by michelescarlato** [comment]
Currently fixed. Scancode starts and performs the scan.

> I would advise against doing path manipulation in the plugin itself, instead use a command line argument to specify the sources path, eg. in docker-compose.yml ` "-po", "PythonLicenseDetectorExtension=/mnt/fasten/revision-callgraphs/pypi/pypi/sources"` Most other plugins also do that, `-po` is the default argument to use. This way, specifics of each deployment can be easily accounted for.

Sorry, but I am not understanding very well, do you think I need to add:
PythonLicenseDetectorExtension=/mnt/fasten/revision-callgraphs/pypi/pypi/sources
[here](https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/docker-compose.yml#L420-L421) ?

**Comment by michelescarlato** [comment]
I was waiting for Magiel input regarding his last comment. Never mind.
