### ISSUE TITLE
repoUrl with GitHub coordinates for Python packages?

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten#430]
Dear @gdrosos and @MagielBruntink,

In Java, for the outbound license detection, we do this:
1. we control the pom.xml,
2. if nothing is found, we try with the GitHub APIs.

As far as I can observe, for Java, [we are controlling if the URL ](https://github.com/fasten-project/fasten/blob/789cb6d17d2af52592c60df549b0660b62544ff3/analyzer/license-detector/src/main/java/eu/fasten/analyzer/licensedetector/LicenseDetectorPlugin.java#L209-L278)contained in the `repoUrl` (taken from the `RepoCloner.out` ) is a valid GitHub link, and we then perform the API query.

To extract the `repoUrl` we use [this](https://github.com/fasten-project/fasten/blob/789cb6d17d2af52592c60df549b0660b62544ff3/analyzer/license-detector/src/main/java/eu/fasten/analyzer/licensedetector/LicenseDetectorPlugin.java#L302-L318) method.

As far as I remember if a GitHub URL is there, is thank to some components (Web crawler, maybe?) that is in charge of searching if a given source/package is also hosted in GitHub.

@gdrosos are you aware if there are any chances of having a GitHub URL for Python packages?

@MagielBruntink , do you think it is possible to adapt the crawler also for Python (as far as I remember it has been developed Maven specific, please correct me if I am wrong) ?

PS for the outbound Python license detection the main approach is:
1. we ask license information to the pypi APIs,
(optional) 2. if nothing is found, it would be nice, try with the GitHub APIs.

**Comment by gdrosos** [comment]
Hello, we do not store at any topic any Github URL for Python Packages. 

But after a quick search, I found that pypi offers a json api (you can see the docs [here](https://warehouse.pypa.io/api-reference/json.html)) where you can potentially retrieve a github url.
 For example, I see on request  https://pypi.org/pypi/pycg/json the `Homepage` key contains the Github url whereas on https://pypi.org/pypi/Django/json the `Source` key contains the Github url.

**Comment by michelescarlato** [comment]
Thank you.
