### ISSUE TITLE
Populating pypi.coords.txt with more entries.

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/fasten#437]
Hi @gdrosos Giorgos,

May ask you for a small help for increasing the number of packages to feed the pipeline (I am referring to [pypi.coords.txt](https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/test-resources/pypi.coords.txt) )?

Unluckily, for the packages we are currently scanning, Scancode is not retrieving any license (I guess). That's why the `files` table is not storing licenses information (while the `package_versions` is fulfilled with them).

Also, unluckily, there is no license information from PyPI for the current set of packages (all the licenses have been retrieved from GitHub).

Feel free to commit there ( [pypi.coords.txt](https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/test-resources/pypi.coords.txt) ) as many coordinates you want (but plz not more than 100 entries .... also 20 would probably be enough!). Meanwhile I will try to understand the status of [426](https://github.com/fasten-project/fasten/issues/426) (which is an open issue for the Java pipeline) and provide there my contribute.

Thanks for your time and understanding.
Sincerely,
M

PS Sorry but this is blocker for PyPI plugin development.

**Comment by gdrosos** [comment]
Hello @michelescarlato, after a quick search I came up with a file containing many packages, so from those  you can select the ones that Scancode can retrieve licensing information, so that you can test your tool: 
https://github.com/fasten-project/pypi-tools/blob/master/kafka-filter-pypi/example_input.json

**Comment by michelescarlato** [comment]
short update: I pushed [this new list](https://github.com/fasten-project/fasten-docker-deployment/blob/aabb4c9b0c23aea545974efb1bebdb7b20b25dd8/test-resources/pypi.coords_long.txt), I will elaborate the [missing packages](https://github.com/fasten-project/fasten-docker-deployment/blob/python-license-detection-feeder/test-resources/pypi.coords_30_still_manipulate.txt) as soon as I can.

Anyway, on this first run, it seems that Scancode is not finding any license information in the files.
I will update it here.
But please, let's leave this issue open because I really need to be sure that the detection at the file level is functioning, and so far it is not provable.

**Comment by michelescarlato** [comment]
A few commits fixed the situation.

Particularly [this](https://github.com/fasten-project/fasten/commit/028201e2f81f9825193c03d3dc6553057c68dc92) and [this](https://github.com/fasten-project/fasten/commit/c4f5d5bcc16fb26de2bc33d58b3edca47f4094eb).

Improvement from our side, populating the metadata field should be done (still I can see useless information there).

![image](https://user-images.githubusercontent.com/10910590/161125988-f039ba1d-599c-4665-a4ab-cfee5b6877ce.png)
