### ISSUE TITLE
Is the heartbeat call in FASTEN server still needed?

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#448]
Are we sure the heartbeat call in the FASTEN server is really necessary? I have reason to think it slows down the processing of messages. This can be observed with the QualityAnalyzer Metadata plugin, for instance, which processes quite a lot of them (1 per callable). 

How can we test whether the heartbeat is needed?
https://github.com/fasten-project/fasten/blob/df4726863ea2e2b86e85a7c3d5ea3cd8d09ddc69/server/src/main/java/eu/fasten/server/plugins/kafka/FastenKafkaPlugin.java#L222

**Comment by mir-am** [comment]
@MagielBruntink,
To keep the normal consumer alive, the `sendHeatBeat` call is needed when the FASTEN server is processing priority records.
In other words, the `sendHeatBeat` call should not be called when the FASTEN server is only processing one topic, i.e., normal topic.
I can look into the FASTEN server to optimize the code for the case where only the normal topic is given.

**Comment by mir-am** [comment]
I have created PR #449 to address this issue. There might also be other possible optimizations that we can make for handling Kafka consumers.
