### ISSUE TITLE
Release the project on Maven 

### ISSUE THREAD

**Issue by ilyagrishkov** [fasten-project/fasten#54]
## Is your feature request related to a problem? Please describe.
It's currently impossible to have dependencies on some modules of the project from outside the project. E.g. WALA and OPAL v1 call graph generators are in different repositories and both of them need a dependency on the FASTEN core. Having FASTEN released on Maven would allow to have those dependencies. 

## Describe the solution you'd like
Creating a workflow that would push the project to Maven on every release would solve this problem.

## Additional context
Having Maven releases will also increase maintainability of plugins in different repositories that depend on FASTEN as the code will be consistent across dependent project.

**Comment by proksch** [comment]
The new loader platform releases all Maven packages in the GH package registry. This is not Maven central yet, but at least allows for others to use the project results. As we will migrate all plugins in the coming weeks/months, this issue will become obsolete soon.
