### ISSUE TITLE
Improve RepoCloner

### ISSUE THREAD

**Issue by MihhailSokolov** [fasten-project/fasten#58]
## Is your feature request related to a problem? Please describe.
* Plugin does not report any errors, even though they do happen.
* Partners asked to copy `commitTag` and `sourcesUrl` from the output of POM Analyzer to the output of RepoCloner.

## Describe the solution you'd like
* Error handling should be improved
* Plugin should produce `commitTag` and `sourcesUrl` along with `repoPath` and maven coordinate as an output

**Comment by cg122** [comment]
I also found that if repo is not available, 'repoPath' field is not included in the generated message. Could it be better to include the field(key) with empty value (like "repoPath" : " ")?

**Comment by MihhailSokolov** [comment]
> I also found that if repo is not available, 'repoPath' field is not included in the generated message. Could it be better to include the field(key) with empty value (like "repoPath" : " ")?

Yes, will do. Thanks for noticing.
