### ISSUE TITLE
Wiki uses mvn-crawler Docker image

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#74]
The [Development Environment wiki page](https://github.com/fasten-project/fasten/wiki/Development-Environment) makes use of the [`mvn-crawler`](https://github.com/fasten-project/mvn-crawler/commits/master) Docker image in its step-by-step guide.\
Yet, its Dockerfile has been removed in https://github.com/fasten-project/mvn-crawler/commit/0ea00f8190dab8d5d65a0d9794916e49825dce6b#diff-1eef4e1e3eb8b97aec14b6bbd5332799.

**Comment by mir-am** [comment]
Thanks for pointing out the inconsistency in the wiki page. I have updated the development page for installing and using the crawler.

**Comment by marcomicera** [comment]
Nice, thanks!
