### ISSUE TITLE
Add 'release time' in the output topic of RepoCloner.

### ISSUE THREAD

**Issue by cg122** [fasten-project/fasten#75]
## Problem

Version tags may not be always available for the repository, so we will have problem to check out the right version of source code in this case. By adding the 'release time', it will allow some heuristic based checkout of the right version when tags are absent.

## Solution

Add 'release time' or any other useful information (not sure yet, if anyone has suggestions) to help checking out the right version of source code in the output topic of RepoCloner.

**Comment by MihhailSokolov** [comment]
Added in #76 as `date`. [Wiki page](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenrepocloner) has also been updated accordingly
