### ISSUE TITLE
Update 'repoUrl' field location in wiki

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#77]
The `repoUrl` field of the [`fasten.POMAnalyzer.*` Kafka topic](https://github.com/fasten-project/fasten/wiki/Kafka-Topics#fastenpomanalyzer) has been moved from `input` to `payload` in #71.
That wiki paragraph needs to be updated accordingly.

**Comment by MihhailSokolov** [comment]
Updated, thanks for noticing
