### ISSUE TITLE
Add type of SCM for checking out source code in the output of RepoCloner

### ISSUE THREAD

**Issue by cg122** [fasten-project/fasten#84]
## Problem
As there are multiple repo types of SCM (git, hg, svn, ...) used for storing the repository of maven project, it will be good to have information of which type of SCM associated with the 'repoPath'.

## Solution
Add 'repoType' field in the fasten.RepoCloner.out

**Comment by MihhailSokolov** [comment]
Implemented in b0c59c0
RepoCloner output now contains `repoType` which can be `git` for Git repository, `svn` for SVN repository, `hg` for Mercurial repository, or empty if could not clone or determine the type of repository.
