### ISSUE TITLE
Retrieving edges from KB takes too long

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#85]
## Is your feature request related to a problem? Please describe.

#80 aims to implement the REST API to access the KnowledgeBase.
The [_edges_ endpoint](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#edges) `GET /mvn/packages/{pkg}/{pkg_ver}/edges` should return all incoming and outgoing edges of a given package version.

The only way to access those edges is through the `callables` table, as visible from the [schema](https://user-images.githubusercontent.com/8766163/93773151-06b68780-fc20-11ea-8a9e-8166ee80dfc6.png).
For this reason, I am creating a view containing all callables given a package name and version:

```sql
CREATE OR REPLACE VIEW callable_ids AS
SELECT  c.id
FROM    packages AS p JOIN
        package_versions AS pv ON p.id = pv.package_id JOIN
        modules AS m ON pv.id = m.package_version_id JOIN
        callables AS c ON m.id = c.module_id
WHERE   p.package_name = <packageName> AND
        pv.version = <packageVersion>
```

A quick sketch of its algebraic tree shows that it might theoretically contain up to ~1.9B entries, in the absolute worst case ever (see details below), so this could _theoretically_ be a first problem. However, for the sake of this issue, I will be using a package name and version that will cause this view to contain exactly 30 rows, i.e., package `com.lemoulinstudio.jnag:jnag-utils-jse-rds`, version `1.2.1`.

<details>
<summary>Quick algebraic tree reasoning</summary>

1. #### The `packages` table

    It contains ~200K rows. Its `WHERE` clause narrows its contribution to 1, given the fact that:

    ```sql
    SELECT COUNT(DISTINCT package_name) FROM packages
    ```

    returns exactly the same number of rows it contains.

2. #### The `package_versions` table

    It has ~2.8M entries, with a reduction factor of ~100K for its `version` field, so on average ~28 possible entries for a given version.

3. #### Inner join between `packages` and `package_versions`

    In the worst case, there might be all package versions for the selected package, resulting in a contribution of ~28 rows.

4. #### The `modules` table

    ~22.3M rows.

5. #### Inner join between 3. and `modules`

    In the worst case, all modules may refer to an existing package (version), resulting in a contribution of ~22.3M rows.

6. #### The `callables` table

    ~1.9B rows.

7. #### Inner join between 5. and `callables`

    In the worst case, all callables belong to all modules and package versions, resulting in a contribution of ~1.9B rows.

</details>

---

Such a view would be used by the following query:

```sql
SELECT  *
FROM    edges
WHERE   source_id IN (SELECT id FROM callable_ids) OR
        target_id IN (SELECT id FROM callable_ids)
```

The `edges` table is 3473 GB:

```sql
SELECT  pg_size_pretty (pg_relation_size('edges'));
```

With roughly 22 billion rows:

```sql
SELECT  n_live_tup
FROM    pg_stat_user_tables
WHERE   relname = 'edges';
```

This takes way too long, causing our Servlet engine to timeout.

## Describe the solution you'd like

Personally, I would avoid using the `edges` table completely and only use the graph database which I have heard mentioned (@ilyagrishkov any news on this? 🙂).
If I'm not wrong, the only argument in favor of maintaining such a table was the lack of the `source_id` and `target_id` fields in the graph database.
<sub>_On a side note, using that graph database might also help with the `callables` endpoints._</sub>

To conclude, while I acknowledge that it may be hard to enforce consistency in two different databases, I do not know whether it would be worth to create indexes on those two fields.
Given its size, it is impossible to determine how many different values of callable IDs the `edges` table contains, i.e.:

```sql
SELECT  COUNT(DISTINCT source_id)
FROM    edges
```

If this number is high, Postgres might perform a table scan anyway.

Another option would be to insert redundancy so that I can avoid traversing big portions of the KnowledgeBase's E-R diagram while querying (in particular, `packages`.`package_name` and `package_versions`.`version` in `callables`, if possible/makes sense).

**Comment by gousiosg** [comment]
I am not sure why you need to create an intermediate view. What is wrong with a simple join?

```sql
select e.src, e.target 
   from edges e 
    join callables c on e.src = c.id
    join modules m on m.id = c.module_id 
--- other join conditions
```

**Comment by ilyagrishkov** [comment]
@gousiosg Are there any reasons why we wouldn't use graph database for it?

**Comment by gousiosg** [comment]
Yes, the graph DB only contains ids, which will need to be resolved against the callables table as well

**Comment by gousiosg** [comment]
I mean let's first try the simple solution and see if it works and then we can think of more elaborate schemes

**Comment by marcomicera** [comment]
> I am not sure why you need to create an intermediate view. What is wrong with a simple join?

Nothing, my bad. Sorry for not seeing the already-existing multicolumn B-Tree index on `edges`.`source_id` and `edges`.`target_id`. If the [response body](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#edges) is correct (`edges.*`), then a single join will do the job. Sorry for the hassle.
