### ISSUE TITLE
REST API unit tests

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#87]
Endpoints are implemented in the [`eu.fasten.analyzer.restapiplugin.api.mvn.impl`](https://github.com/fasten-project/fasten/tree/kbapi/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl) package, where they all use methods of the [Metadata Data Access Object `MetadataDao.java`](https://github.com/fasten-project/fasten/blob/kbapi/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java).

Testing those methods requires DB mocking, and it could be done with [Testcontainers](https://www.testcontainers.org) as in #92.\
I would use Java's Dependency Injection to inject the mock DB during tests. More specifically, I think the following field should be `@Inject`ed:

https://github.com/fasten-project/fasten/blob/c6d80175996f4a408cd8fc55e9239a7cf45a2aed/core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java#L43

Such a field is normally initialized with a setter of the [`DBConnector` interface](https://github.com/fasten-project/fasten/blob/kbapi/core/src/main/java/eu/fasten/core/plugins/DBConnector.java):

https://github.com/fasten-project/fasten/blob/c6d80175996f4a408cd8fc55e9239a7cf45a2aed/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/RestAPIPlugin.java#L102-L106

But we do not want to start the whole extension (hence the whole REST server) to be able to run unit tests.

**Comment by marcomicera** [comment]
I've been trying to add CDI support to our embedded Jetty, but unfortunately, I had no success.
I've followed:
- [The official Jetty guide](https://www.eclipse.org/jetty/documentation/current/framework-weld.html#weld-embedded) on how to include Weld;
- A [Jetty + Weld MWE](https://github.com/stilkov/jetty-weld-sample) that works on my machine.

@proksch time for me to ask for some help. Is there anyone else willing to work on the API with me?

**Comment by proksch** [comment]
Skimming #80, it seems that there is no `beans.xml` in the `src/main/resources/META-INF` folder, which I think should be required to make CDI work. Or what is the problem, maybe you can elaborate a bit on what's not working.

**Comment by marcomicera** [comment]
> Skimming #80, it seems that there is no `beans.xml` in the `src/main/resources/META-INF` folder, which I think should be required to make CDI work.

Indeed, I didn't push non-functioning code on that branch. I've now pushed my attempt on the [`api-cdi` branch](https://github.com/fasten-project/fasten/tree/api-cdi) (https://github.com/fasten-project/fasten/commit/9524a9303613452d423abcfd1ca9bb3b304ffd96).

> Or what is the problem, maybe you can elaborate a bit on what's not working.

Well, after having followed this guide:

> * [The official Jetty guide](https://www.eclipse.org/jetty/documentation/current/framework-weld.html#weld-embedded) on how to include Weld;

I still get a `NullPointerException` on the field I want Weld to inject:

https://github.com/fasten-project/fasten/blob/9524a9303613452d423abcfd1ca9bb3b304ffd96/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/FileApi.java#L12-L15

Note that this is not strictly needed for testing, but I would be using the same technique anyway, so I started by trying injection within the same Maven module.

For your convenience:

```bash
$ export PORT=... && curl http://localhost:$PORT/mvn/packages/com.lemoulinstudio.jnag:jnag-utils-jse-rds/1.2.1/files

[...] ERROR 500 [...] java.lang.NullPointerException
```

I must be doing something wrong with CDI for embedded Jetty.
