### ISSUE TITLE
Make sure the REST API handles concurrent requests

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#93]
How does RESTeasy behave with multiple concurrent requests?

**Comment by marcomicera** [comment]
Our REST API only has `GET` endpoints, so we don't have to worry about data consistency.

As far as concurrency is concerned, I haven't found clear evidence that RESTeasy handles concurrent requests in separate threads. Moreover, the [documentation](https://docs.jboss.org/resteasy/docs/4.5.8.Final/userguide/html_single/index.html#Asynchronous_HTTP_Request_Processing) suggests using asynchronous HTTP request processing in these cases:

> The primary use case for Asynchronous HTTP is in the case where the client is polling the server for a delayed response. The usual example is an AJAX chat client where you want to push/pull from both the client and the server. These scenarios have the client blocking a long time on the server’s socket waiting for a new message.

I don't think this is our case though.

> (in fact using asynchronous processing may actually hurt your performance in most common scenarios)

---

We can still come up with a stress test and compare our current implementation with a multithreaded one.
Practically, this could be achieved by running endpoints' logic into separate threads, so this:

https://github.com/fasten-project/fasten/blob/cdbb924eadee9c60de445e2eb496683c3c1d36c7/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/FileApi.java#L16-L26

Might turn into this (tested & working):

```java
@GET
@Path("/{pkg}/{pkg_ver}/files")
@Produces(MediaType.APPLICATION_JSON)
public void getPackageFiles(@Suspended final AsyncResponse response,
                            @PathParam("pkg") String package_name,
                            @PathParam("pkg_ver") String package_version,
                            @DefaultValue("0")
                            @QueryParam("offset") short offset,
                            @DefaultValue(RestApplication.DEFAULT_PAGE_SIZE)
                            @QueryParam("limit") short limit) {
    new Thread(() -> {
        Response result = service.getPackageFiles(package_name, package_version, offset, limit);
        response.resume(result);
    }).start();
}
```

Our endpoints wouldn't be returning `Response` objects anymore, but clients would have to pass `AsyncResponse`s as arguments.

**Comment by MihhailSokolov** [comment]
Consider using [h2load](https://nghttp2.org/documentation/h2load-howto.html) for load testing when most of the stuff is done.

**Comment by marcomicera** [comment]
@MihhailSokolov 

>   With Spring's embedded Tomcat, it'll be possible with a simple `server.tomcat.max-threads=20` in the [server configuration file](https://github.com/endocode/fasten/blob/c4935e593615cdf553f7f5e30356d945a39b1188/analyzer/restapi-plugin/src/main/resources/application.properties).

**Comment by MihhailSokolov** [comment]
> @MihhailSokolov
> 
> > With Spring's embedded Tomcat, it'll be possible with a simple `server.tomcat.max-threads=20` in the [server configuration file](https://github.com/endocode/fasten/blob/c4935e593615cdf553f7f5e30356d945a39b1188/analyzer/restapi-plugin/src/main/resources/application.properties).

Done in 6d5a9a6
